### ISSUE TITLE
win installer getting the error "Server shutdown unexpectedly with code 216."

### ISSUE THREAD

**Issue by MaxPeal** [httptoolkit/httptoolkit#100]
[Window Title]
Error

with the win installer HTTP.Toolkit-1.0.0.Setup.exe
i just gett the error:
----------------
[Main Instruction]
HTTP Toolkit hit an error

[Content]
Server shutdown unexpectedly with code 216.

Please file an issue at github.com/httptoolkit/feedback.

[OK]
----------------

how can i debug it?

and please add also a standalone zip for windows!

**Comment by pimterry** [comment]
What version of Windows are you running? I think there's an issue due to a recent update where Windows 7 and older aren't currently supported. Support from Microsoft for Windows 7 also ended in January this year (so I'd definitely suggest updating!).

Does that sound like it might be your issue? If so, don't panic - I'm going to be publishing some updates to avoid crashing in this case, likely in the next day or two, so just hold tight! Windows 7 still won't be 'officially' supported though, and there could be unpredictable issues in the future. Now that it's an officially unsupported version of Windows, reliably supporting it fully is tricky, but I'll try to keep it working for as long as I can.

**Comment by pimterry** [comment]
@MaxPeal I've just released a new version of the app which _should_ fix this. I don't actually have a Windows 7 machine available for testing though! Can you try it out? You'll have to manually update your app: go to https://httptoolkit.tech and download & install the latest release from there, and let me know if that fixes this for you.

**Comment by MaxPeal** [comment]
@pimterry yes with the commit https://github.com/httptoolkit/httptoolkit-desktop/commit/ac1e12d5b53c7c2ab12c83808ba0d5fd387993b5
it works now also again on my Windows 7 test machine.

**Comment by pimterry** [comment]
Ok, great! Thanks for letting me know
