### ISSUE TITLE
Error: Could not instantiate: ProductRegistryImpl

### ISSUE THREAD

**Issue by meisamzolfaghari** [httptoolkit/httptoolkit#113]
i'm facing below error on startup and the first page stops going to main page...
errors : 
![Screenshot from 2020-11-19 15-07-15](https://user-images.githubusercontent.com/57758725/99661340-ef0d4b00-2a78-11eb-8224-21ff25ec87eb.png)

stops on this page
![Screenshot from 2020-11-19 15-07-35](https://user-images.githubusercontent.com/57758725/99661405-06e4cf00-2a79-11eb-8e7b-e49b78bc991a.png)

Google Chrome 87.0.4280.66
ubuntu linux 20.04 lts
httptoolkit 1.02 amd64

**Comment by pimterry** [comment]
According to https://github.com/electron/electron/issues/12185 the `ProductRegistryImpl.Registry` is a known issue that doesn't actually break anything in the app, it's just an annoying warning about a devtools issue, so that shouldn't cause this.

You will generally see the app fail to load if the proxy server & app interceptor process doesn't respond somehow - either it can't listen on the ports it needs, or something crashes when generating certificates, detecting the available browsers, etc. I'm not sure what would cause that, there's not many possible failures here, and in most common cases where that process crashes there would be an alert with an error shown. If there isn't, presumably it's running but just not responding...

Is there any other output shown in the terminal if you scroll back before the `ProductRegistryImpl` messages? If you open the devtools in the app (View -> Toggle DevTools) is there anything shown in the console there?

**Comment by meisamzolfaghari** [comment]
there's nothing more in terminal

here's the consol log
![Screenshot from 2020-11-19 15-25-25](https://user-images.githubusercontent.com/57758725/99663207-7eb3f900-2a7b-11eb-8a9d-dd3402c509cb.png)

**Comment by pimterry** [comment]
Huh, that error suggests the UI on your machine is corrupted. You can reload it from the developer tools console there: go to the Application tab, then 'Clear Storage', and click 'Clear site data' (leaving every box ticked), and reload the UI (Ctrl-R).

I'm not sure how you could get into that state - somehow your app has downloaded an update to the UI, and cached it successfully, but the updated version is corrupted. Presumably the server is actually loading correctly, and it's just that the UI doesn't initialize enough to try and talk to it, I've never seen that before!

**Comment by meisamzolfaghari** [comment]
thank's that worked :+1:
