### ISSUE TITLE
Support intercepting your existing default Chrome profile

### ISSUE THREAD

**Issue by tilmans** [httptoolkit/httptoolkit#118]
I like to run Chrome manually from the command line with the proxy setting since it's more convenient than the (empty) Chrome started from HTTP Toolkit. This worked fine until I tried to connect to localhost. It took me a while (and another issue with a useful link) to figure out Chrome skips the proxy on localhost connections.

The correct way to do this is:
`/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary --proxy-server=localhost:8000 --ignore-certificate-errors --proxy-bypass-list="<-loopback>"`

Maybe you could add this to the intercept templates? Basically a "non-fresh" Chrome window which is useful if you need bookmarks, saved passwords etc.

Thanks
---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Interesting! Good idea, and yes, I'd 100% like to support intercepting existing windows.

Does that command work for you when you have existing Chrome windows open already though? I thought that because Chrome shared a profile between windows, if you have any existing windows then most settings will be shared too, so these kinds of command line options would be ignored in most use cases.

I'm open to exposing this in the UI, but if possible I'd rather support intercepting existing windows automatically somehow, rather than providing manual workarounds... If the above profile concerns don't apply so there's a single command that will work to do this automatically then that's amazing of course, and I can just expose that directly.

If not, I think there's still at least one route through here, by globally trusting the CA on your system... With that, you then just need to toggle the proxy settings, and that can be done dynamically, e.g. with a Chrome extension. What do you think?

**Comment by pimterry** [comment]
> I'm actually not trying to intercept existing windows ... I'm just trying to use my regular Chrome profile

I think those are the same though, if Chrome is already running. Unless I'm missing something, you can only have one running Chrome session per profile directory. If you open Chrome again, it just creates a new window in the same session and ignores any command line arguments or options. E.g. on my machine, with Chrome already open:

```bash
$ google-chrome --proxy-server=localhost:8000
Opening in existing browser session.

$ # Exits immediately, new window ignores that proxy setting
```

Do you not have Chrome running already? Or is there a trick that I'm missing somewhere?

**Comment by tilmans** [comment]
The trick is that I don't use Chrome for anything but dev work :) 
+ sometimes I might use Canary as a second Chrome.

I do realize it's an edge case so maybe not worth adding specific support for. It would still be nice to have a link to an FAQ with the different command-lines for different browser though.

**Comment by pimterry** [comment]
Ahhhh, that's it :smiley:. Makes sense! But I have heard similar requests elsewhere, and there is something here... I think there could be a Chrome interception option that:

* Checks if Chrome is running
  * If so, shows a warning
  * If accepted, cleanly closes the root Chrome process to shut it down
* Then starts a normal Chrome process with no special profile, just passing `--restore-last-session` if we killed Chrome (to make sure we bring back whatever you had open) plus everything we do for fresh Chrome windows.

That should just work, I've just tested it manually, all seems to work very nicely. Should work for Edge/etc too. Interesting...

There's a couple of caveats:
* We need to find the root Chrome process (the one with no `--type` argument) and kill it, reliably, cross-platform. Bit tricky, but not so bad.
* When HTTP Toolkit exits, it would need to kill and restart Chrome again too (as it'll stop working without the proxy).

This sounds fun, I'm going to try it right now :smiley:

**Comment by pimterry** [comment]
> This sounds fun, I'm going to try it right now :smiley:

I tried it, it turns out this is actually _very_ practical, it's now live.

You'll need server 1.1.0+. Your app will update in the background automatically next time you run it, and 'Existing Chrome' will appear the following run. Click it, and it'll launch Chrome with your default profile but all the other extra interception options injected automatically. It Chrome's already running, it'll warn you before it kills & restarts it automatically. I'll close this issue now - give that a go, let me know if it works for you!

**Comment by tilmans** [comment]
Works well, thanks a lot!
