### ISSUE TITLE
Node.js not working in HTTP Toolkit terminal

### ISSUE THREAD

**Issue by nicholaskajoh** [httptoolkit/httptoolkit#120]
When I try to set up a fresh or existing terminal, I get the following output:
```
node: Toolkit.app/Contents/Resources/httptoolkit-server/overrides/js/prepend-node.js" is not supported in NODE_OPTIONS
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `npm config delete prefix` or `nvm use --delete-prefix v8.16.2 --silent` to unset it.
```

If I try to run node or npm I get this error:

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '"/Applications/HTTP'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:901:12)
    at preloadModules (internal/bootstrap/node.js:601:7)
    at startup (internal/bootstrap/node.js:285:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

Running `npm config delete prefix` or `nvm use --delete-prefix v8.16.2 --silent` doesn't help.

I'm on macOS Catalina v10.15.7

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @nicholaskajoh which version of node are you using? From the error there, it looks like it's v8.16.2.

This is a known issue for Node 8, but Node 8 is also end-of-life since 2019. The issue is that HTTP Toolkit intercepts node using a `NODE_OPTIONS` env var set to:

```
--require "/Applications/HTTP Toolkit.app/Contents/Resources/httptoolkit-server/overrides/js/prepend-node.js"
```

This injects the node interception setup. This works fine in all current node releases (v10+) Unfortunately though Node 8 ignores the quotes, so treats the space in the app name there as a separate argument.

Assuming you are indeed using Node 8, there's a few options:

* Use Node 10+ (you can change the nvm default with `nvm alias default 10` - you might need to `nvm install 10` first). Any modern version will do, so if you have no other constraints I'd suggest using v14.
* Rename "HTTP Toolkit.app" to a name with no spaces in it.
* In the intercepted terminal, run `unset NODE_OPTIONS`, and it'll fall back to a PATH-based interception, which might still work for you, although that's not as reliable in some cases.

Give that a go, let me know if that helps at all.

**Comment by nicholaskajoh** [comment]
Thanks a lot @pimterry 🙏🏾
