### ISSUE TITLE
Support for username and password in proxies?

### ISSUE THREAD

**Issue by shirshak55** [httptoolkit/httptoolkit#155]
I tried to add username password in standard format but it doesn't accept it?

username:password@host:port

Or,

host:port:username:password

is it only my issue? Or httptoolkit has no support for username and password? I can add one if it doesn't

Thanks

**Comment by pimterry** [comment]
> httptoolkit has no support for username and password? I can add one if it doesn't

Hi @shirshak55, good spot, yes that isn't properly supported right now. If you want to take a look, it should be easy to add.

I think it is supported internally in Mockttp, because we use [proxy-agent](https://www.npmjs.com/package/proxy-agent) to do the actual proxying of traffic, and that module can use usernames & passwords straight from the URL. It's only missing at the UI configuration level ([UI here](https://github.com/httptoolkit/httptoolkit-ui/blob/master/src/components/settings/connection-settings-card.tsx), builds a URL [here](https://github.com/httptoolkit/httptoolkit-ui/blob/a1dcf83259a6d3f90b46023d9e5c1b4031ed4416/src/model/rules/rules-store.ts#L288-L291)). If you're interested in this feature and you want to take a look at fixing that, I'd very happily accept a PR! :smile:

**Comment by shirshak55** [comment]
sure i can do that.

**Comment by shirshak55** [comment]
Fixed by https://github.com/httptoolkit/httptoolkit-ui/pull/29 . I think I will close this to make issue tracker clean.
