### ISSUE TITLE
download free - pay to do a mocked fixed response. shady practice!! by a greedy company.

### ISSUE THREAD

**Issue by orenmizr** [httptoolkit/httptoolkit#164]
uninstalled this software!

**Comment by pimterry** [comment]
It's not a big greedy company, it's just me :smiley:. Sorry, but software costs money to build! Not everything can be 100% free. If HTTP Toolkit didn't make enough money to fund my work, then I would have to do something else to feed myself, and HTTP Toolkit wouldn't exist at all.

As for 'Greedy' & 'Shady' - most features really are free, the price is very reasonable for anybody who works professionally as a developer, the list of paid vs free features are well documented (on the home page, the pricing page, and in the app) and honestly it's not making me rich or doing anything close. 

HTTP Toolkit is by design a 100% open-source project that's _largely_ free, rather than being a strictly commercial product that's 100% paid. I've done that even though the commercial alternative would make me quite a bit more money (but with fewer users, creating less impact, and imo doing less valuable work).

That said:
* Although you can't set up an automated mock rule (replace all responses matching X with this response) you can manually mock any responses you like for free, using "Pause a response to edit it" rules. For most quick simple use cases this works just fine.
* HTTP Toolkit is _totally free_ for open-source contributors. If you're not happy with the paid model, I'd encourage you to help do the work to build HTTP Toolkit. For everybody who does, it's effectively a traditional open-source project where every feature is 100% free. See https://github.com/httptoolkit/httptoolkit#contributing-directly for more details.

Sorry to see you go, but if everything was free then HTTP Toolkit wouldn't exist. Hope that's some useful context anyway!

**Comment by orenmizr** [comment]
it is ok to ask for money! its your prerogative. don't say free free free on the site and then have someone realize he just installed something on a windows machine that simply does not deliver the basic mock behaviour.
