### ISSUE TITLE
adb never connects

### ISSUE THREAD

**Issue by DaviArcherBR** [httptoolkit/httptoolkit#173]
Unfortanely, connected Android devices that aren't rooted do many requests being hided or blocked. I was trying to connect my device with adb, but it's icon everytime appears as "Not available" and "CONNECTED SOURCES" tab never loads.

**Comment by pimterry** [comment]
Hi @DaviArcherBR, did you close this because you've got it working now? Happy to help if not.

"Not Available" normally means no devices are currently connected to adb. You can run `adb devices` to see the current state - if it appears connected there with no warnings, then the option should be available in HTTP Toolkit.
