### ISSUE TITLE
Something went wrong. Check your connection and try again. 

### ISSUE THREAD

**Issue by pogrametricwise** [httptoolkit/httptoolkit#181]
**Installed HTTP toolkit in windows**
1. I have android emulator AVD with Android 11
2. Installed Android Toolkit in android emulator
3. Enable certificate and connected successfully.
4. Now i am searching  in emulator browser and network logs are coming in View Section.
5. But after 2-3 seconds, **Error coming**  **Something went wrong. Check your connection and try again.** 

Please let me know, how can i resolve.

**Comment by pimterry** [comment]
Hi @pogrametricwise, where is this error shown? Is that inside a specific app, or inside the HTTP Toolkit Android app, or one your computer somewhere?

**Comment by pogrametricwise** [comment]
For all apps inside Android app emulator

**Comment by pimterry** [comment]
Inside HTTP Toolkit on your computer, do you see many blank rows like "Connection aborted" or "Certificate rejected"?

Assuming you're using an official OS, are you using a Google Play, Google APIs or Vanilla emulator OS build?

Does the HTTP Toolkit android app show system certificates as enabled?

System certificate interception is necessary for intercepting 3rd party apps, if you can't rebuild them with debug features enabled. System certificates can't be added on "Google Play" Android emulators since they don't allow root access, but they are enabled automatically on other emulator versions and on rooted devices. There's more details in [this emulator interception tutorial](https://httptoolkit.tech/blog/inspect-any-android-apps-http/) and in the [Android docs](https://httptoolkit.tech/docs/guides/android/).

If system interception is enabled then most apps should be intercepted successfully totally automatically. You may find one or two extra-secure apps (high-profile apps like Twitter/Facebook, and sensitive apps like banking) where certificate pinning is used, which requires some [additional manual steps](https://httptoolkit.tech/blog/frida-certificate-pinning/).

**Comment by pogrametricwise** [comment]
Inside HTTP Toolkit on your computer, do you see many blank rows like "Connection aborted" or "Certificate rejected"?
**Yes**

**Comment by pimterry** [comment]
Ok. What about the other questions?

**Comment by pimterry** [comment]
Closing this. I'm happy to investigate further, but I think the advice above should work. If not, please provide more details about the OS & configuration you're using.

**Comment by pogrametricwise** [comment]
hello

**Comment by pogrametricwise** [comment]
Inside HTTP Toolkit on your computer, do you see many blank rows like "Connection aborted" or "Certificate rejected"?,,
**yes**

Assuming you're using an official OS, are you using a Google Play, Google APIs or Vanilla emulator OS build?
**Yes using official tools**

Does the HTTP Toolkit android app show system certificates as enabled?
**How can i check?**

System certificate interception is necessary for intercepting 3rd party apps, if you can't rebuild them with debug features enabled. System certificates can't be added on "Google Play" Android emulators since they don't allow root access, but they are enabled automatically on other emulator versions and on rooted devices. There's more details in this emulator interception tutorial and in the Android docs.
**How can i check?**


If system interception is enabled then most apps should be intercepted successfully totally automatically. You may find one or two extra-secure apps (high-profile apps like Twitter/Facebook, and sensitive apps like banking) where certificate pinning is used, which requires some additional manual steps.

**Comment by pogrametricwise** [comment]
Error coming from emulator **SSL certificate is invalid whether to continue access**

**Comment by pogrametricwise** [comment]
1. Added network_security_config.xml inside xml dir

<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
  <base-config>
      <trust-anchors>
          <certificates src="system" />
          <certificates src="user" overridePins="true" />
      </trust-anchors>
  </base-config>
</network-security-config>


2. Added android:networkSecurityConfig="@xml/network_security_config" to the <application> element in application manifest.

**Comment by pimterry** [comment]
> > Assuming you're using an official OS, are you using a Google Play, Google APIs or Vanilla emulator OS build?

> Yes using official tools

I think you've misunderstood the question. Which one of those three options?

> > Does the HTTP Toolkit android app show system certificates as enabled?

> How can i check?

Look at the HTTP Toolkit android app, which is shown on the device. The difference looks like this:

![image](https://user-images.githubusercontent.com/1526883/135267699-6cfc1b21-0957-4a39-94d5-45be6cbf1991.png)

> Error coming from emulator SSL certificate is invalid whether to continue access

Can you share a screenshot of the error please?

Also, which app are you trying to intercept? Do you know if it uses certificate pinning?

**Comment by pogrametricwise** [comment]
![Screenshot (28)](https://user-images.githubusercontent.com/81216143/135277368-08e1c133-bbcc-47ef-b2d6-789b0081eb3b.png)

**Comment by pogrametricwise** [comment]
![Screenshot (30)](https://user-images.githubusercontent.com/81216143/135277846-42b9bb02-a398-4717-b36d-3a071c15ca1d.png)

**Comment by pogrametricwise** [comment]
Also, which app are you trying to intercept? Do you know if it uses certificate pinning?
>> I don't know about certificate pinning

**Comment by pogrametricwise** [comment]
I have checked about certificate pinning. I think I needs to use frida here. But I am facing issue in windows machine about adb

**Comment by pimterry** [comment]
The "System Trust Disabled" message in the HTTP Toolkit android app is almost certainly your problem.

You need to either use a rooted device, or use an appropriate rootable emulator.

You still haven't answered the question about which emulator you're currently using - I guess it's the Google Play version, because that one won't give you access, and you'll hit issues like this.

I think you just need to delete your emulator, and start again carefully following this guide: https://httptoolkit.tech/blog/inspect-any-android-apps-http/. If you do that then it will say "System Trust Enabled" in the HTTP Toolkit android app, and then intercepting 99% of apps everything will work automatically.

**Comment by pogrametricwise** [comment]
Ok 👌thank you for the quick response, I will try which you suggested and let you know.
