### ISSUE TITLE
Certificate rejected

### ISSUE THREAD

**Issue by 89z** [httptoolkit/httptoolkit#182]
I have been using this program successfully with different Android APKs, but for some reason the Instagram APK is not working. Every request made by the app is returning:

~~~
Certificate rejected for connection to i.instagram.com
Certificate rejected for connection to graph.instagram.com
~~~

**Comment by pimterry** [comment]
I can't really help with that I'm afraid. Maybe restart the app now that that's changed? If the built-in options for Instagram really aren't working, you're going to need to either get in contact with their security team for advice, or reverse engineer the app yourself and extend the Frida script in the article above to hook each of their relevant internal APIs to disable these checks.

Sorry I can't help more. Apps who implement advanced certificate pinning approaches like this are specifically defending against apps like HTTP Toolkit, and sadly the Facebook security team has more time & money than I do, so I'm not going to win this battle :smile:

**Comment by 89z** [comment]
Damn this app is a piece of shit. I finally got the whitehat menu by creating a Facebook test account [1], but when I log out and log back in, it now says my password is bad. I reset the password using the same page, but it continues to say password is invalid. Fuck this shit.

1. https://www.facebook.com/whitehat/accounts

**Comment by 89z** [comment]
I found some patches APKs:

https://github.com/itsMoji/Instagram_SSL_Pinning

but it seems only Burp Suite is listed - is it possible to use these with HTTP Toolkit?

**Comment by pimterry** [comment]
Yes, that should work fine! You should be able to use that directly and simply ignore any basic certificate & proxy setup steps, since HTTP Toolkit does that all for you automatically.

Do let me know if it works for you, it'd be useful to know so I can point other people there in future.

**Comment by 89z** [comment]
Doesnt seem to work :(

I might just try to get Burp Suite or MitmProxy working, although I dont want to learn a new tool unless I really need to.

**Comment by pimterry** [comment]
What device are you using, and what steps specifically are you following?

I've just tested this on my rooted physical test device (using the non-root APK from that repo) and I can see everything. I'm using non-root just because it's recommended, and it doesn't require messing around to inject manually patched files.

I do see lots of noise mind you - they seem to be running MQTT (a non-HTTP protocol) over port 443, which adds some garbage requests, and there's some Sentry errors from HTTP Toolkit due to weird ICMP packets. I'll look at that and fix those Sentry errors shortly, but you can just filter out all that noise with `not(hostname=sentry.io) not(errored)`. Given that, the interesting traffic on the initial app load looks like this:

![Screenshot from 2021-09-22 17-11-28](https://user-images.githubusercontent.com/1526883/134370819-89cd2011-6a04-4b3d-b842-b3ea52c553e2.png)

In general, Burp Suite, mitmproxy and HTTP Toolkit are all capable of intercepting the same traffic. We're all doing effectively the same things to proxy raw HTTPS traffic internally, and the differences are in the UX and especially the interception setup steps (for the others for Android you need to manually configure a cert & proxy, while HTTP Toolkit uses a VPN to do that for you). As far as I'm aware, there's no HTTP traffic you can capture with the other proxies but not HTTP Toolkit.

**Comment by 89z** [comment]
> What device are you using, and what steps specifically are you following?

I am using Android Studio [1], with this device:

~~~
Nougat, API Level 25, ABI x86, Android 7.1.1 (Google APIs)
~~~

Note that its an emulator, its not a real phone in my hand. If my choice above is wrong, other virtual devices are available. But I have used this device with other APK no problem. But this is my first time with the Certificate Pinning crap.

1. https://developer.android.com/studio

**Comment by pimterry** [comment]
Are you using the root or non-root APK? Which steps are you following exactly?

I've just tested the x86 non-root APK on an Android 7 x86_64 Google APIs emulator and it works fine for me. I did have issues when I forgot step 1.2 from [the instructions](https://github.com/itsMoji/Instagram_SSL_Pinning#non-root-method-recommended) though:

> 1.2. For x86 only, Open Instagram app (wait a few seconds) and close it.
> It's important to run Instagram app once, before setting the proxy!

Did you do that? I saw errors before, but after I force-closed the app, stopped HTTP Toolkit, started Instagram as normal, and then enabled HTTP Toolkit again, I can now see everything - no TLS errors.

**Comment by 89z** [comment]
> Did you do that? I saw errors before, but after I force-closed the app, stopped HTTP Toolkit, started Instagram as normal, and then enabled HTTP Toolkit again, I can now see everything - no TLS errors.

This flow that youre describing is not acceptable, as for my usecase Toolkit needs to be running BEFORE Instagram is started. I want to capture every single request coming from Instagram, and I cant do that if Instagram is started before Toolkit, as in your instruction.

**Comment by pimterry** [comment]
You can still stop and restart Instagram, it's just that apparently it needs to be run successfully once, before you enable the proxy. That's only if you're intercepting on x86, according to the docs. ARM seems to work fine immediately, if you have a physical rooted device available.

Honestly though - this is all something you should take up with the person patching Instagram, that requirement is part of their setup, it's nothing to do with HTTP Toolkit.

**Comment by 89z** [comment]
Sorry I wasnt clear, I am talking about this:

> started Instagram as normal, and then enabled HTTP Toolkit again, I can now see everything - no TLS errors.

I understand that you need to start, close and start Instagram. Thats fine. But from your instruction, it seems that on the SECOND TIME you start Instagram, youre doing so BEFORE starting Toolkit. Thats the part thats not acceptable. Im fine with having the start/stop/start, if on the final start, it works. I am not fine with, on the final Instagram start, I am potentially missing requests.

**Comment by pimterry** [comment]
Ok - that's nothing to do with HTTP Toolkit though. The cause of this is how this other person has modified the Instagram app, which doesn't work if there's any proxies enabled on first run. I'm afraid I don't know anything about that or why that's required, and there's nothing I can do about it.

I'm going to lock this here, since I think the HTTP Toolkit side is working fine and I'm not sure more discussion here is constructive. HTTP Toolkit can definitely intercept this traffic if you can find a way to unpin Instagram version that works with your workflow.

I've tested on an ARM device and that already works exactly as you want. If you can only work with x86, I think it's probably possible there too, but you need to test it thoroughly yourself and see if the results in practice work for you. If that doesn't work, you should talk to https://github.com/itsMoji/Instagram_SSL_Pinning about avoiding the restart step that they require.
