### ISSUE TITLE
Support Transparant Proxy

### ISSUE THREAD

**Issue by shirshak55** [httptoolkit/httptoolkit#184]
I don't know if http toolkit supports transparent proxy but searching duck duck go doesn't show anything that tells HTTP toolkit support transparent proxy.

I think other tools like mitmproxy , charles already support them .

**Comment by pimterry** [comment]
Hi @shirshak55. HTTP Toolkit supports transparent proxying, totally automatically. That's enabled by default, and used automatically any time it's required. Some more details on how this works here: https://httptoolkit.tech/blog/http-https-same-port/.

I'm going to close this for now, since it's already implemented. I'm open to PRs if you think there's any way that this could be better documented or otherwise improved though.

**Comment by shirshak55** [comment]
I see thanks. Sorry, I guess its my iptable settings that are messing things.

**Comment by pimterry** [comment]
Ah, ok, do you have a specific issue with some traffic you're trying to intercept? What's happening exactly?

For transparent proxying, the only requirement is that HTTP Toolkit receives the request with a Host header that points to the real target server. Every spec-compliant HTTP client must send that (or HTTP/2's equivalent :authority header) with every request, so that's normally pretty easy & reliable.

**Comment by AJolly** [comment]
1) I wish this was documented better, I only found out about the super cool same port feature when I came to ask for transparent proxy support.

2) Not everything will send a host header / it may be easier to capture traffic if we have the option to force where to send traffic to.
(Charles proxy has this with its reverse proxies setting, burp suite has the same redirection option)

**Comment by pimterry** [comment]
> Not everything will send a host header 

Anything that doesn't include a Host header isn't sending a valid HTTP request - it's been a strict requirement for all requests since HTTP/1.1 (published in 1999). Are you running into a real-world issue where this isn't available? I've never seen one, but I'm happy to investigate if you have an example.

> may be easier to capture traffic if we have the option to force where to send traffic to

This is possible already. You can create a "Forward the request to a different host" option in the mock rules to forward traffic anywhere you like, or you can create a breakpoint rule for requests & manually edit the URLs to forward each request manually too.

**Comment by AJolly** [comment]
The forward request to a different host option is extremely useful.

I think the difference is with HTTPProxy its being done on a global basis, with burp/charles I can easily apply it to a specific subset of traffic (since its only applying to traffic coming in on a localhost)

I'll investigate the host header aspect.

**Comment by pimterry** [comment]
> I think the difference is with HTTPProxy its being done on a global basis, with burp/charles I can easily apply it to a specific subset of traffic (since its only applying to traffic coming in on a localhost)

I'm not exactly sure what you mean here. Can you give me an example? Forwarding rules are necessarily global in HTTP Toolkit - you can absolutely add matchers to target specific traffic if you'd like.

**Comment by AJolly** [comment]
Charles etc make it easier to configure and manage.
The real issue seems to be that only one rule gets applied to traffic, rather than the rules being applied in order:

Ex: 
![image](https://user-images.githubusercontent.com/91493/140011915-d40a15ca-9f43-4857-9493-cf985081d536.png)

This rule set will let me rewrite the request, but will end up in a passthrough loop. 
If I swap the order of the rules around, it'll get forwarded fine, but never hit the manual rewrite rule.

**Comment by pimterry** [comment]
When you modify the POST request with those rules, what's the initial URL, and what do you modify the URL to become?

If you're seeing a looping issue, then I suspect it's because you're modifying the request in the first rule, and it's then being sent back to the proxy again, and matching the same rule again. Any time that happens, it's considered a loop and the request gets dropped to avoid infinite proxying issues.

If you edit the rule so that the first rule doesn't match, then when it comes round again to the proxy it will run the 2nd rule instead. How to do that for your case depends on what you're doing though.

Can you share some specific examples of the requests you're seeing and what you want to happen?
