### ISSUE TITLE
How to export crt certificate http toolkit using?

### ISSUE THREAD

**Issue by vikasg603** [httptoolkit/httptoolkit#191]
Hey team, I have a doubt, how can I export the CRT certificate which HTTP toolkit is using?
For 1 of my experiment based on a particular application, The current Frida solution for the SSL pinning is not working.

Now i am trying to do this using this script https://codeshare.frida.re/@pcipolloni/universal-android-ssl-pinning-bypass-with-frida/

But i am not able to find out a way to export the crt certificate.

**Comment by pimterry** [comment]
If you click the 'Anything' option in HTTP Toolkit, it will show you the path for your CA certificate (e.g. `C:\Users\USERNAME\AppData\Local\httptoolkit\Config\ca.pem` on Windows).

Alternatively, you can get the same content by visiting amiusing.httptoolkit.tech/certificate in an intercepted HTTP client.

That will give you the certificate in PEM format. I think .crt files are generally in DER format. You'll need to convert between the two, which is a manual process, but there's 1000s of guides and tools available to do that online.

All of that said: I don't think you need to do this. If you're using HTTP Toolkit for Android interception (or any other tool that adds the CA certificate to the system store) then it should be better to use the Frida script & instructions from https://httptoolkit.tech/blog/frida-certificate-pinning/, which covers lots more cases than the script you've listed above (as far as I can tell from reading it - if you do find a case where that script works but this script doesn't, please let me know so I can expand it!).

**Comment by pimterry** [comment]
I'm going to close this issue, since the original problem (exporting crt certificates) is now resolved - there's now a button to manually export the certificate in the 'Anything' intercept option.

There was a tangent we followed here, where the underlying issue was that bodies which cannot be decoded at all (due to invalid data and/or content-encoding header) are not accessible at all. I've tracked that separately in https://github.com/httptoolkit/httptoolkit/issues/230.
