### ISSUE TITLE
api.amplitude.com/identify

### ISSUE THREAD

**Issue by 89z** [httptoolkit/httptoolkit#192]
I tried to intercept the traffic from this:

https://apkpure.com/the-nbc-app-stream-live-tv-and-episodes-for-free/com.nbcuni.nbc

But when I start the app, I just get hundreds of requests like this:

~~~
METHOD: POST
URL
https://api.amplitude.com/identify
~~~

all with response 400 Bad Request. Am I doing something wrong?

**Comment by 89z** [comment]
If I start the app without HTTP Toolkit, it has a short (one second) initial load before you see the home screen. I assume during this time, its making a single (successful) request matching what I put in the original post.

If I start the app with HTTP Toolkit running, it loads forever, looping on that same request, never getting to the home screen.

**Comment by pimterry** [comment]
Yeah, I mean that is suspicious! A 400 response implies something inside the request content is invalid though, and HTTP Toolkit generally doesn't modify the request content at all, unless you've added a rule to do so. I'm not aware of anything HTTP Toolkit would do that could cause this.

Is there anything in the body of the response that explains why the request was rejected?

What happens if you add a mock rule, and replace the 400 response with a 200?

**Comment by 89z** [comment]
I have some more time to work on this now

**Comment by 89z** [comment]
After trying many other options, I finally gave in and tried Frida [1]. And what do you know, it actually worked! Its only only tool that where I can see the APK traffic. Plus, I didnt even have to install a system certificate! You are a beast man, thanks for the good work!

1. https://httptoolkit.tech/blog/frida-certificate-pinning
