### ISSUE TITLE
Burning desire for these suggestions

### ISSUE THREAD

**Issue by jayesh83** [httptoolkit/httptoolkit#196]
1. As under matcher we've URL matching with regex, Query parameters also should have regex accepting option.
2. Naming rule -> by default name of rule comes but we should be able to add our own name of particular rule
---
_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
> Query parameters also should have regex accepting option.

Can you give me some examples of the kind of query parameter regexes you'd like to use?

I've been thinking about adding key-value matching for query strings, which would be more flexible. Similar to how the header matching works now, like:

```
Match
GET requests
Including query values:
  id   abc
  page 4
```

Would that work for you, or do you need the full power of regex?

It'd prefer to limit the complexity here if possible because it quickly gets confusing, especially since many query strings contain characters that have special meanings in regex (`?[].` for example) so lots of awkward escaping would be necessary.

> we should be able to add our own name of particular rule

Right now you can't do this, but you can create groups of rules (drag one rule onto another), and you can give those rule groups special names. Does that help you?

If not, can you explain a little more about what names you want to use and why?

**Comment by jayesh83** [comment]
1. query: ?post_id=24&page=1&per_page=20
regex query: ?post_id=[0-9]+&page=[0-9]+&per_page=[0-9]+

maybe something like, adding it like key-value pair would be overwhelming as some apis have many queries but yeah both works i guess.

2. yeah having name of individual rule can be very helpful to easily enable/disable different versions of same api. that is one use case but having individual name is something very powerful

**Comment by pimterry** [comment]
I'm going to close this issue to clean things up. These two requests here are tracked separately in:

* #231 (but note that flexible per-parameter matching is now supported since this issue was filed!)
* #102
