### ISSUE TITLE
Some apps fail without proxy

### ISSUE THREAD

**Issue by 89z** [httptoolkit/httptoolkit#201]
I apologize if this is off topic, but it seems close enough that may be worth posting. I have noticed recently, newer versions of some apps wont run on a Virtual Device, even with proxy disabled. Example app:

~~~
com.soundcloud.android
~~~

If you start the app and try to sign in, you get a message saying "signing in" that pops up over and over again, until you kill the app. If you try an older version of the app, it works as expected. Another app having problems:

~~~
com.zhiliaoapp.musically
~~~

I could only get this one to install with Android 9 or higher, but even though it installs, it just crashes on start. Again this is with proxy disabled. I havent tried an older version of the second app, but I suspect similar result. Again sorry if this is off topic, but I think HTTP Toolkit is used by many people to monitor APK, so maybe it is of some interest, if someone happens to have a suggestion or workaround.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
So this happens even without any use of HTTP Toolkit, right?

In that case, I suspect this is due to [SafetyNet](https://developer.android.com/training/safetynet/attestation). This is a built-in Google API that verifies whether the device is a standard production OEM device, or something else (custom ROM, rooted device, emulator, whatever).

Some apps will check this and refuse to run if it fails (especially those who have copyright restrictions that legally require them to enforce DRM). You can interactively check the SafetyNet result on any device with apps like https://play.google.com/store/apps/details?id=com.flinkapps.safteynet (or one of the hundreds of others).

It's used to be easy to set up a rooted device that still passes SafetyNet on custom ROMs designed to do so, but I think that's got more difficult with hardware-backed attestation recently on modern devices, and I think standard non-Google Play emulators will generally never pass this. There are workarounds for modern devices though seemingly, although I've never tried them myself: https://www.thecustomdroid.com/fix-safetynet-hardware-attestation-guide/

As an alternative you can of course always patch the APK (directly or with Frida) to remove the check entirely.

**Comment by 89z** [comment]
FYI I tried both of these again, this time using Frida. I made sure to update `frida-server` and Frida script [1] before testing. The SoundCloud app seems to have same problem even with Frida. With TikTok, I did notice this Frida error:

~~~
Process crashed: Trace/BPT trap

***
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86_arm/generic_x86_arm:9/PSR1.180720.122/6736742:userdebug/dev-keys'
Revision: '0'
ABI: 'x86'
pid: 5266, tid: 5321, name: tp-io-13  >>> com.zhiliaoapp.musically <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'vendor/unbundled_google/libs/ndk_translation/runtime/host_call_frame.cc:65: CHECK failed: 3331640760 == 3331641312'
    eax 00000000  ebx 00001492  ecx 000014c9  edx 00000006
    edi 00001492  esi c6c59f4c
    ebp c6c59f18  esp c6c59ea8  eip ef330b39

backtrace:
    #00 pc 00000b39  [vdso:ef330000] (__kernel_vsyscall+9)
    #01 pc 0001fdf8  /system/lib/libc.so (offset 0x1f000) (syscall+40)
    #02 pc 00022ed3  /system/lib/libc.so (offset 0x22000) (abort+115)
    #03 pc 0000040e  <anonymous:eb4c7000>
***
[Android Emulator 5554::com.zhiliaoapp.musically]->
~~~

1. https://github.com/httptoolkit/frida-android-unpinning

**Comment by pimterry** [comment]
Not sure what's going on in that trace, but it's some kind of native code error, which is pretty unusual. Could be unrelated, since I'd expect SafetyNet failures to happen much more gracefully than that.

Either way the existing Frida script won't help here - it doesn't try to disable any of these kinds of checks. I mentioned Frida in that it is probably _possible_ to disable these checks with Frida, but you'd need to write your own new script to do so from scratch. The current script only thinks about certificate pinning, not SafetyNet.

From a more detailed look at the SafetyNet attestation docs, it seems the server will often do validation of attestations too, in which case this will be much much more difficult even with Frida. It depends whether people are actually doing that advanced step though. If you want to look into this, you'll need to do a bunch of research into the APIs and reverse engineering into the apps to do so. It's probably easier to look into the [magisk route](https://www.thecustomdroid.com/fix-safetynet-hardware-attestation-guide/) to get a physical rooted device that passes SafetyNet.

**Comment by 89z** [comment]
https://github.com/httptoolkit/frida-android-unpinning/issues/13

**Comment by 89z** [comment]
OK I finally figured the issue for this one:

~~~
com.soundcloud.android
~~~

I am using a APK downloader that I built myself. By default it downloads a split APK, which is the main file and some smaller config files, instead of one big APK, in order to save space. My program was assuming that the config would always be two or more files. So in cases where you just had on main file, and one config file (like the current SoundCloud), it would only download the main file. I have since fixed the problem.
