### ISSUE TITLE
feature request: save mock requests to disk when closing and reopening httptoolkit

### ISSUE THREAD

**Issue by nutterthanos** [httptoolkit/httptoolkit#209]
_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
If you mean mock rules, then that is already available as a Pro feature. For Pro users, all configured rules persist indefinitely.

For intercepted requests, that's not available at the moment, it's an interesting idea! I'm pretty cautious about doing that though, because it can be quite a lot of data, and I think most of the time it's not what you want. It is possible to do this manually by exporting & importing traffic instead, although that's a little fiddly. If that's what you're looking for, is there a specific reason you want that?

**Comment by nutterthanos** [comment]
ah nvm it was mock rules and since its already a pro feature yeah well i guess i can close this
