### ISSUE TITLE
trying to open https://app.httptoolkit.tech, not opening its stuck

### ISSUE THREAD

**Issue by sushantoghosh** [httptoolkit/httptoolkit#233]
---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).
<img width="260" alt="Screenshot 2022-01-29 at 11 48 00 AM" src="https://user-images.githubusercontent.com/20637464/151650073-bb1982d9-5e56-4c65-8480-971d62f7957f.png">
<img width="1540" alt="Screenshot 2022-01-29 at 11 48 12 AM" src="https://user-images.githubusercontent.com/20637464/151650076-1ea90103-aba6-480d-bc9a-4f17dec83dd9.png">
_

**Comment by pimterry** [comment]
Hi @sushantoghosh - the issue here is in the first screenshot you've shared. The internal port that HTTP Toolkit uses (45457) is already in use.

The HTTP Toolkit app is actually two components: a UI and a server. The server is failing to start and showing an error (because the port is in use) and the UI is stuck on this loading screen because it then can't connect to the server.

To fix this, you'll need to work out what is currently using port 45457 and shut that down. You can use `lsof -i tcp:45457` to see which process on your Mac is using this port. One thing that could cause this is old leftover HTTP Toolkit processes, if HTTP Toolkit failed to shut down correctly last time, so I would check for that first (these might appear as HTTP Toolkit or as Node.js processes on your machine).
