### ISSUE TITLE
Request body cant be decoded. Only hex and text options 

### ISSUE THREAD

**Issue by martindunford** [httptoolkit/httptoolkit#235]
![image](https://user-images.githubusercontent.com/51754034/151822850-a7e036eb-875d-4677-810d-f1e3ac578f3e.png)

Should be able to decode this to 
'p_details={"rollup":"N","extra_info":"NONE","teamArea":"1103","period":"202205","periodStartDate":"31 Jan 22","rollingPeriod":false,"teamAreaDesc":"ACME Cork","titletext":"31ST January   2022 - 6TH February  2022"}'

There appear to be only 'text' and 'hex' options from the dropdown menu. Both of which result in difficult to 
read/compare data. Should be decoded further 
e.g Python can do it with urllib.parse.unquote('....') 

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @martindunford, thanks for reporting this. What's the `content-type` parameter? I imagine it's something like `application/x-www-form-urlencoded`? If so, I think this is covered by #175 - it looks like the body here is encoded form data.

It might be good to try to detect this format too, where possible, in the same way we do for JSON (string starting with `{` or `[` that seem to be JSON can be parsed as JSON even if the content-type is wrong).

The problem here and in #175 though is how to show this. We could format the data as JSON instead, but that might be confusing - it will look like the body really is JSON but it's not.

We can't just decode the characters directly but leave it on one line, because it's ambiguous when you have encoded = and & characters (among others) inside the string. For example, if you receive the body `a=c&b=c%26c%3Dd`, and you just decode character by character you get `a=c&b=c&c=d`, which doesn't really represent the original value.

Any ideas for how this should be represented?

**Comment by pimterry** [comment]
I think this is covered by #175, so I'm going to close it for now, but feel free to reply here if you think that's incorrect.
