### ISSUE TITLE
Add custom headers to all requests on a global basis?

### ISSUE THREAD

**Issue by briantully** [httptoolkit/httptoolkit#239]
Hi there. First off thank you for developing such a wonderful tool! I just purchased the Pro license and have been very impressed with HTTP Toolkit. One feature I haven't been able to figure out is being able to add custom headers for all requests that are being intercepted. For example, I may want to add Akamai debug headers, or Cloudflare debug headers. so that I can see cache related headers in the intercepted responses. Or in another case I may not be able to access a site without a custom header. Typically I can get around this in my global browser with browser extensions. However with the "fresh independent browser window" it opens a clean profile that does not have the required browser extensions. I understand that I can choose "Global Chrome", but that is also intercepting any other Chrome extension traffic, which is not ideal.

I was hoping that under the "Mock & Rewrite Rules" section I would be able to add a custom header to all requests, but that does not appear to be an option at this time. There's an option to pause request and manually edit, but that's not ideal.

Are there any plans on allowing automatic modification of all all requests for such things as adding custom headers?

Thanks again! :)

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @briantully. Yes, this is supported, using transformation rules, like so:

![Screenshot from 2022-02-04 10-55-14](https://user-images.githubusercontent.com/1526883/152508973-7db2b0a6-5761-4968-a20a-a828c0253416.png)

This rule matches all requests, and adds an extra header before forwarding them upstream.

Be aware that matching _all_ traffic like this has some side-effects, because it means the subsequent rules (in the Default Rules block) will never run, so the `amiusing.httptoolkit.tech` page won't be injected, and setup for Android devices (which adds a rule to the default block) won't work.

You can fix that by either matching just the specific traffic you care about (e.g. match just one hostname) or by moving this rule to the second last position of the default block (just above the 'Any other requests' rule) so that it doesn't override anything but the final proxying behaviour.

Does that make sense, and work for you?

**Comment by briantully** [comment]
That’s perfect! Thank you so much. I’m not sure why I didn’t see that before. Thanks again for all you do 😀

**Comment by pimterry** [comment]
Excellent! I'll close this now, great to hear everything's working well for you :smiley:
