### ISSUE TITLE
unsupported HTTP method

### ISSUE THREAD

**Issue by gagagadev** [httptoolkit/httptoolkit#244]
Hi,

The httptoolkit is a great tool and really easy to use. Thank you!

Unfortunately, I run into an issue when I try to intercept a TCP connection from an android app, which is communicating to a server on port 20541. In httptoolkit it says: "This request could not be handled [...] unsupported HTTP method [...]". In the request box the Method is shown as "0gBue" and the URL field is empty.

Does httptoolkit "only" support HTTP POST and GET method or also socket connections? (I'm a noob, so please excuse me if this question does not make any sense.)

The reason I'm asking: The android app "Packet Capture" by "Grey Shirts" (also using VPN) is able to handle and log this connection - but it does not have the nice features of httptoolkit.

Thanks for your feedback and best regards.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @gagagadev. A message like that means that the 'request' is not an HTTP request, it's some other TCP-based procotol.

HTTP Toolkit supports HTTP (HTTP/1.1, HTTP/2, and HTTPS versions of both), and supports WebSockets (over any HTTP protocol) although websockets aren't debuggable in the UI yet. This is something that isn't one of those, so you'll need some kind of byte-by-byte raw traffic inspector instead.

There's a bit of a split within tools here: raw traffic analysis lets you view many more different types of protocols, but it's almost impossible to build a friendly tool like HTTP Toolkit on top of that to understand all those specific protocols and even rewrite them in a nice way, unfortunately. Most tools go either one way, or the other.

By the way, it's not directly usable on mobile, but you might be interested in looking at https://www.wireshark.org/. It can be a bit complicated, but it's the gold-standard tool for raw network traffic inspection on desktop, so if you can redirect the traffic via your desktop somehow (e.g. by using HTTP Toolkit at the same time) then that will give you some very powerful tools on your computer to explore the raw data.

I'm going to close this for now, since parsing arbitrary raw data isn't something that HTTP Toolkit is going to do, but I hope the above can help you out anyway :smile:
