### ISSUE TITLE
System Trust is Disabled even after rooting in oneplus 3

### ISSUE THREAD

**Issue by kaustav07** [httptoolkit/httptoolkit#253]
---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by shirshak55** [comment]
This will probably be fixed shortly.

**Comment by pimterry** [comment]
This is very old now, closing. I think (see some discussion in https://github.com/httptoolkit/httptoolkit-server/pull/37) that this is fixed in new Magisk releases, so it should now be working correctly. I'm not currently aware of any remaining cases where this can happen.

If you're still facing this, or if anybody else finds this issue and has similar problems, please do file a new issue with details!
