### ISSUE TITLE
Can not open some site on cloudflare.

### ISSUE THREAD

**Issue by NabiKAZ** [httptoolkit/httptoolkit#256]
Why I can not open this site: https://pegaxy.io/ in any of browsers that opened by httptoolkit? return 403 code.
I know about this site is on cloudflare, Alright, I have a question that may be related to this issue here: https://stackoverflow.com/q/71529199/1407491

**Comment by shirshak55** [comment]
In short fingerprinting.

**Comment by shirshak55** [comment]
I just checked my fingerprints and it is different.

Real Browser https://browserleaks.com/ssl

![image](https://user-images.githubusercontent.com/8097377/159107909-92d5ce24-f038-44a4-95a8-b2c242f91fc0.png)


HttpToolKit https://browserleaks.com/ssl

![image](https://user-images.githubusercontent.com/8097377/159107921-fd00f8b4-8cb3-4920-a790-728f32ba38c5.png)

**Comment by NabiKAZ** [comment]
@shirshak55 Thanks, Do you thinks can add this fingerprint into CURL request in CMD or are there technical limitations in this regard?
In what layer is this fingerprint added? For example, is it inside the `pem` file?
Is just adding this fingerprint enough? Or does it depend on data transmission methods and protocols?

**Comment by shirshak55** [comment]
@NabiKAZ No, You can't. You have to compile and do these things manually. Maybe I will fix the fingerprinting issue in HTTP toolkit, so it will make your experience better.

**Comment by pimterry** [comment]
The TLS fingerprint is defined by how Node.js (used inside HTTP Toolkit) sets up its TLS connections.

There are a couple of configuration options we can use to modify this, but not very many. There's an issue tracking this in node with more info here: https://github.com/nodejs/node/issues/41112

It is possible that there might be some change we could make with the configuration options available that would fix this, but it's not very likely, because we definitely can't _exactly_ match a real browser right now (becuase we can't set the extension order). If anybody wants to test this out though (by making requests with node's built in https module, and changing options until the request stops being blocked) then be my guest, any working configurations would be very interesting.

We do already shuffle the cipher order (here: https://github.com/httptoolkit/mockttp/blob/main/src/rules/passthrough-handling.ts) which helps a bit: it makes us hard to recognize as being normal Node.js traffic, so that instead HTTP Toolkit looks like an unusual unrecognised client instead. That defeats blacklists of disallowed fingerprints, which are common, but any extra tight configurations that only allow a strict list of very common fingerprints will still reject us, and that's what's happening here.

For now, I think there's probably not much we can do here until Node offers more configuration options that allow us to fully emulate the TLS fingerprint of a common client, like Chrome.

**Comment by shirshak55** [comment]
@pimterry the othersolution is to use https://github.com/klzgrad/naiveproxy?

**Comment by pimterry** [comment]
Yes, that looks promising! If you configure that as an upstream proxy for HTTP Toolkit then it may be able to correctly emulate Chrome's TLS fingerprint, which would do it.

It's a bit tricky and you'll need HTTP Toolkit Pro (for the advanced proxy configuration settings) but it should work in theory.

**Comment by NabiKAZ** [comment]
This project might be useful:
https://github.com/lwthiker/curl-impersonate

**Comment by pimterry** [comment]
That is interesting, and they're solving the same problem, but they're doing so by swapping out OpenSSL entirely for BoringSSL (for Chrome) and nss (for Firefox). It looks like they've done that for Curl by directly patching the curl internal TLS code and some parts of those libraries too to make that work.

To do the same for HTTP Toolkit we'd need to patch Node.js's TLS internals to support those libraries, which is a) very difficult and b) something we'd need to constantly maintain each time we update Node.js versions.

If somebody wants to put together a patch to make this work, that would be interesting (if there's a nice way to do it that doesn't make updating Node versions too difficult) but it's a big project and it's very unlikely that I'm doing to do that myself any time soon.

In the meantime, proxying through something else (like naiveproxy, or anything similar) that can replace the TLS handshake is the best option imo.

Long-term, the 'real' solution to do this properly is to add proper support for this inside Node.js, but that's not easy either, and it doesn't look like it will be happening any time soon.

**Comment by pimterry** [comment]
I've just pushed an update with a few big improvements here @NabiKAZ. HTTP Toolkit will update in the background next time you run it, within a couple of minutes, and then the subsequent time this should work much better. This isn't a perfect fix, but in my testing it now avoids most blocks automatically.

Can you update, and then test out your use case again?

**Comment by pimterry** [comment]
I'm going to assume this is working, and close this as fixed for now, since we made a lot of improvements here last week.

In any rare cases where you're still seeing issues, I would suggest trying Firefox, which works even more reliably (because we can accurately match Firefox's JA3 fingerprint). Some blocks also appear to be more likely to allow requests if they're sent via HTTP/2, which you can configure in the Pro settings. Presumably not very many bots are using HTTP/2 yet :smile:.

None of this is an exact science - bot behaviour will change, Cloudflare etc will change their blocking logic in turn, and there's no 100% perfect solution, but right now I find that Firefox and/or Chrome+HTTP/2 works 100% of the time for me. I'll keep working on this as I find new issues in future, so do report more issues if you find them.
