### ISSUE TITLE
HTTP Toolkit HAR Exports Do Not Include URL Encoded Post Payloads

### ISSUE THREAD

**Issue by H0r53** [httptoolkit/httptoolkit#266]
I've been exporting HTTP Toolkit sessions as HAR files that I can later either load in a browser or in HTTP Toolkit itself. I generally prefer viewing HAR files in a browser. I've noticed that HAR files produced by HTTP Toolkit exports do not include form data of `content-type: application/x-www-form-urlencoded` from HTTP POST requests.

In other words, if I load a HTTP Toolkit HAR export into a browser such as Chrome or Firefox, I cannot see the POST data if the content-type is `application/x-www-form-urlencoded`. Other content-types seem to work fine. If I load the HAR back into HTTP Toolkit I'm able to see the POST data. There may be other factors at play, but the only consistent thing I've seen so far is this particular content-type being omitted when viewing HTTP Toolkit HAR exports in browsers.

**Comment by pimterry** [comment]
> if I load a HTTP Toolkit HAR export into a browser such as Chrome or Firefox, I cannot see the POST data if the content-type is application/x-www-form-urlencoded

Thanks for reporting this, this is interesting. The data is actually exported, but it seems that Chrome at least doesn't follow the HAR spec in how they import & export data for this use case.

The logic we use right now is here: https://github.com/httptoolkit/httptoolkit-ui/blob/c40782b2601a79f99ab3e0d482f5e1967e6cd454/src/model/http/har.ts#L173-L205

The corresponding part of the spec for that part of the export is here: http://www.softwareishard.com/blog/har-12-spec/#postData. The relevant snippet is:

```
Note that text and params fields are mutually exclusive.
```

I.e. you should export `params` containing the parsed structured param data, if possible/wanted, or you should export the `text` field with the data as a raw string if not.

HTTP Toolkit currently follows that approach, but it looks like Chrome exports both text & params every time instead, and ignores any `params` data on import.

Imo this is really a Chrome bug: Chrome should definitely use the `params` data on import if it's available, and when exporting it should probably pick one format or the other, not both. I've filed a bug there: https://bugs.chromium.org/p/chromium/issues/detail?id=1312895. I doubt they'll be in much hurry to change this though, and at the end of the day it's not especially unreasonable behaviour. Fundamentally this is an awkward design in the HAR format itself, but that's the only shared format for HTTP data we have.

In the meantime, I'm not sure what the best solution is here, because exporting params is actually very useful in some cases, e.g. code generation libraries that use HARs uses this to easily generate structured code for POSTs like `request.post({ 'a': 'b', 'b': 'c' })` instead of `request.post('a=b&b=c')`.

The most practical fix for now is probably to just export both, as Chrome does... It's explicitly forbidden by the spec, but Chrome's format is probably more influential in practice than the official spec anyway! I'll make the change to do that now.

> I generally prefer viewing HAR files in a browser.

Just out of curiosity, why? Is there something specific missing in HTTP Toolkit that would better support this use case for you?

**Comment by pimterry** [comment]
> The most practical fix for now is probably to just export both, as Chrome does... It's explicitly forbidden by the spec, but Chrome's format is probably more influential in practice than the official spec anyway! I'll make the change to do that now.

Now fixed & deployed. New exports will now include `text` as well as `params` in all POST data, so that data will be visible in Chrome as expected. Importing works with any combination of the fields, with `text` taking priority if both are present.
