### ISSUE TITLE
Multiple Instances / Tabs?

### ISSUE THREAD

**Issue by shirshak55** [httptoolkit/httptoolkit#267]
I generally debug mobile apps as well as web apps. However, I feel request, etc generally gets merged in the same UI so it gets difficult. It would be nice if we can have separate tabs according to port? It also means an increase in complexity. I don't think competitor tools like Charles Proxy support it. I am fine with the ability to run multiple instances if tabbed UI is difficult.

**Comment by pimterry** [comment]
This should work already @shirshak55. If you run HTTP Toolkit multiple times, it will open multiple windows, and each one will have its own proxy port. You can start interception separately in each to see traffic separately. This is one of the big benefits of configuring proxy ports per-target rather than setting a single system proxy value that's shared by everything as in Charles etc :smiley:.

It's not always possible to intercept the same type of interception target in multiple windows (you clearly can't intercept one Android device in two windows at the same time, for example, and I think launching the same browser from two windows at the same time doesn't work correctly sometimes either) but you should be able to launch Android from one and Chrome from another to see web & mobile traffic separately. Does that work for you?

**Comment by shirshak55** [comment]
@pimterry I think in ubuntu it doesn't work that way. When I run the HTTP toolkit it just opens one window.

**Comment by pimterry** [comment]
How do you launch HTTP Toolkit? Are you using Gnome or something else? https://unix.stackexchange.com/questions/451109/open-multiple-instances-of-a-given-application suggests you might need to press 'Ctrl+Enter' to launch an app twice, or right click and select 'Open a new window'. Does that work?

It doesn't need to be from the command line, most window managers should have a way to launch an application that's already running.

Might be good to add a menu item in the app though, to make this more obvious/easy. The current logic is [here](https://github.com/httptoolkit/httptoolkit-desktop/blob/24ef4a6d6bd41180983b0b08b1ed021c5c5cf330/src/index.ts#L511-L515), it's not very complicated. If you have a minute, do you want to open a quick PR to add a 'New window' option to the desktop app File menu for this? Or maybe we should call it 'New session'?

**Comment by shirshak55** [comment]
@pimterry I see what I can do is launch from the taskbar. But, it won't work from "Show Application". Maybe, it is an electron issue. So, I think I will close this issue, as there is a workaround (taskbar)
