### ISSUE TITLE
Any plans to support JDBC/JMS?

### ISSUE THREAD

**Issue by recursivecodes** [httptoolkit/httptoolkit#273]
Would be extremely handy to be able to inspect JDBC traffic. No idea if it's possible/feasible, but just thought I'd throw it out there.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
I'm not too familiar with the low-level protocols, but I assume they're unrelated to HTTP or anything similar? Given that this is probably out of scope I think, since that means both interception and parsing etc are unrelated to the current implementation, and lots of the UI features wouldn't fit neatly either. It'd be a good idea for a tool of your own though!
