### ISSUE TITLE
ui crashed

### ISSUE THREAD

**Issue by migers7** [httptoolkit/httptoolkit#276]
httptoolkit server shutdown error code 3221225785

**Comment by pimterry** [comment]
Hi @migers7, see https://github.com/httptoolkit/httptoolkit/issues/243 - this error means that your version of Windows is no longer supported I'm afraid.

On Windows, HTTP Toolkit only supports version 8.1 or newer. Older versions of Windows are no longer supported even by Microsoft, and have not been for many years. This is because some components we use internally (notably Node.js) no longer support Windows 7, so there's no longer any way to support it ourselves. You'll need to update to at least Windows 8.1.
