### ISSUE TITLE
Not intercepting node requests using new terminal or exisitng powershell

### ISSUE THREAD

**Issue by delebash** [httptoolkit/httptoolkit#282]
Windows 11
node 18.0.0
Power shell v7.2.4 installed from msi package

Steps to reproduce:

npm init
npm install node-fetch
add index.js file
Paste into index.js

import fetch from 'node-fetch';
```

(async () => {
    const response = await fetch('https://github.com/');
    const body = await response.text();

    console.log(body);
})()
```

Run Invoke-Expression (Invoke-WebRequest http://localhost:8001/ps-setup).Content in terminal

Response is HTTP Toolkit interception enabled

type node . to run your index.js file and run a fetch request
Request completes but nothing is intercepted when you click on view in Http Toolkit

Existing terminal is showing as activated but not connected

I also tried this with a fresh terminal with the same results

Note:
If I run your example commands in the same terminal session the interception works.  It just does not seem to work running node . or node index.js and I am using node-fetch.

```
node
> const https = require('https');
> https.get('https://example.com')
```

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
I think this is due to the latest version of node-fetch going all-in on ES Modules. ESM in Node does not use `require()` internally at all, which makes it nearly impossible to hook imports in the way that HTTP Toolkit normally does to inject proxy settings (similar to how other require() hooks work, e.g. when mocking modules for unit testing, or adding support for importing more filetypes in node).

The lack of support for import hooks is an ongoing Node issue that's being debated here: https://github.com/nodejs/modules/issues/351.

In this specific case you can work around this, because HTTP Toolkit's hooks do work fine for node-fetch, and the only problem is that they're not activated, because the import is invisible. You can solve that by explicitly running `require('https')` before rest of your code, which will trigger HTTP Toolkit's HTTP hooks so that all traffic is intercepted.

I'm going to leave this open though - that's a quick workaround, but we're going to need a proper solution for this as ESM gets more popular.

**Comment by delebash** [comment]
Thank you for the work around.  Awesome tool!!!

**Comment by pimterry** [comment]
This issue is now fixed permanently in the latest HTTP Toolkit release - `http` is automatically hooked every time, so that anything that relies on it internally (like node-fetch) will always be intercepted in all cases.

This doesn't solve the related issue that our hooks don't work with ESM, and so some other modules which specifically require special hooks aren't properly intercepted when imported via ESM. I've filed https://github.com/httptoolkit/httptoolkit/issues/298 separately to track that.
