### ISSUE TITLE
Mercurial command not working when using 'Fresh Terminal'

### ISSUE THREAD

**Issue by krishnaraj** [httptoolkit/httptoolkit#285]
![image](https://user-images.githubusercontent.com/141018/171053943-f1b17e7f-46fa-4b02-9aaa-6e4d2dfcb5a9.png)

'hg' command complains of 'ModuleNotFoundError: No module named 'http.cookiejar'' when using 'Fresh Terminal' interception.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hmm, I'm not sure what's happening here. What happens if you open an intercepted terminal, and run `python` then `import http.cookiejar` in the REPL there directly?

I've just tested that and it seems to work fine, so I'm not sure why it would fail when loaded through Mercurial...

Which versions of Python and Mercurial are you using?

The way this works is that HTTP Toolkit prepends [this directory](https://github.com/httptoolkit/httptoolkit-server/tree/master/overrides/pythonpath) to your PYTHONPATH, which allows it to add hooks to a few modules as they're imported. Each module in that directory re-exports the real module, but makes some small patches en route to override the proxy & cert settings when the module is used. I haven't seen that fail before, but this must be some issue within the patches there somewhere.

**Comment by krishnaraj** [comment]
Importing `http.cookijar` in REPL works correctly. So far only the `hg` command seems to be having this issue.

**Comment by krishnaraj** [comment]
I am getting the same error on a mac too. Just did a `pip3 install mercurial` then opened a 'Fresh Terminal' and ran `hg --version`.

**Comment by pimterry** [comment]
Ok, I've traced this down to Mercurial's internal `hgdemandimport` module. In the root `hg` script, replacing [that code](https://www.mercurial-scm.org/repo/hg-stable/file/tip/hg#l48) with `pass` fixes this issue. Looks like that also means this will work correctly if you use Python >3 <3.6 too.

The code for `hgdemandimport` itself is here: https://www.mercurial-scm.org/repo/hg-stable/file/tip/hgdemandimport/demandimportpy3.py

From what I can tell, they use this module to make Python imports automatically lazy, and that's somehow interfering with HTTP Toolkit's own hooks.

I think there's a couple of options to fix this: we could add a hook for `hgdemandimport` itself, and disable that entirely (seems like an optional performance optimization), or we could eagerly load the `http` module before that point so it skips lazy loading, or we could wrap the `hg` command and disable intercepting it entirely. Probably many other approaches available too...

It is also possible that there's an actual issue in our hook, but since they're very simple and they works everywhere else, and this hg code is quite funky, I'm a bit suspicious. I can't see anything obvious that would cause this.

I'll think about this over the next week and see what I can come up with. In the meantime, you should be able to comment out the above lines or use a slightly older Python version as a workaround.

**Comment by krishnaraj** [comment]
Thanks for the quick workaround.

**Comment by pimterry** [comment]
I've just pushed a release with a proper fix for this. HTTP Toolkit now includes a hook that disables `hgdemandimport` entirely, so everything should work correctly with no workarounds required in future. Next time you open HTTP Toolkit it'll update in the background, and the following run everything should work correctly.

Thanks for reporting this! It's hard to find every possible interaction with every possible tool in advance, so it's really helpful to hear about issues like this :smile:. Hope the fix works well for you, and do let me know if you run into any other problems.
