### ISSUE TITLE
SSL error: tls_early_post_process_client_hello:unsupported protocol

### ISSUE THREAD

**Issue by tuck1s** [httptoolkit/httptoolkit#290]
Watching traffic from an iPhone, these errors are seen on the terminal window:

```
httptoolkit-server: Updating CLI... already on latest version: 1.8.1
Unknown TLS error: Error: 139762295134080:error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1686:

    at initRead (_tls_wrap.js:436:25)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  library: 'SSL routines',
  function: 'tls_early_post_process_client_hello',
  reason: 'unsupported protocol',
  code: 'ERR_SSL_UNSUPPORTED_PROTOCOL'
}
```

Could this message be more informative on the specifics of the protocol?

Background: running on Linux Mint 20.3 inside Virtualbox, openssl version:
```
OpenSSL 1.1.1f  31 Mar 2020
```

Just making a quick request to the proxy from the host machine to the proxy (which I didn't expect to fully succeed, as it's not set to trust the CA) shows that TLS1.3 is offered by `httptoolkit` and can be accepted.

```
curl -v https://192.168.0.23:8000
*   Trying 192.168.0.23:8000...
* Connected to 192.168.0.23 (192.168.0.23) port 8000 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self signed certificate in certificate chain
```

Awesome tool, by the way 🥇 

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
This error comes directly from OpenSSL somewhere. I'm not totally sure how to interpret it - it's not totally clear whether this is an error in accepting a client TLS connection to HTTP Toolkit, or the TLS connection from HTTP Toolkit upstream.

When this fails, does a failing request show up in HTTP Toolkit itself, with the above error as the response body? That should be definitive: if a full request wit this error appears then it's definitely an upstream error, if not (there might be a blank 'connection reset' line shown in HTTP Toolkit instead) then it must be a downstream error.

If it's a downstream error, I suspect this means that the client on iOS is trying to use some very old TLS protocol that isn't properly supported. I'm not sure what the limits are there, or if we can change them... Happy to investigate if you can confirm the versions involved though so I can try to reproduce this. There might be some clues available if you use Wireshark to record this traffic, filter that for `tls`, and look at the client & server handshakes to check which versions are offered in the failing handshake.

**Comment by tuck1s** [comment]
There's no "connection reset" line shown, mostly `GET .. 200`s.

A tcpdump of the client side connection with
```
sudo tcpdump -v -s 1514 port 8000 -w /tmp/proxy1.pcap
```
![Screenshot 2022-06-09 at 17 55 28](https://user-images.githubusercontent.com/11942927/172902518-026087c0-e96e-4f93-9fa3-7033edb38c80.png)

An upstream capture of port 443 traffic shows a lot of successful connections, no obvious TLS errors.
![Screenshot 2022-06-09 at 18 00 48](https://user-images.githubusercontent.com/11942927/172903494-2dee3266-7b1a-40e9-a0d6-441bebb37ffa.png)




shows a lot of TLS1.2 and 1.3 traffic.

**Comment by pimterry** [comment]
Are there any errors shown in HTTP Toolkit at all? If you enable the error filter (start typing 'errored' into the filter box on the View page, and pick the error filter option that appears) then it will show only requests that couldn't be properly sent, due to either upstream or downstream issues.

If you reproduce the error logged above, I think definitely some kind of error should appear with the details of exactly what failed in there. That should either be some kind of "Certificate rejected"/"Connection reset" empty line, or a failing request whose body has the same OpenSSL error message above.

Similarly, when you reproduce the error there must be something corresponding to that in wireshark somewhere, but there's nothing obvious in the screenshots above. Finding this might be more difficult, you might want to look through each TLS stream to try to spot streams that connect and then close almost immediately with little or no application data (which likely means the client wasn't happy), or streams that show a TLS alert (which may or may not be encrypted I think, so I'm not sure if that's always visible in this case). Or you can try to watch the TLS connections at the exact time the error appears (if you don't have too much other TLS traffic).

Once you find the TLS connection that's actually failing, you can see exactly what SSL version the client is requesting and what the server is offering, and that mismatch should tell us what the problem is.

If you're struggling to find the correct TLS exchange, but you've got collected data in Wireshark that you're sure contains this failing traffic, you can export & share a PCAP here and I'll take a look too and see if I can find what's up.

**Comment by tuck1s** [comment]
I am seeing aborted connections towards Apple domains. Perhaps they are using certificate pinning or transparency to reject connections via the proxy?
![Screenshot 2022-06-10 at 15 01 29](https://user-images.githubusercontent.com/11942927/173082648-6f65ba49-110c-4807-a265-5acacca9433f.png)

**Comment by tuck1s** [comment]
Very detailed reply, thank you. I found one packet on the client --> proxy side that looks like this.

![Screenshot 2022-06-14 at 13 23 14](https://user-images.githubusercontent.com/11942927/173576365-3cf2eb47-638d-4de5-b97b-9db943380822.png)

I suspect but can't be sure that the request
was made by "Lemmings", a game. It appears to be written with the Unity3D package and relies on the iTunes account to hold the player game state. It also makes a ton of other calls when it's running and was prone to being "laggy".

It went through a bad patch of having poor performance, suspected due to latency on the game's calls back to their servers (now somewhat improved), and I was trying to gather info on it so their support team might look at it. I'm not the app author. In other words, it's not really important, just intriguing.

pcap of just that one packet:

[tls10_req.pcap.zip](https://github.com/httptoolkit/httptoolkit/files/8899689/tls10_req.pcap.zip)

**Comment by pimterry** [comment]
> I found one packet on the client --> proxy side

Perfect, thanks! Yes, that's definitely a TLS v1.0 packet to `gateway.icloud.com`, and that's exactly the kind of thing that would cause this error.

Interestingly though, I've just done some quick testing, and that server doesn't actually support TLS v1.0 - any such TLS connection is rejected with a TLS alert 70: "The protocol version the client attempted to negotiate is recognized, but not supported".

I have managed to find a workaround for this for you on the client end anyway: you can support this by launching HTTP Toolkit with the env var `HTTPTOOLKIT_NODE_OPTIONS="--tls-min-v1.0"`. That won't work forever (as above - Node will stop supporting this entirely in a year or so) but AFAICT it works right now. I'll keep investigating full support for this, but that should solve your immediate problem.

Note though that HTTP Toolkit _doesn't_ try to match the exactly TLS version downstream & upstream while proxying, which means you'll see some interesting behaviour here. The connection to HTTP Toolkit should start working, accepting the app's TLSv1 connection so you'll see the request data, but then the upstream connection will also work even though it probably fails in real normal usage (because the server doesn't support TLS v1.0). The upstream works in this case because HTTP Toolkit does support TLSv1.3, so it will successfully negotiate to start using that with the server. This might not matter for your testing, but it's worth being aware of!

> Filtering on ssl.handshake.extensions_server_name == "gateway.icloud.com" there is one more packet, that seems to have a strange supported_versions value of 0x6a6a.

This is due to GREASE: https://tools.ietf.org/id/draft-ietf-tls-grease-01.html. This is a technique of injecting various invalid unused values into TLS packets to force clients & middleboxes to accept unrecognized data, to try and make sure that in future TLS has fewer backward incompatibility challenges. That's totally fine, nothing to worry about.

I can't be sure, but looking at the PCAP I'm fairly confident that the second packet is from a different client app, not just a retry from the same implementation. It's not just that the version is different, but it also supports a quite different set of cipher suites and uses lots of other different extensions. I expect that's just some other more up-to-date app that's talking to the same server.

**Comment by tuck1s** [comment]
Great, thank you. Closing this issue.
