### ISSUE TITLE
Intercept request without VPN on Android

### ISSUE THREAD

**Issue by thiagobenine** [httptoolkit/httptoolkit#293]
Is it possible to intercept HTTPS requests on Android using HTTPToolkit **without using a VPN**? I need to intercept requests of an app but this app doesn't allow VPN. 
Just to mention, I know [Charles Proxy](https://www.charlesproxy.com/) works perfectly without a VPN on the phone, it would be great if I could achieve the same with HTTPToolkit.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by thiagobenine** [comment]
One thing come to my mind. Do you know [ProxyDroid](https://github.com/madeye/proxydroid)? With rooted devices it can act as a global proxy, it uses something related to IPTables to achieve this. What do you think of following the same strategy? I mean, adding a use case that rooted devices can opt in to not use a VPN

**Comment by pimterry** [comment]
Hi @thiagobenine, yes, you can absolutely do this! The VPN is used because most of the time it's much more convenient, but internally HTTP Toolkit is really an intercepting HTTP(S) proxy just like Charles and others. Any client setup that works for other tools with work exactly the same for HTTP Toolkit.

All the VPN app does is _automatically_ manage your proxy settings, manually redirect traffic that ignores proxies (e.g. older devices/apps, some apps that try to avoid proxies), handle cert setup, and provide a nicer UX to turn things on/off and know when interception is enabled. It's not required if you want to avoid it.

In an environment where you can't use the normal automatic VPN setup, you'll need to do two things:

* Configure your Android proxy settings, either in the normal Android wifi settings, or using an app like ProxyDroid - HTTP Toolkit supports all HTTP & HTTPS proxy clients, so you can do this any way you like.
* Trust the HTTPS certificate. HTTP Toolkit will have generated a CA certificate on your computer, which it uses to intercept encrypted HTTPS traffic, but this only works when the client trusts that CA certificate. The normal automated setup configures this for you, but without that you'll need to either do that manually.

The settings you'll need are shown in the 'Anything' option on the Intercept page of HTTP Toolkit on your computer.

You can do cert setup by following fully manual guides as with Charles etc, or if you want you could do the normal setup via HTTP Toolkit (which will do all the cert steps for you), and then just disable the VPN at the end and add your proxy settings. AFAIK that should work fine.

Does that all make sense? Let me know if you have any questions.

**Comment by thiagobenine** [comment]
@pimterry Thank you so much for the clear answer. It is now perfectly working. 
Just one question: I needed to manually install the certificate on Android, but when using Charles this is not required, do you know why?

**Comment by pimterry** [comment]
> Thank you so much for the clear answer. It is now working perfectly.

Great! Glad you've got that sorted :+1:

> I needed to manually install the certificate on Android, but when using Charles this is not required, do you know why?

I can't be sure, but I suspect you have done some certificate setup somewhere for Charles in the past that's still in place. I'm not sure if Charles has an official guide for Android, but every unofficial guide I've found has a certificate setup step, equivalent to what HTTP Toolkit is doing internally. That's unavoidable really, as somehow you have to make your target Android app trust your interception certificate for TLS. If Android allowed TLS interception with no certificate setup at all then HTTPS would be totally insecure, since it would trust _anybody_ to read & modify your traffic.

If you want to know more about how this works, I wrote up a detailed guide to Android's HTTPS & certificate internals here: https://httptoolkit.tech/blog/intercepting-android-https/
