### ISSUE TITLE
Error (Server shutdown unexpectedly)

### ISSUE THREAD

**Issue by MateoElias** [httptoolkit/httptoolkit#295]
Upon installing on Windows 7, and when trying to use the tool I am immediately met with the error: `"Server shutdown unexpectedly with code **3221225785**"`, because of this the app as is, its unusable and wont even start. Could it be because of my operating system? as I have been having issues installing latest versions of Node.JS.

Thanks in advance.

![image](https://user-images.githubusercontent.com/61370647/174239831-9c07c8f0-037e-4212-a64f-03b794ce307b.png)

**Comment by pimterry** [comment]
Yes, this is due to Windows 7.

Windows 7 has been officially unsupported by Microsoft and EOL for a few years now. Many of HTTP Toolkit's dependencies no longer support it, so it's impossible to continue supporting it ourselves I'm afraid.

I'd very strongly recommend updating/switching OS ASAP, as there are known security vulnerabilities in Windows 7 that will never be fixed.
