### ISSUE TITLE
Passing Through unsupported methods

### ISSUE THREAD

**Issue by Mikowmer** [httptoolkit/httptoolkit#305]
Hi! I was recently attempting to inspect the traffic coming from an app. Unfortunately, it was using an unsupported method, likely a TCP method as opposed to an HTTP method.

Issue #244 means that I won't be asking for it to be supported. However.

HTTP Toolkit doesn't pass on these unsupported methods, which means that the app I'm inspecting doesn't work at all. If I disable HTTP Toolkit, it starts working normally again.

Would it be possible for HTTP Toolkit to pass on these unsupported methods blindly? Or does the implementation method mean that this isn't possible?

---

_Does this affect you too? Click the :smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @Mikowmer, do you have an example of this, and any info on where it comes from and what protocol is being used?

If you could share a screenshot of the failing request in HTTP Toolkit that would be helpful.

You're describing this as unrecognized methods, but it sounds like this is just raw non-HTTP TCP data (bear in mind that a 'TCP method' is not a thing - the data is just shown in the 'method' area in HTTP Toolkit because that's a best guess at trying to parse it as if it was HTTP). Right now it's not possible to proxy traffic like this at all unfortunately, since it doesn't include some necessary data like a `host` HTTP header, which is how we work out who to proxy the traffic to. To proxy this requires a completely different mechanism, which depends on the specific protocol being used.

It sounds like you're doing this on Android though, and there are some options there to avoid redirecting the traffic to HTTP Toolkit in the first place. In the HTTP Toolkit Android app, when it's connected, you'll find buttons appear to configure traffic capture by port, and by app. If you try using those, does that help? You could disable intercepting this app entirely for example, if you're actually interested in other traffic, or you could try removing all the redirected ports configured there, which can help to fix unintended non-HTTP interception in many cases.

**Comment by Mikowmer** [comment]
I apologise for getting back to you so late. I turned off all of my GitHub notifications after the Great Epic Games Developer Ping Incident.

To answer your questions, I was attempting to trace some traffic on the FanFiction.net Android app, but all of it appeared to be non-HTTP traffic. As a consequence, because it wasn't getting to their servers, I was just getting a whole lot of nothing on the app.

At the moment, I'll need to get my Android VM's set up again (which won't happen in the near future, Real Life is rearing its ugly head at the moment), but I'll probably come back to this at some stage if there is a way to ignore the non-HTTP traffic, and hopefully get some HTTP traffic that will give me the information that I would like.

**Comment by pimterry** [comment]
No problem @Mikowmer. In the case you're describing though, I think you're probably looking for #108.

Assuming the app is sending data via TLS (you can tell by looking at the URL in the garbled HTTP Toolkit data - if there's at least an `https` there and a real domain name, that should be enough))and there's a unique domain name + port used for this protocol (very common) then this would be enough to allow you to exclude interception for traffic sent to that address entirely, while still intercepting everything else, which would solve your issue. Does that make sense?

**Comment by Mikowmer** [comment]
Yes, that does, thank you! I'll see if it works when I get the chance, and I'll let you know how it goes.
