### ISSUE TITLE
[Bug]: Symbolic link at ~/.bashrc is deleted and replaced with a file during during terminal setup

### ISSUE THREAD

**Issue by lkrms** [httptoolkit/httptoolkit#307]
### Repro steps

1. Create a symbolic link from `~/.bashrc`, for example to your dotfiles repo
   ```bash
   ln -s ~/dotfiles/.bashrc ~/.bashrc
   ```
2. Open the HTTP Toolkit desktop app
3. Use the "Intercept" tab to open a fresh terminal, or click "Existing Terminal"
4. Check your `~/.bashrc`--it will have been replaced with a normal file in the process of adding the HTTP Toolkit shell script at the end

Although this doesn't result in immediate loss of data, it does result in broken functionality and if edits are made unknowingly on an unlinked `~/.bashrc`, they may subsequently be lost when the symbolic is re-provisioned.

It would be preferable for the symbolic link to be followed and its target edited, and/or to have an option to disable profile script edits entirely.

### How often does this bug happen?

Every time

### The desktop OS you're using

Linux (Arch) and macOS*  (*haven't replicated definitively on macOS yet)

**Comment by pimterry** [comment]
Ah, interesting! I hadn't considered that, yes, good catch. These modifications are only temporary (they're removed automatically when HTTP Toolkit exits) but that obviously won't undo the write in this case (it'll just undo the changes in the unlinked file) so that's clearly a problem.

I think the best solution would be to follow links, if present, and modify the original instead. I think I have a solution to that [here](https://github.com/httptoolkit/httptoolkit-server/commit/e7703574215ef511d2810f8f5ade71cee1318721). I need to do a bunch more thorough testing to confirm that works correctly in various environments before I release it, but I think it should cover this correctly.

If you've got a minute to test this out yourself ([dev setup steps here](https://github.com/httptoolkit/httptoolkit-server#contributing) - you'd just need to run the server and then open app.httptoolkit.tech in a browser) to just confirm that it now works as expected on your system, that would be very helpful.

> 3. Use the "Intercept" tab to open a fresh terminal, or click "Existing Terminal"

I think 'Existing Terminal' shouldn't do this, this is just part of 'Fresh Terminal'. Are you sure you're seeing that behaviour?

Unfortunately this is required to make 'Fresh Terminal' work reliably in many cases, so it can't really be configurable there. Interception relies on injecting environment variables into the new terminal, and without this setting your own config is very likely to override that, and stop terminal interception working in confusing and hard to debug ways.

In the meantime, if you'd like to avoid this for yourself, I'd suggest just using 'Existing Terminal' instead - that doesn't (or at least, shouldn't) modify anything on disk, it just serves a script to set all the required env vars, and provides a command to remotely pull and run that script on-demand in your terminal.

**Comment by pimterry** [comment]
This is now fixed in the latest server release (v1.9.1). When you next run HTTP Toolkit it'll update in the background automatically, and the following startup everything should work correctly. Thanks for reporting this, do let me know if you run into any other issues at all.

**Comment by lkrms** [comment]
Sorry for disappearing so rudely after opening this, @pimterry! Too many plates spinning, not enough hands. I really appreciate you responding -- and fixing -- this issue so quickly. (It's fully resolved in all of my dev environments, anyway.) Thank you 🙏🏻
