### ISSUE TITLE
[Bug]: macOS - Electron binary can not be selected in UI

### ISSUE THREAD

**Issue by andriy-bcio** [httptoolkit/httptoolkit#308]
### Repro steps

Description:
When opening electron app on macOS it is required that UNIX binary is referenced (the one inside of xyz.app/Contents/MacOS/), however it is not possible to open the binary, only .app bundle (can not enter what would be normally in "Show package contents" menu).
The workaround is to either "Go to Folder" and proceed down the path of .app/Contents/MacOS or drag and drop the binary onto the httptoolkit "open" window thus passing the correct binary path.

For reference, instructions in the menu:
Start an Electron application with HTTP Toolkit's settings injected, to intercept all its HTTP & HTTPS traffic.
To run a Mac .app bundle, select the executable within. It's typically in Contents/MacOS inside the bundle.
Once you've run an application, it'll be saved and shown here so you can rerun it later.

Steps to reproduce:
1. Open HttpToolkit app
2. Click "Electron Application"
3. Click "Select an application"
4. Select the desired application
5. Click open or double click on the application

Expected result:
Should be able to proceed further down the path to add the executable

Actual result:
Selection window closes and an error pops up in "Electron Application" section for a split second.

### How often does this bug happen?

Every time

### The desktop OS you're using

MacOS 12.4

**Comment by andriy-bcio** [comment]
@pimterry 
Hello Tim, I'm seeing that intercepting Electron app is now disabled (coming soon), was it intentional because of this bug? However imperfect the addition is we would really appreciate to have it available, rather than disabled.
Thanks!

**Comment by pimterry** [comment]
Hi @andriy-bcio, unfortunately even if it was re-enabled, it's basically not functional as-is on Mac, due to Mac file selection limitations. The default file picker won't let you pick inside app bundles, which completely breaks selecting any application in a very confusing and awkward way.

More detail here: https://github.com/httptoolkit/httptoolkit/issues/329#issuecomment-1251658095 (I'm going to close this issue in favour of that one).

In general, I would definitely like to see this fixed, but it's not easy and I don't have an immediate plan for that. In the short term, your options are a) investigate the details in that issue and open a PR to fix this (HTTP Toolkit Pro is free for contributors! More details here: https://github.com/httptoolkit/httptoolkit/#contributing-directly) or b) use Windows or Linux, where Electron interception is fully supported.
