### ISSUE TITLE
[Bug]: Intercepting an HTTP response and then resuming it corrupts the response body 

### ISSUE THREAD

**Issue by anthonytliu** [httptoolkit/httptoolkit#309]
### Repro steps

1. Set up HTTP Toolkit to intercept API call from Android application
2. Intercept a GET call
3. See that GET call is intercepted properly
4. Click resume and observe the response body 
5. Response body should be converted from JSON to random unicode characters

### How often does this bug happen?

Every time

### The desktop OS you're using

MacOS 11.6.1 (20G224)

### Details of other apps/devices

Using a Pixel 3a, non-rooted. 

### Error screenshot

<img width="1904" alt="Screen Shot 2022-07-19 at 3 47 44 PM" src="https://user-images.githubusercontent.com/18356575/179861094-7d072a76-0628-4c86-98c0-f014070304a1.png">

**Comment by pimterry** [comment]
This is due to content encoding (because of the `content-encoding` header in this response, the body needs to be gzipped after you edit it, but due to a bug it's actually being double-gzipped, so that when HTTP Toolkit un-gzips to show you the real content it just gets more raw gzip data, which is the data you're seeing here).

I'm fairly sure this was a temporary bug that has since been fixed though, so it's most likely that this actually means that your app isn't updating correctly. I've just tested, and I can't reproduce this on the latest release.

Alternatively, it's possible that you just haven't been using HTTP Toolkit recently so it hasn't had time to update, and so if you close the app and restart it now it'll immediately fix this issue and start working correctly :smile:

If not, can you please hover your mouse over the 'HTTP' icon in the top left, and share the versions it shows there? That will include all info for each of the components of HTTP Toolkit. The desktop version isn't important, but the latest server version is 1.9.0, and if you're using an older version then you may see this issue.

I'm not sure why that wouldn't update. If you're persistently seeing this not update successfully, it would be helpful if you could launch HTTP Toolkit from the command line by running `/Applications/HTTP\ Toolkit.app/Contents/MacOS/HTTP\ Toolkit` and then share the output here, which will probably include some kind of update error.

**Comment by pimterry** [comment]
Happy to investigate further, but please share the details above.

For now, I'm going to assume this was indeed the old bug, so it will most likely be fixed automatically once your software has updated. As in the comment above - if that's not true, please share more info and I can investigate further.
