### ISSUE TITLE
Tools for handling base64-encoded content

### ISSUE THREAD

**Issue by pimterry** [httptoolkit/httptoolkit#31]
Many clients send base64-encoded content, either in the body of the response or the header values. It would be useful to have an easy way to decode this.

Unclear what format this should take, since we can't easily tell when it's required...

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by daluu** [comment]
Do some headers indicate the use of base64? Otherwise, maybe try/catch - if succeed, return the decoded content, otherwise return "as is" as text. And if to avoid always doing this, maybe have this as option to enable otherwise don't bother trying to decode base64?

And when decoded, simply return as a hexdump like how Wireshark does it? Since encoded content is likely binary.

**Comment by pimterry** [comment]
I'm going to close this, since that was actually implemented a little while back! Thanks for the reminder @daluu.

Right now, Base64 body content is detected by test-decoding the data, as long as it's less than 100 KB. If it's larger then this isn't supported, but you also probably don't want to look through the raw data by hand in HTTP Toolkit anyway, since that strongly suggests it's a large binary file. In that case, it'll be better to download it and use the appropriate tools to parse and handle the content.
