### ISSUE TITLE
Do Not Change HTTP Header Order

### ISSUE THREAD

**Issue by H0r53** [httptoolkit/httptoolkit#311]
HTTP Toolkit appears to be sorting/modifying headers before they are sent. This makes the use of HTTP Toolkit easily detectable and renders the utility useless for any site that blocks requests that have been modified.

Please, if nothing else, make the modification of HTTP Headers optional. I would like to use HTTP Toolkit to capture HTTP communications verbatim, without any modifications to the data that is transmitted. I have the paid Pro version and this is still an issue.

**Comment by pimterry** [comment]
Hi @H0r53, can you share an example that reproduces this issue please?

I've just tested for myself by running:

```
curl -X GET -H'a: 1' -H'c: 2' -H 'b: 3' http://httptoolkit.tech
```

in an intercepted terminal, and then looking at the raw HTTP traffic with Wireshark I see those three headers forwarded upstream by HTTP Toolkit exactly as they're received (i.e. lowercase, ordered as "a, c, b").

More generally, while HTTP Toolkit makes best efforts to preserve traffic details when forwarding, especially for semantically meaningful differences, this isn't perfect and there will always be small detectable differences.

It's very difficult (or impossible) to make a HTTP proxy undetectable to a sufficiently determined server, in large part because comparing TLS fingerprints alone is both easy & sufficient if the server has a small set of known clients or is willing to risk blocking unknown browser traffic. Perfectly proxying arbitrary TLS fingerprints is not possible with any existing tooling I'm aware of (e.g. it's not supported by OpenSSL, so that would need major changes there, just for starters) and would have serious performance downsides (e.g. we'd have to exactly pair every upstream & downstream TLS connection, instead of polling, thereby creating a lot more connection overhead and latency through to the proxy).

Also in many cases when you're using HTTP Toolkit's automated setup, the client is aware that it's talking to a proxy, and so will send mildly different headers to what it'd send normally. It's possible to intercept traffic without that using iptables etc for packet redirection, but it's a limited approach and the UX is generally far worse.

**Comment by H0r53** [comment]
Example Chrome headers when sent to my own local HTTP server for traffic inspection.
```http
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
```
Headers when using the Chrome instance launched and intercepted by HTTP Toolkit.
```http
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Host: 0.0.0.0:5000
Connection: keep-alive
```

**Comment by H0r53** [comment]
I'm using Chrome in either case and my understanding is TLS fingerprinting should not be an issue if the agent is Chrome. That could be what is detecting HTTP Toolkit, but based on the results above it seems like HTTP fingerprinting is the likely issue.

**Comment by pimterry** [comment]
> my understanding is TLS fingerprinting should not be an issue if the agent is Chrome

Unfortunately this is not true. HTTP Toolkit has a different TLS fingerprint to Chrome. Because the requests will contain a Chrome user-agent but sent with a non-Chrome TLS fingerprint, anybody who is sufficiently determined to strictly block all unusual clients can always detect and block HTTP Toolkit through TLS fingerprinting alone.

The same issue applies to all HTTPS proxies I'm aware of. They have to receive the TLS connection from the client, and make their own separate TLS connection to the upstream server. In general this upstream connection will always have a different fingerprint, and trying to make the fingerprints exactly match is effectively impossible right now (due to the UX tradeoffs & tooling limitations above).

If you'd like to help fix this, that'd be very valuable to the entire community - I think the main step would be creating APIs in OpenSSL to allow configuration of the many fingerprintable details like extension ordering etc. See https://github.com/nodejs/node/issues/41112 for some context.

HTTP Toolkit does shuffle some of its TLS settings to avoid looking like any other known tools, which is normally sufficient to avoid blacklist blocking (e.g. "block all requests by Python/Node/curl" - the most common approach) but for strict whitelist blocking (e.g. "block all requests except recognized browser versions) it's not enough.

If you're interested in the details, you can test this for yourself - just load https://ja3er.com/ in a normal Chrome window, and in an HTTP Toolkit Chrome window, and you'll see the different TLS fingerprints there.

From the details there, it sounds like the header issue you're seeing isn't due to header reordering in general, but just the specific order of those two headers (`connection` & `host`), is that right? Unfortunately those are both fairly essential headers involved in the basic connection management, and so some internal part of the HTTP parsing & generation libraries used to make connections must be managing them specially. I will look into that, since I agree it would be better to avoid this, but I don't think it will fix your issue. I think it's very very unlikely that that is the cause here - if you're using Chrome and seeing traffic being blocked, this is almost certainly due to TLS fingerprinting, because that is definitely a real check used in many places.

**Comment by H0r53** [comment]
@pimterry thanks for your detailed and informative response. I performed the following test to rule out TLS fingerprinting on the particular website I've experienced issues with.

- Navigate to target website in Chrome
- Copy the request as `curl`
- Send the same request via `curl`

The request was successful.

If TLS fingerprinting was the issue, then I would think `curl`'s TLS stack would be well-known and blocked. Here is the interesting part. I performed the same test as above, but this time I rearranged the HTTP headers in the `curl` request. This should flag any detection based on HTTP header order. To my surprise the request was still successful.

Therefore, it does seem that HTTP header order is not the specific issue and TLS fingerprinting may be at play. What is crazy to me is I would think that `curl` would be blocked if HTTP Toolkit is also blocked.

Back to the issue at hand - **if TLS fingerprinting is used by a website to block HTTP Toolkit, are there any workarounds that you know of?** You mentioned using ip-tables and that could be a possibly solution, or perhaps something such as `tcpdump`.

**Comment by pimterry** [comment]
That makes sense, it does sound like this is a TLS fingerprinting issue in your case. It's always a bit of an unpredictable process of what gets blocks - it's not that somebody is specifically deciding to add curl to a list or not (and indeed curl will have many fingerprints, depending on the specific version and the OS used and libraries it's linked against). Instead, in practice my impression is that this is usually implemented with basic machine learning/pattern matching powered by large datasets of the server's/service provider's normal traffic. That tends to be close enough, but it does make the specific blocks a bit of a black box to everybody involved :shrug:

> if TLS fingerprinting is used by a website to block HTTP Toolkit, are there any workarounds that you know of

Unfortunately, no.

For some use cases, you may be able to use [Wireshark](https://www.wireshark.org/) instead (which directly observes raw traffic, without proxying it) but that comes with many limitations: it's much more complicated to set up, it requires you to somehow provide the TLS keys used by each connection yourself (i.e. it can't automatically decrypt TLS for you) and it can only show raw traffic - it can never modify it. Might be useful though, depending on your use case.

This is a hard problem that lots of other similar projects are looking into as well, but if you're trying to access a site that's doing the strictest possible checks then there are no good workarounds I'm aware of right now. This affects every single HTTPS debugging proxy I know of, not just HTTP Toolkit. If you do find a tool or solution that works though, do please let me know!

**Comment by H0r53** [comment]
Fortunately, I was able to find a few workarounds. I'm able to capture and decrypt the traffic in WireShark. If you're using Chrome for example, you can set a SSLKEYLOG environment variable that stores the SSL keys and can be imported into WireShark to decrypt the traffic. So that works, but clearly I can't do things like spoof responses like I can in HTTP Toolkit. I'm also able to hook into SSL routines via binary instrumentation to observe the raw traffic. So I don't necessarily have an issue anymore, I'm just curious as to why HTTP Toolkit is being detected and blocked in this case. It seems like TLS fingerprinting is the most likely explaination. It's a bit unfortunate but it doesn't sound like much can be done at this time.

**Comment by pimterry** [comment]
I've just pushed an update with a few big improvements here @H0r53. HTTP Toolkit will update in the background next time you run it, within a couple of minutes, and then the subsequent time this should work much better. This isn't a perfect fix, but in my testing it now avoids most blocks automatically.

Can you update, and then test out your use case again?

**Comment by H0r53** [comment]
I'm not exactly sure what version I was using before but after launching HTTP Toolkit is now reporting `Version 1.7.0 (1.7.0)`. I opened a new intercepted instance of Chrome and the website that was blocking / detecting HTTP Toolkit before is still blocking / detecting HTTP Toolkit somehow.

**Comment by pimterry** [comment]
If you hover over the HTTP icon in the top left, you can see the versions of the various subcomponents - things should be improved if you're using server 1.10.0+.

As a quick test, you can also try www.g2.com (which previously showed a Cloudflare captcha) and [opensea.io](https://opensea.io) (which showed a full Cloudflare block page) - both now work for me locally with no problems.

One thing I have seen is that you avoid even more blocks when using Firefox, because HTTP Toolkit's TLS fingerprint now very nearly matches Firefox's, so this means headers & behaviour are consistent with the fingerprint. Enabling HTTP/2 also helps some cases - that's disabled by default for clients that don't explicitly force it via ALPN, as it's a bit unstable/experimental still, but Pro users can force-enable it in the settings.

If that doesn't help, can you share the site you're testing, so I can reproduce the issue & investigate?
