### ISSUE TITLE
[Bug]: Http toolkit doesn't recognize emulator

### ISSUE THREAD

**Issue by asafe199** [httptoolkit/httptoolkit#314]
### Repro steps

Hi!
I'm trying to connect on emulator, but unsuccessful. My ADB server it's running on port 5037 and I already test with Android API 10 | 11 and cpu x86 | x86_64.

Is there some bug? I can give more information if necessary.

### How often does this bug happen?

Every time

### The desktop OS you're using

MacOS Monterrey - v12.5

### Details of other apps/devices

Android 10 | 11 and Cpu x86 | x86_64

### Error screenshot

![Screen Shot 2022-08-03 at 15 24 25](https://user-images.githubusercontent.com/39995089/182718449-6221fd23-00c1-4cb2-8199-1a4b3028fab6.png)

**Comment by asafe199** [comment]
Update: It worked for me : https://github.com/httptoolkit/httptoolkit/issues/180

**Comment by pimterry** [comment]
Ah, so just to be clear: the issue was that `localhost` didn't resolve on your computer?

Out of interest, if you undo your localhost fix to reproduce the issue, would `test.localhost` resolve correctly?

I've seen that using `*.localhost` as a test domain works independently of DNS setup in some cases, e.g. Chrome. If that works I could change internal addresses to use that, and it might help avoid issues like this for other users in future.
