### ISSUE TITLE
[Bug]: Desktop app freezing after a few minutes when monitoring requests

### ISSUE THREAD

**Issue by MakeShiftArtist** [httptoolkit/httptoolkit#316]
### Repro steps

1. Connect desktop app with Android device via ADB
2. Open an app that makes frequent requests
3. Monitor requests in the "View" page

### How often does this bug happen?

Often

### The desktop OS you're using

Windows 10

### Details of other apps/devices

- Using the app iFunny
- Seems to happen when the desktop is open in the background for too long.

### Any other info?

- Pausing traffic monitoring seems to keep the desktop app from freezing

**Comment by pimterry** [comment]
Hi @MakeShiftArtist. Thanks for reporting this, that certainly sounds like a bug.

Approximately how many requests are we talking? Hundreds, thousands, 100s of thousands? If you intercept enough traffic the app will eventually start to break necessarily, as we have to store every request, so it unavoidably uses up increasing amounts of memory. It should take a very large number of requests (or a machine with very little memory) before that really seems to cause problems though.

Each run, HTTP Toolkit creates a log file, which may contain some clues. That's stored at `C:\Users\<username>\AppData\Roaming\httptoolkit\logs\last-run.log`. Next time you run into this issue, can you please close HTTP Toolkit and then share that file here? Be careful not to restart it, as that will reset the log file.

It would also be useful to try launching the app from the command line (follow the shortcuts to find the .exe path, paste that path into a cmd window), reproducing the issue (if it's possible to do so on purpose) and then sharing that output here. That will contain similar output to the log file, but there's some parts of the desktop wrapper that could cause this which may log there directly, and so that output might not make it into the main log file in cases like this.

**Comment by MakeShiftArtist** [comment]
I was able to recreate the bug and it froze at about 13000 requests. I wasn't able to find the log folder in the project files.
![image](https://user-images.githubusercontent.com/47653736/185815272-40f3a09e-cc7f-4733-86d3-309ee5e3ace6.png)
Nor was I able to open the folder via the terminal

**Comment by pimterry** [comment]
> I was able to recreate the bug and it froze at about 13000 requests.

That's quite a lot, but not enough that I'd expect it to crash in normal usage. Are these especially big requests? If many of those were video, for example, then that would be a large amount of data that would definitely break things on most machines.

How much RAM do you have in your system? When it crashes, how much is HTTP Toolkit using? If you run out of memory almost complete, and so request data starts paging to disk, you would probably see serious UI freezing problems.

> I wasn't able to find the log folder in the project files.

Ok, this might mean you're running an old version of the desktop wrapper that doesn't generate the log files. You can manually update it by downloading the latest installer from https://httptoolkit.tech. Almost all the app auto-updates, but the desktop shell itself doesn't, and that's the part that handles capturing logs from the rest of the app. Version 1.9.1+ should include this. There'll also be a 'View HTTP Toolkit logs' button in the Help menu that will link directly to the logs.

> Nor was I able to open the folder via the terminal

I'm not sure what this means

**Comment by MakeShiftArtist** [comment]
> That's quite a lot, but not enough that I'd expect it to crash in normal usage. Are these especially big requests? If many of those were video, for example, then that would be a large amount of data that would definitely break things on most machines.
No the requests usually being made were small ad requests. One every couple seconds.

> How much RAM do you have in your system? When it crashes, how much is HTTP Toolkit using? If you run out of memory almost complete, and so request data starts paging to disk, you would probably see serious UI freezing problems.
Memory doesn't seem to be an issue because I have 16gb of ram and everything else runs fine, but I can check my memory usage next time it occurs.

> Almost all the app auto-updates, but the desktop shell itself doesn't, and that's the part that handles capturing logs from the rest of the app.
I'll update it and try to obtain the logs again


> I'm not sure what this means
Was basically just repeating myself. My b

**Comment by pimterry** [comment]
@MakeShiftArtist have you seen this issue any more since it last happened? I'm still happy to investigate further if you can still reproduce the issue and share some logs from after it breaks.
