### ISSUE TITLE
[Bug]: Certificate rejected for connection to ip

### ISSUE THREAD

**Issue by PaulDotSH** [httptoolkit/httptoolkit#317]
### Repro steps

1. Open the app with a browser attached like Brave
2. Go to krunker.io
3. Wait for the website to load
4. The website fails to load, http toolkit giving a bunch of
"Certificate rejected for conection ip_.RANDOMSTRING.krunker.io"

### How often does this bug happen?

Every time

### The desktop OS you're using

Arch Linux

**Comment by pimterry** [comment]
Hi @PaulDotSH, thanks for reporting this, this is really interesting!

I've done some digging, and what's happening is that underscores are now completely disallowed in TLS certificate domain names, and these names contain an underscore. HTTP Toolkit ignores this and generates a normal certificate regardless, but then Chrome rejects it as invalid.

This is surprising! It's especially weird because these are still valid domain names, but as of mid-2019 it's just impossible to create TLS certificates for them (https://www.ssl.com/faqs/underscores-not-allowed-in-domain-names/). It looks krunker avoid this issue themselves by using a wildcard TLS certificate to cover the whole group with `*.krunker.com`.

I'm not sure how recently Chrome started enforcing this certificate requirement, but presumably due to this issue there's not many hostnames that do use underscores nowadays, so this hasn't come up before. Great find!

I'll get this fixed in the next week or so, it should be easy enough to replace this with a `*.<parent domain>` for just these cases. Thanks again for reporting this, I never would've found that myself :+1:

**Comment by PaulDotSH** [comment]
> Hi @PaulDotSH, thanks for reporting this, this is really interesting!
> 
> I've done some digging, and what's happening is that underscores are now completely disallowed in TLS certificate domain names, and these names contain an underscore. HTTP Toolkit ignores this and generates a normal certificate regardless, but then Chrome rejects it as invalid.
> 
> This is surprising! It's especially weird because these are still valid domain names, but as of mid-2019 it's just impossible to create TLS certificates for them (https://www.ssl.com/faqs/underscores-not-allowed-in-domain-names/). It looks krunker avoid this issue themselves by using a wildcard TLS certificate to cover the whole group with `*.krunker.com`.
> 
> I'm not sure how recently Chrome started enforcing this certificate requirement, but presumably due to this issue there's not many hostnames that do use underscores nowadays, so this hasn't come up before. Great find!
> 
> I'll get this fixed in the next week or so, it should be easy enough to replace this with a `*.<parent domain>` for just these cases. Thanks again for reporting this, I never would've found that myself +1

Woah this is such a quick and great write-up, thanks a lot for explaining too!

**Comment by pimterry** [comment]
Just to let you know, this has been now fixed ([here](https://github.com/httptoolkit/mockttp/commit/3fe388c92d7cc2145ef253d0a1fb3563b3e52eee)) and just got released in HTTP Toolkit server last night. If you open your HTTP Toolkit, it'll update in the background, and the following time everything should work correctly. Krunker.io now all seems to load just fine.

> EDIT: also thanks for making HTTP Toolkit, I reported a bug in the past related to .NET apps on your email if you remember, http toolkit's android ssl pinning blog post helped me find and disclose a ton of critical bugs in an app from my country, great work!

Thanks @PaulDotSH! Always great to hear stories like this, really glad to know that HTTP Toolkit helped you find & fix those bugs :+1::+1::+1:. And thanks again for reporting this issue, it's super hard to spot these kinds of intricate bugs myself without other people taking the time to look into problems and share the details like this :smile:.
