### ISSUE TITLE
Clarify the differences between this and in-browser debug tools

### ISSUE THREAD

**Issue by tucpmjc** [httptoolkit/httptoolkit#32]
Hello, the tool visually looks nicer than the built-in debug tools included with browser.  However, can you please point out any differences between this and the built-in tool?  I see nice color coding of the response body, but what else?  Maybe a comparison checkbox between your tool and what is available in Chrome, Firefox, Safari, Edge, etc.

Thanks and keep up the great work!

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Sure! Good idea - I'll polish a proper comparison for the website some time soon, but a quick list for now:

* Supports _all_ browsers, and non-browser clients too (CLI tools, desktop apps, mobile apps, IoT devices, whatever you like), all in one place.
* Much more powerful tools for viewing & exploring the request body (better highlighting, autoformatting, code folding, mouseover hints).
* Built-in documentation for every standard HTTP status code and HTTP header, so you understand what the raw HTTP sent actually means.
* 100% open-source, with the internals available as [a standalone library](https://github.com/httptoolkit/mockttp) that you can use to build your own tools or automation.
* Subjective, but imo much prettier and more user friendly.

Pro-only:
* Integrations with 1400+ APIs. That means live request validation to check the parameters you're sending (or that you've missed), warnings for deprecated parameters or endpoints, and inline documentation for the server, endpoint, parameters, response status & the contents of the response body.
* Caching analysis. You can see the cache headers you're sending, but this will also explain what that means in practice (Is this response cacheable? Until when, and what happens when it expires?).
* Compression analysis. Info on how well your responses are being compressed, comparisons to other compression methods you could use, and warnings or suggestions where you could easily make improvements.
* Import/Export (coming early this week): export requests as ready-to-use code snippets for 15 languages, or as [HAR files](https://en.wikipedia.org/wiki/.har), and import HARs to explore saved HTTP traffic from you or your teammates.

Does that all make sense? Anything you wish HTTP Toolkit had above browser devtools, that isn't yet here?

**Comment by ElijahLynn** [comment]
You missed the BIGGEST difference. 

HTTP Toolkit allows you to pause a request and EDIT the request AND/OR response which is hugely useful debugging applications. Sometimes getting your app to respond a certain way takes moving a mountain and before you move that mountain you want to see if it will work with a response a specific way. THIS does that!

That is THE key here it can intercept and EDIT requests and responses (mocking). Should be bullet point #1.

**Comment by pimterry** [comment]
Haha, excellent point @ElijahLynn! In fact, the list above was written before that existed, but it's now definitely a big difference. More to come soon too :smiley:

**Comment by pimterry** [comment]
I've now published a small selection of comparison pages, highlighting the features HTTP Toolkit has over a few similar tools: https://httptoolkit.tech/alternatives/

I'm going to close this, but feedback on those and further suggestions for points to include and/or other tools to compare with are very welcome!
