### ISSUE TITLE
Feature request: option to delete the system CA cert on Android

### ISSUE THREAD

**Issue by dkter** [httptoolkit/httptoolkit#323]
Android provides an interface for deleting user CA certs, but not system ones. It would be nice if I could tell HTTP Toolkit to delete the CA cert it installed, in order to restore my device to the way it was before installing HTTP Toolkit.

(I'm running into an issue trying to inspect an app that worked before but no longer works, and would like to reset everything as a troubleshooting step.)

---

_Does this affect you too? Click the :smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @dkter, it would be technically possible to provide a way to do this, but the UX is a little tricky...

On the other hand, it is easy to remove the certificate manually: just reboot the device. It's 'installed' by mounting an in-memory temp file system over the CA certificates folder, and when the device turns off that will disappear completely. If rebooting is problematic, you could alternatively `adb shell` and unmount the `/system/etc/security/cacerts/` tmpfs mountpoint.

Does that work for you?

More background here: https://httptoolkit.tech/blog/intercepting-android-https/#injecting-ca-certificates-into-rooted-devices

**Comment by dkter** [comment]
Thanks, that was what I was looking for.

(BTW I really appreciate the detailed documentation and blog posts!)

**Comment by pimterry** [comment]
Great! Glad that works :+1:

I'm going to close this for now, since I think the existing "restart your phone" approach is probably the best solution I have to this in the medium term at least, and I suspect it's not a super common problem. And this issue can now act as even more documentation for anybody searching for the same thing in future :smile:.

If you (or anybody else) has any problems or other suggestions for this in future though, feel free to comment here and we can discuss further.
