### ISSUE TITLE
Mark the request

### ISSUE THREAD

**Issue by pb36** [httptoolkit/httptoolkit#326]
Hi, would it be possible to mark the specific requests to distinguish from them once the traffic is captured so does not need to search each time looking for it?

Like, having a separate tab to show the marked requests list or maybe something like a check mark for each request would help develop some flow. (something like in fiddler mark the request feature)

Thank you.

---

_Does this affect you too? Click the :smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @pb36, you can 'pin' messages (using the pin icon, or Ctrl/Cmd+P when a row is selected).

Pins are shown in the list view, so you can easily see those requests, and they're not deleted if you delete all messages (unless _only_ pinned messages are left, and even then it will show a warning).

Does that work for you?

This has suggested a nice improvement here though: we could add a 'pinned' filter, so that you can easily search for pinned messages and hide everything else in the list, without deleting it. That should be quick & easy to do. Would that be useful?

**Comment by pb36** [comment]
Perfect Thank you for pointing out the Pin thing. I didn't even see the pin thing existed in the first point, and yeah, a filter to show only pinned messages would be a great help, and would that be possible to preserve pins when saving Har format and loading back again later?

**Comment by pimterry** [comment]
> would that be possible to preserve pins when saving Har format and loading back again later?

Oh yes, that's also a good suggestion too.

Both of those (persisting pins in HAR exports, and filtering by 'pinned') are now implemented and live :+1:. The app will update next time it starts, and then the following time this should all work nicely. Thanks for the ideas!
