### ISSUE TITLE
[Bug]: Electron application intercept button on Mac suddenly says 'Coming soon'

### ISSUE THREAD

**Issue by ShlomiArc** [httptoolkit/httptoolkit#329]
### Repro steps

Start the application
Under Interception search for the word 'Electron'

### How often does this bug happen?

Every time

### The desktop OS you're using

MacOS 12.3.1

### Error screenshot

<img width="789" alt="Screen Shot 2022-09-19 at 13 12 51" src="https://user-images.githubusercontent.com/112396327/191081662-3b2ff0f3-ed51-45f8-8963-a60b19246e82.png">

### Any other info?

Issue started around Sep 14-15 2022
The day before that the application run fine on my computer and I could intercept Electron apps easily.

I have tried to remove http toolkit from my machine and installed versions:
1.8.1
1.10.1
I have tried to restart the machine

None of the above helped.

**Comment by pimterry** [comment]
Hi @ShlomiArc. Yes, this has unfortunately had to be disabled on Mac for now.

In recent Electron versions, used by HTTP Toolkit to provide the desktop app shell that we use for native UI including file pickers, it's no longer possible to select inside a .app directory (i.e. any normal installed app) in the file picker. Instead, when you select the app, Electron searches the entire app directory for something that matches the mime type (a binary, in our case) and then uses that, which usually means it picks a random native library instead of the main executable, after freezing HTTP Toolkit for a while, and never successfully starts the target app.

Basically on Mac it was unusable and confusingly broken for the most common use case, so enabling it created more problems than solutions. It is still enabled on Windows & Linux.

Currently I don't have a long-term fix for this yet. I'm very open to doing so, but I don't have much time right now myself. PRs welcome! This would probably need some addition to our Electron desktop shell ([here](https://github.com/httptoolkit/httptoolkit-desktop/)) to implement a new file picker that _can_ pick binaries from within .app bundles, and to then trigger that from inside the UI ([here](https://github.com/httptoolkit/httptoolkit-ui/blob/0eaff10664bc86ff75cef4864c89415b52ed2a12/src/util/ui.ts#L64-L141)). Or some other solution that resolves this. The code that actually disables the button is [here](https://github.com/httptoolkit/httptoolkit-ui/blob/0eaff10664bc86ff75cef4864c89415b52ed2a12/src/model/interception/interceptors.ts#L275-L278).

**Comment by Geczy** [comment]
so it's disable only because of a file picker? any chance we can just manually input the file path via source, build, and run httptoolkit locally ?

**Comment by Geczy** [comment]
oh it worked perfectly, all i had to do was remove the disabling of electron on a mac. everything is being logged in the browser. this is magical

i'm on m1 btw

**Comment by pimterry** [comment]
Yep, it all works fine in a browser, if you run the components separately! It's just that in Electron it tries to use Mac OS's built-in file picker (which doesn't work for selecting application bundles like this) we can't disable that to use `prompt` because Electron has it disabled, so we need to build a custom file picker or prompt input UI and use that instead.

PRs for this are very welcome! In the meantime though, yes running the UI locally and un-disabling Electron interception will work in a browser. For anybody else who wants to do this, the local UI setup guide is here: https://github.com/httptoolkit/httptoolkit-ui/#contributing

**Comment by datenreisender** [comment]
> This would probably need some addition to our Electron desktop shell ([here](https://github.com/httptoolkit/httptoolkit-desktop/)) to implement a new file picker that _can_ pick binaries from within .app bundles, and to then trigger that from inside the UI ([here](https://github.com/httptoolkit/httptoolkit-ui/blob/0eaff10664bc86ff75cef4864c89415b52ed2a12/src/util/ui.ts#L64-L141)).

[Electron's `dialog.shoOpenDialog` supports a `treatPackageAsDirectory` property](https://www.electronjs.org/docs/latest/api/dialog#dialogshowopendialogbrowserwindow-options) which should make this possible on Electon's side. But with the description above I was unable to put this to use. 

Is there an example of how code from inside the UI triggers code in the Electron desktop shell that I can use to guide me while implementing this?

**Comment by pimterry** [comment]
> Is there an example of how code from inside the UI triggers code in the Electron desktop shell that I can use to guide me while implementing this?

Right now, there is no code that does this yet. I haven't investigated that much myself, but in theory there's a standard Electron pattern for sending messages between the two - I'd suggest researching the normal approach, then adding some methods to send & listen for messages in https://github.com/httptoolkit/httptoolkit-ui/blob/main/src/services/desktop-api.ts (currently the only logic there receives parameters from the shell through a very quick rough method - it never sends them) and then adding a little "listen for pick-directory message -> show open dialog -> send response message" loop in the desktop shell side.

You might be interested in https://github.com/httptoolkit/httptoolkit-ui/blob/main/src/services/ui-worker-api.ts and https://github.com/httptoolkit/httptoolkit-ui/blob/main/src/services/ui-worker.ts which uses postMessage between the UI and a background thread, with defined requests & responses types linked to individual operations by id, to solve a very similar problem. In theory I thin it could just be the same thing but via Electron's APIs.

**Comment by datenreisender** [comment]
Thanks, I will take a look at those places. 

I was looking for usage of `ipcMain` and `ipcRenderer`, since that is [the common Electron pattern I was aware of for communication between the UI and the desktop app](https://www.electronjs.org/docs/latest/tutorial/ipc). :-)

**Comment by pimterry** [comment]
Ah, yes that's the one! But no, not used anywhere yet as far as I'm aware.

**Comment by datenreisender** [comment]
With httptoolkit/httptoolkit-desktop#60 and httptoolkit/httptoolkit-ui#80 it is possible on macOS to select the files within an app bundle. 

But I don't know whether I am still doing something wrong, because it doesn't yet work completely for me: The Electron app seems to start, its icon starts bouncing in the dock, but then … it just disappears from HTTP Toolkit again, the icon continues to bounce and the app’s window never appears. Am I doing something else wrong?

**Comment by Geczy** [comment]
you can try proxyman if you need electron sniffing, for anyone

**Comment by pimterry** [comment]
Thanks @datenreisender! Great work, I'll look into those PRs and test everything out myself shortly.

Can you share the specific app you're testing against that's failing, and the version?

**Comment by datenreisender** [comment]
I tried it with the latest version of [nRF Connect for Desktop](https://github.com/NordicSemiconductor/pc-nrfconnect-launcher) from my employer. But I tried it only very briefly and will give it another try on Monday.

**Comment by datenreisender** [comment]
I don't know what I did wrong on Friday, but know I was able to start either Electron Fiddle or nRF Connect for Desktop from within HTTP Toolkit. 

One more thing I needed to fix was to upgrade mockttp to 3.7.2 in httptoolkit-server because of the issue described in https://github.com/httptoolkit/mockttp/issues/139. But with that in place, I now got it running nicely on macOS.

**Comment by pimterry** [comment]
This is now resolved, and Mac users can intercept Electron apps once again :smile:. Many thanks to @datenreisender for doing all the hard work to fix this!

As it requires an update to the native desktop components, you'll need to update the desktop app manually to see this, by downloading the latest version (1.13.0) from [httptoolkit.com](https://httptoolkit.com).

If you had HTTP Toolkit installed before, you'll also need to run the app once, wait 30 seconds, and then restart it before you'll see the button enabled, as you'll still have a locally cached version of the UI which may not update instantly.

Hopefully that resolves this neatly for everybody, do please reply here if it's still not enabled for you unexpectedly, or open a new issue if you run into any other kinds of Electron issues (or anything else).
