### ISSUE TITLE
[Bug]: Le module spécifié est introuvable

### ISSUE THREAD

**Issue by Gabriel-Isitech** [httptoolkit/httptoolkit#334]
### Repro steps

Open HTTP Toolkit:

Hit an error at start but work this morning: le module spécifié est introuvable

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11

### Error screenshot

![Capture d’écran 2022-09-23 223035](https://user-images.githubusercontent.com/78261440/192051854-ba405124-1edc-44d6-aeab-be539810e7e2.png)

**Comment by PolarLofy** [comment]
I'm having the same problem

**Comment by tareck** [comment]
I'm having the same problem

**Comment by Gabriel-Isitech** [comment]
> delete the folder C:\Users\t.fahos\AppData\Local\httptoolkit-server and restart httptoolkit
Work for me

**Comment by pimterry** [comment]
This was due to a server update that seems to have had some issues on Windows, sorry about that! I've now rolled back the release, I think this should resolve this for most people, but for anybody who updated already and keeps hitting this error, you can safely delete that directory (`C:\Users\<username>\AppData\Local\httptoolkit-server`) to revert that.
