### ISSUE TITLE
[Bug]: HTTP Toolkit hit an error

### ISSUE THREAD

**Issue by SomeGuyCalledBru** [httptoolkit/httptoolkit#335]
### Repro steps

When attempting to run HTTP Toolkit today, I'm randomly facing an error that tells me to raise an issue here. Seems to have happened after auto update to 1.10.2.
version 1.10.2, Windows 10 home 21H2

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10 home 21H2

### Error screenshot

![image](https://user-images.githubusercontent.com/98551819/192085879-20933854-364d-4086-865a-db81ea5cb627.png)

### Any other info?

error.log:
```
2022-09-24T07:22:20.783Z Error: specified module could not be found
2022-09-24T07:22:20.783Z //?/C:/Users/user/AppData/Local/httptoolkit-server/client/1.10.2/node_modules/node-datachannel/build/Release/node_datachannel.node
2022-09-24T07:22:20.783Z     at Object.<anonymous> (C:/Users/user/AppData/Local/httptoolkit-server/client/1.10.2/node_modules/node-datachannel/lib/index.js:2:25)
```

**Comment by lulavc** [comment]
![bug](https://user-images.githubusercontent.com/1395704/192087127-d459d747-d0be-4bea-bfdd-6b185f0954ee.JPG)

Same here. Every time it launches shows that same screen just like buddy issue mentioned on previous post.

Windows 10 Pro - 21H1 - 19043.1021



--- Launching HTTP Toolkit desktop v1.10.1 ---
INFO: Initialising UI (version a38d9e6daa6ea5856876bf0a38362b75b176cef3)
INFO: Account store created
INFO: UI store initialized
INFO: Proxy settings loaded
INFO: API store initialized
(node:8452) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
    Error: The specified module could not be found.
    \\?\C:\Users\lula\AppData\Local\httptoolkit-server\client\1.10.2\node_modu
    les\node-datachannel\build\Release\node_datachannel.node
    Code: ERR_DLOPEN_FAILED

**Comment by Alokkumar8** [comment]
same problem with me

**Comment by tareck** [comment]
delet the folder C:\Users\t.fahos\AppData\Local\httptoolkit-server

**Comment by Gabriel-Isitech** [comment]
@tareck work for me thanks !

**Comment by pimterry** [comment]
This was due to a server update that seems to have had some issues on Windows, sorry about that! I've now rolled back the release, I think this should resolve this for most people, but for anybody who updated already and keeps hitting this error, you can safely delete that directory (`C:\Users\<username>\AppData\Local\httptoolkit-server`) to revert that.
