### ISSUE TITLE
[Bug]: Sever crashed with: Error the specified module could not be found '(1)

### ISSUE THREAD

**Issue by xtekky** [httptoolkit/httptoolkit#337]
### Repro steps

When opening the deskop app, for some reason it crashed on startup, even if it always worked flawless before, I have checked my connection, restarted, reinstalled but the error still persists.

What can I do to find out what is causing the error ?

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11 on msi laptop

### Details of other apps/devices

None, failing on startup

### Error screenshot

![image](https://user-images.githubusercontent.com/98614666/192091740-3440123a-0514-4d04-8dbd-c7c04b63f4c4.png)

**Comment by pimterry** [comment]
This was due to a server update that seems to have had some issues on Windows, sorry about that!

I've now rolled back the release, I think that should resolve this, but if you've updated already and you're still hitting this error, you can delete the server update directory (`C:\Users\<username>\AppData\Local\httptoolkit-server`) to revert that.
