### ISSUE TITLE
[Bug]: configured rules could not be activated, so were reset to default

### ISSUE THREAD

**Issue by ghost** [httptoolkit/httptoolkit#345]
### Repro steps

1. open httptoolkit
2. put device to Sleep
3. wake up from sleep
4. change mock setting 
5. press save changes 

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11 22H2

### Error screenshot

![Screenshot 2022-10-08 150653](https://user-images.githubusercontent.com/10223927/194702724-b4967c05-3ca7-4df1-aa5e-5d84bc573b8d.png)

**Comment by pimterry** [comment]
Ah, interesting, yes that makes sense.

I think there's some internal logic that detects persistent disconnection and shuts down the internal proxy (which would then break the rule configuration here later) and I bet that that's being triggered by device sleep, and causing this problem.

It's going to take a little time to solve this nicely I think, but I'll look into it and see what I can do. In the meantime I think the only workaround is to exit HTTP Toolkit before putting your device to sleep.

**Comment by nutterthanos** [comment]
Still happens today

**Comment by nutterthanos** [comment]
> Ah, interesting, yes that makes sense.
> 
> I think there's some internal logic that detects persistent disconnection and shuts down the internal proxy (which would then break the rule configuration here later) and I bet that that's being triggered by device sleep, and causing this problem.
> 
> It's going to take a little time to solve this nicely I think, but I'll look into it and see what I can do. In the meantime I think the only workaround is to exit HTTP Toolkit before putting your device to sleep.

isn't that like the persistent websocket connection or something?

**Comment by pimterry** [comment]
> isn't that like the persistent websocket connection or something?

Yes, exactly. It's not clear why, but in some environments (but not all of them - I can't seem to reproduce it myself in testing) the websocket breaks and fails to reconnect after the machine comes back from sleep, and leaves the application in an internally broken state, which triggers this. In most of my testing meanwhile, the connection stops, but then reconnects just fine when the machine reboots.

I'm working on this now. To start with, this is now handled separately from broken rule saving, so that the app will immediately show a clear error and exit any time this happens (e.g. immediately after sleep, if it fails to resume OK. It won't just be quietly broken until you save a rule later, and it won't reset your rules when it exits - it'll just close as normal, so you can restart and keep going. It's still very inconvenient, but that should solve the immediate problem with people losing the unsaved rule configuration. 

I'm going to improve that UX, and investigate the underlying cause further now. If anybody can share more details about their device configuration (as much info as possible) and when exactly this happens, that would be very helpful.

**Comment by Pbmatch** [comment]
Hellowindows 10 22H2To always catch a bug, you need to: Create mock rules. We are not closing the application. Send the computer to sleep mode (start-shutdown-sleep mode). Then turn on the computer. Any save change to the mock rules causes this error. After that, through the task manager, close the http toolkit and turn off the process node.exe . And you can start it again. All rules will be lost. I'm already used to it, and I often close the http toolkit so as not to lose the rules.24.10.2024, 20:13, "Tim Perry" ***@***.***>:

isn't that like the persistent websocket connection or something?

Yes, exactly. It's not clear why, but in some environments (but not all of them - I can't seem to reproduce it myself in testing) the websocket breaks and fails to reconnect after the machine comes back from sleep, and leaves the application in an internally broken state, which triggers this. In most of my testing meanwhile, the connection stops, but then reconnects just fine when the machine reboots.
I'm working on this now. To start with, this is now handled separately from broken rule saving, so that the app will immediately show a clear error and exit any time this happens (e.g. immediately after sleep, if it fails to resume OK. It won't just be quietly broken until you save a rule later, and it won't reset your rules when it exits - it'll just close as normal, so you can restart and keep going. It's still very inconvenient, but that should solve the immediate problem with people losing the unsaved rule configuration.
I'm going to improve that UX, and investigate the underlying cause further now. If anybody can share more details about their device configuration (as much info as possible) and when exactly this happens, that would be very helpful.

**Comment by pimterry** [comment]
The above "configured rules could not be activated, so were reset to default" messages should no longer appear, and rules will not be reset, unless there's a real issue with the rules themselves. Instead in this broken-on-wake case you'll see a different explicit error (see #647) but your rules won't reset. I'm working on fixing that fully so there's no error at all - I'm going to close this to consolidate issues, but keep an eye on #647 for updates.

**Comment by Pbmatch** [comment]
Hi. I don't know after which update, but this bug hasn't appeared for a long time. Thank you very much for your work
