### ISSUE TITLE
[Bug]: "Error: unable to verify the first certificate" with valid website

### ISSUE THREAD

**Issue by andrechalella** [httptoolkit/httptoolkit#353]
### Repro steps

1. "Intercept a fresh independent Chrome window"
2. Try to browse to https://sistema.cursoh.com.br/lms/

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10

### Error screenshot

![Uploading http-toolkit-error.png…]()

### Any other info?

The application shows the error below in the request. However, Chrome navigates to that website regularly without a single complaint about the certificate, in many different devices.

>STATUS:` 502 Error communicating with upstream server
>
>This request was not forwarded successfully
>
>The upstream server has an untrusted HTTPS certificate, so HTTP Toolkit did not forward the request.
>
>By default unrecognized certificate authorities (CAs) are only accepted for localhost servers, but Pro users can trust additional CAs or disable HTTPS validation for a host entirely.`

**Comment by pimterry** [comment]
Hmm, seems there's something odd happening here then. I can reproduce this, and it does indeed work in the current Chrome release. It fails when connecting using curl though on my machine, with v7.68.0, or when using openSSL directly with `openssl s_client -connect sistema.cursoh.com.br:443`.

I think this is a configuration issue on that specific site, in some format that browsers can work around (by caching intermediate certificates from elsewhere) but which other tools (like HTTP Toolkit and others) cannot. You can test this by comparing the OpenSSL output from the command above with the output from the same command with `sectigo.com:443` (which uses the exact same certificate chain, but delivered correctly). There's clearly some missing certificates in the cursoh.com.br certificate.

More specifically, when running that command, I see:

```
> openssl s_client -connect sistema.cursoh.com.br:443
CONNECTED(00000003)
depth=0 serialNumber = 13.488.293/0001-40, jurisdictionC = BR, businessCategory = Private Organization, C = BR, ST = Rio de Janeiro, O = CURSO H EDUCACIONAL LTDA, CN = sistema.cursoh.com.br
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 serialNumber = 13.488.293/0001-40, jurisdictionC = BR, businessCategory = Private Organization, C = BR, ST = Rio de Janeiro, O = CURSO H EDUCACIONAL LTDA, CN = sistema.cursoh.com.br
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:serialNumber = 13.488.293/0001-40, jurisdictionC = BR, businessCategory = Private Organization, C = BR, ST = Rio de Janeiro, O = CURSO H EDUCACIONAL LTDA, CN = sistema.cursoh.com.br
   i:C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Extended Validation Secure Server CA
---
```

Compared to Sectigo:

```
openssl s_client -connect sectigo.com:443
CONNECTED(00000003)
depth=2 C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Extended Validation Secure Server CA
verify return:1
depth=0 serialNumber = 04058690, jurisdictionC = GB, businessCategory = Private Organization, C = GB, ST = Manchester, O = Sectigo Limited, CN = sectigo.com
verify return:1
---
Certificate chain
 0 s:serialNumber = 04058690, jurisdictionC = GB, businessCategory = Private Organization, C = GB, ST = Manchester, O = Sectigo Limited, CN = sectigo.com
   i:C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Extended Validation Secure Server CA
 1 s:C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Extended Validation Secure Server CA
   i:C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
 2 s:C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
   i:C = GB, ST = Greater Manchester, L = Salford, O = Comodo CA Limited, CN = AAA Certificate Services
 3 s:C = GB, ST = Greater Manchester, L = Salford, O = Comodo CA Limited, CN = AAA Certificate Services
   i:C = GB, ST = Greater Manchester, L = Salford, O = Comodo CA Limited, CN = AAA Certificate Services
---
```

Both are signed by the "Sectigo RSA Extended Validation Secure Server CA" certificate, but Sectigo (and presumably everybody else) includes that certificate in the chain that they send to clients when they connect, while this site skips it and only sends the final certificate without the chain (which won't work for many clients, including browsers if they don't already have it cached).

There's more background on this issue here: https://nginx.org/en/docs/http/configuring_https_servers.html#chains.

Unfortunately this isn't something HTTP Toolkit can fix - that server is working incorrectly, and they should fix it. It is possible to connect to remote servers with broken TLS configurations like this with HTTP Toolkit, but it requires Pro: you can go into the Pro settings, and whitelist a hostname there directly, and that will skip the certificate validation for that hostname, which will neatly avoid the issue.

That's just a workaround though - the real problem here is that the server is not set up correctly.

**Comment by andrechalella** [comment]
That is some great work you did there. I thoroughly appreciate it!
