### ISSUE TITLE
[Bug]: Get pro features back by changing date

### ISSUE THREAD

**Issue by FaArIsH** [httptoolkit/httptoolkit#354]
### Repro steps

after subscription expires change the date (if subscription expired on 1st November than change to October) and restart the app

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11 22H2

**Comment by pimterry** [comment]
:laughing: good find, thanks @FaArIsH! I'm not sure this counts as a serious bug, but thanks for reporting it anyway, I'll look at ways to fix that.

I expect in most cases setting your date significantly off the real date will break many things anyway - e.g. for many HTTPS certificates you'll start to run into problems because the certificates will have been issued after the 'current' date, so if you change more than a couple of days then HTTPS traffic will start to break in all sorts of ways. Similarly you'll run into problems intercepting other devices (like phones) because HTTP Toolkit's certificate dates won't match their clocks.

**Comment by FaArIsH** [comment]
yes not a serious bug. 
I have been using since  my subscription expired in October 9 . the jwt token still contains subscription_expiry key so its still working and i did not face any problem yet.  I m using to intercepting mobile app traffic and its working without any problem also after http toolkit opens i can change the date to current date and it will stay in pro mode for 5 minutes

**Comment by pimterry** [comment]
Haha, neat, yes that makes sense! I think I've found a solution so I'm going to add some checks to make this a bit stricter later today, which will block this so just updating your clock won't work any more.

I really appreciate you reporting this though - I've just added 3 month free Pro on your account to say thanks :+1:
