### ISSUE TITLE
Getting Encrypted data

### ISSUE THREAD

**Issue by AshishP1112** [httptoolkit/httptoolkit#357]
### Repro steps

we are using memu emulator to open the app and other side we are using http toolkit in our local system. we are try to capture traffic using Android Device via ADB. And in this we get encrypted payload of request and data of google api https://clients4.google.com/glm/mmap/api

### How often does this bug happen?

Sometimes

### The desktop OS you're using

Window 11

### Details of other apps/devices

SmartPay Rewards_5.7.1_Apkpure.apk

getting encrypted post content in http toolkit while capture traffic.

### Error screenshot

<img width="520" alt="image" src="https://user-images.githubusercontent.com/112385154/202616837-e5741658-ccb9-4592-8d32-1d9f395c43fc.png">

### Any other info?

We want decrypted request and data while capture traffic using http toolkit and it will be helpful for us If we get decrypted data.

**Comment by pimterry** [comment]
Hi @AshishP1112. That data doesn't really look encrypted: the initial part clearly contains real text like `com.cumberlandarms.mobile` (definitely not encrypted) and the subsequent data has a clear structure - it doesn't look like random data, which real encrypted data would.

That's good though, because if this was encrypted then it would definitely be impossible to decrypt it without some secret key. I think in reality this is just data encoded in some binary format (see https://stackoverflow.com/questions/4657416/difference-between-encoding-and-encryption for more info on the difference). It might be compressed, or defined in a specific structure for easy processing, or anything else.

Do you have any idea what format this is? HTTP Toolkit certainly could support more data formats, but it needs to have support for the specific format that's used, and to know which format the data is in either explicitly or via some clear mechanism to guess it. For example, HTTP Toolkit takes raw image data and shows the actual image (using the `content-type` header to detect the image format) and takes JSON data and shows the full JSON structure (using the headers, but also checking for parseable plain-text response bodies that start with `{` or `[`). It's not possible to magically turn arbitrary binary data into human-readable data without knowing the format, so you'll need to work that out before we can look at how it might be supported.
