### ISSUE TITLE
public ip on VPS server

### ISSUE THREAD

**Issue by nhokpro** [httptoolkit/httptoolkit#360]
I want to set up the toolkit as a server on my vps
But I can't find the settings to change from localhost (127.0.0.1) to the actual public IP of the vps

---

_Does this affect you too? Click the :smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
I'm assuming you've closed this because you've found a workaround?

In general, if you run HTTP Toolkit remotely right now you'll have to manually configure clients using your VPS's IP & proxy port. This configuration isn't officially 'supported' but I think that should work just fine.

Out of interest, can you tell me what kind of client you're using, and how this VPS will be useful to you?

In future I'm planning to eventually look at #288 to support this properly - so that all paying users would automatically have a public address they could use like this - but there's a lot of details to work out there. Any info you can share about your use case to help design that would be very helpful :smile:.

**Comment by ibrah3m** [comment]
@pimterry Hi I would love to get some guidance in this.
the usage is to setup a proxy at vps that can mock either the request/response and manipulate the data of the request.

so I think it's easy to make port forwarding at VPS but I couldn't find anything from Android side 
I assume we should
1- install certificate
2- setup proxy

**Comment by pimterry** [comment]
@ibrah3m, yes - that's exactly it! Both steps are a bit more complicated than they sound though, because:

* Android proxy configuration is quite awkward: AFAIK only applies to wifi, and you generally need to manually enter and delete details in the UI.
* Not all app traffic will listen to the system proxy settings anyway (many things - e.g. almost all Flutter apps - do low-level networking that ignores this)
* In non-rooted Android, you can't trust a CA certificate at all for most apps (only for apps that opt in - generally Chrome, and any apps that have explicitly enabled debugging options)

How to work around that depends on your use case. If you're using HTTP Toolkit, most of that is done for you for the tractable cases, but there are still challenges particularly on non-rooted devices.

For more information on how HTTP Toolkit does this internally, there's a detailed article on how Android certificates work and how HTTP Toolkit installs its own [here](https://httptoolkit.com/blog/intercepting-android-https/) and more info on using the VPN APIs to solve the proxy problem [here](https://httptoolkit.com/blog/inspecting-android-http/). Alternatively, depending on your use case, you might be more interested in the Frida scripts [here](https://github.com/httptoolkit/frida-interception-and-unpinning) which provide an alternative approach (but do require Frida - which in turn implies either a rooted phone or debuggable app).

For building custom proxies like this in general, you may well be interested in [Mockttp](https://github.com/httptoolkit/mockttp/) which is the internal HTTPS-intercepting proxy from HTTP Toolkit (without the setup tools, the UI, etc) as a standalone scriptable Node.js library. Very useful for building headless scripted intercepting & rewriting proxies. Getting started guide is here: https://httptoolkit.com/blog/javascript-mitm-proxy-mockttp/

**Comment by ibrah3m** [comment]
@pimterry  thanks alot , yes I'm interested in mockhttp I'll make sure to read all of this article's. and I my case I'm always gonna use rooted device,And I know about the certification and we should force the app to use system certificate for ssl unpinning.
I'm really thankful 🌟
