### ISSUE TITLE
[Bug]: Python Requests export not working

### ISSUE THREAD

**Issue by yhchong** [httptoolkit/httptoolkit#361]
### Repro steps

I have followed the guide on certificate pinning (https://httptoolkit.com/blog/frida-certificate-pinning/) and was able to see the API requests. However, the python request export is getting through with a 403 response. I am not quite sure why and the other exports also returns 403.

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10

### Details of other apps/devices

Android Emulator API 29, Android 10.0 | x76

### Error screenshot

![image](https://user-images.githubusercontent.com/13570016/204107285-af454541-6574-4f41-8ec3-d1512aa3d3c4.png)

### Any other info?

APK: https://drive.google.com/file/d/1mKTlyZ17kNN_8G88aK02G5eGKdbLEgx6/view?usp=sharing

**Comment by pimterry** [comment]
Hi @yhchong. Unfortunately this probably isn't actually an issue with HTTP Toolkit or with the code of the Python export - this is usually caused by a server that is actively detecting and blocking requests from clients like Python, even though the request is valid and would work fine.

The most common mechanism for this is [TLS fingerprinting](https://fingerprint.com/blog/what-is-tls-fingerprinting-transport-layer-security/) which allows a server to detect the type of software that's making a request (regardless of the HTTP content of the request) and block requests from software it considers suspicious (normally anything that looks bot-like and automated, as opposed to normal browser/app client usage).

Notably Cloudflare offers built in anti-bot tools that do this, and I can see the response there is coming from Cloudflare, so that's probably your problem.

Defeating this is a bit tricky. There are tools specifically designed to help with this like https://github.com/apify/got-scraping which carefully emulate the real TLS fingerprint and other HTTP fingerprinting details to avoid these kinds of blocks. On other option might be to use any client you like with a [Mockttp proxy](https://github.com/httptoolkit/mockttp). Mockttp power the internals of HTTP Toolkit, and carefully emulates normal browser fingerprints (which is why the request isn't blocked when its passed through HTTP Toolkit) so if you send a browser-like request through that as a proxy then it will _usually_ avoid blocks like this. This guide might also be useful: https://httptoolkit.com/blog/javascript-mitm-proxy-mockttp/

Nothing is guaranteed here I'm afraid though and there is no right answer - this is a cat & mouse security game that changes frequently.
