### ISSUE TITLE
Edit and resend feature

### ISSUE THREAD

**Issue by nhokpro** [httptoolkit/httptoolkit#367]
The feature allows users to resent the request by configuring simulate to firefox.

![image](https://user-images.githubusercontent.com/31965576/206975808-de13504a-e307-4801-bf0d-49fa03c96f3a.png)

**Comment by pimterry** [comment]
This is definitely a good suggestion that I'd love to get to. If you're interested, contributions are very welcome!

I am going to close this issue though, because it's already tracked [here](https://github.com/httptoolkit/httptoolkit/issues/48). You can +1 there to vote for that.

I'll copy that image over though, that's a good example!
