### ISSUE TITLE
[Bug]: No possible to connect with some sites 

### ISSUE THREAD

**Issue by pywallet-cli** [httptoolkit/httptoolkit#380]
### Repro steps

It is not possible to connect with www.ticketmaster.com or www.ticketmaster.es with the certificate

### How often does this bug happen?

Every time

### The desktop OS you're using

Android

**Comment by pimterry** [comment]
Hi @pywallet-cli, I've just tested and I can load ticketmaster.com in a browser on my Android device.

I suspect you're talking about connections from an app? It would be useful to know which app, just for reference. Regardless though I think this is probably an issue caused by certificate pinning. There's more details on how this works and how to beat it here: https://httptoolkit.com/blog/frida-certificate-pinning/

If that's not what's happening, it would be helpful if you could share more info, including the full steps to reproduce this issue, so I can test it myself and investigate further.
