### ISSUE TITLE
Response Transformation guidelines and features

### ISSUE THREAD

**Issue by ptrckSTL** [httptoolkit/httptoolkit#383]
Response Transformation is super helpful but it's unclear how it actually works.
At first I thought it wanted a [JSON Patch schema](https://jsonpatch.com/) to edit incoming JSON (which would maybe be a good approach?).
Instead, when I use this feature I input the entire mocked response, then remove objects that I *don't* want to be edited. That seems to work but I don't know if this is the best practice or not because there's no documentation around how this feature actually works. It would be super nice if there was a way to do some kind of wildcard matching for array objects, like
```
"array": [
          {
            *:{
              "property":false
               }
          }
    ]
```

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @ptrckSTL, thanks for getting in touch.

The JSON update does simple patching only: it merges the input with the body recursively, so that everything specified in the input overwrites that single part of the original content, and everything unspecified is left as is. The code is [here](https://github.com/httptoolkit/mockttp/blob/918dc96e4d6da880daf4799770c0024adbbd131e/src/rules/requests/request-handlers.ts#L516-L525) - it's effectively Lodash's [_.merge function](https://lodash.com/docs/4.17.15#merge), but you can also explicitly set `x: undefined` too to remove field `x` (note that undefined isn't representable in JSON).

That means it's quick & convenient for tiny patches, but yes it doesn't support complex changes like "set property: false for every element in this array". It's hard to come up with any one single format that can represent all possible changes like this, so the current implementation errs towards to common quick & easy case, rather than maximum power.

If you're looking to do more complex transformations, you're probably looking for #37 - arbitrary scripting in mock rules. Once that's available, you'll be able to add custom logic to precisely define any more complex transformation you might want. This isn't available in the UI yet, but everything required is implemented internally. If this is important for your use case, you can use that yourself now by using [Mockttp](https://github.com/httptoolkit/mockttp/) (HTTP Toolkit's HTTP-handling internals) as a standalone library to build a custom proxy directly, with any arbitrary rewriting logic you like. There's a getting started guide for that here: https://httptoolkit.com/blog/javascript-mitm-proxy-mockttp/

I'll leave this open anyway though. Regardless of the specific use case, you're totally right that this isn't properly documented. I'm planning to do a sweep through the docs soon-ish to get them up to date, and I'll make sure I include this en route (or in the meantime PRs to the docs are welcome, they're here: https://github.com/httptoolkit/httptoolkit-website/tree/main/src/docs)

**Comment by adamoutler** [comment]
I can't figure out how to patch a simple json without wiping everything out. I tried
* mucking around: nothing
* JSON PATCH standards: nothing
* searching : nothing
* asked chatGPT for possible alternatives: nothing
All I can do is either make it wipe out the entire object I'm trying to patch or add new keys into the existing objects.

I even fed ChatGPT and Bing that linked code for lodash and it gave me something that did nothing but add extra keys.   I've got zero clue how to make this work. 

as an example:
```
{ "foo":[
    "bar":{
        "baz": 3,
        "buzz":4
     }
]}
```
When i try to apply any patch to `baz` or `buzz` it will wipe out the other one.  What do I need to do here?

**Comment by pimterry** [comment]
Hi @adamoutler - I think the previous comment covers the current state: these rules support merging of objects/arrays/etc and targeted field deletion, but not more complex modifications. These are designed to make it easy to handle simple cases (replace/remove specific path values etc) but don't offer maximum flexibility.

For your specific example, it's not clear whether the patch you want is possible within that model, because the text above is not valid JSON (your array contains a `"bar": {}` key-value syntax - unclear if there's missing braces, or the whole thing should be an object, or something else?). Happy to provide pointers if you can share a valid JSON example though.

Alternatively, you'll be glad to hear that JSON patch support is now on the way, and should be live within a couple of days. If your transform is representable with JSON patch and you can wait a tiny bit longer then hopefully that'll work nicely for you.

**Comment by pimterry** [comment]
JSON patch support is now live:

![Screenshot from 2024-07-03 19-27-28](https://github.com/httptoolkit/httptoolkit/assets/1526883/b53cb24c-2bbc-44ff-81d1-d0d550e3d44c)

HTTP Toolkit will update in the background next time you start it, and the following time, you'll be able to pick this as a request or response body option within a transform rule.
