### ISSUE TITLE
[Bug]: HTTPToolkit not actually sending modified requests from mock/rewrite

### ISSUE THREAD

**Issue by nutterthanos** [httptoolkit/httptoolkit#388]
### Repro steps

1. Open Desktop App
2. Click on Mock
3. Add a rule to pause request to manually edit it
4. Modify request to your desire

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11 22000.1455

### Any other info?

I think this effects Windows 10 Versions too and maybe Mac but i can't test on Mac.

this is just a recording of the bug in action
[recording.zip](https://github.com/httptoolkit/httptoolkit/files/10754119/recording.zip)

**Comment by pimterry** [comment]
That's an interesting recording format! I haven't seen that before. Unfortunately it doesn't seem to be well supported and I can't really view it I'm afraid. The only tool I can find that can open it on Linux is Chrome, and that refuses to load the images, just the text descriptions, which isn't very helpful.

That said, I suspect this is just UX confusion. How do you know the request isn't being modified? If it's because you're still seeing the original content in HTTP Toolkit, that's expected - HTTP Toolkit always shows the original content that the client sent, and the final content the client receives. It doesn't show the upstream request & response data, even if that differs. It's always the client's perspective.

Most of the time that's what you want, though I see how it can be confusing in cases like this. Extending the UX there to explicitly show both client & server perspectives is tracked already here: https://github.com/httptoolkit/httptoolkit/issues/250.

If that's not what's happening, and you're editing the request but you can see (e.g. in server logs) that the server is not receiving your modifications, please do share more information, but I think it needs to be in video form or clear steps I can reproduce for myself. I've just tested manually, and request editing does seem to be working for me.

https://httpbin.org/anything might be useful for testing - that will directly echo the request content back to you so you can see the server's POV.

**Comment by nutterthanos** [comment]
i could redo the recording in an format that supports linux if you want

**Comment by nutterthanos** [comment]
yeah i just check with httpbin.org/anything
it does go through as the modified request
i guess just UX confusion
