### ISSUE TITLE
[Bug]: Http Toolkit not intercepting traffic from Android to 10.0.2.2 (localhost)

### ISSUE THREAD

**Issue by Jay1305** [httptoolkit/httptoolkit#398]
### Repro steps

First of all thank you very much for creating a great tool for developers! It really helps :)

Environment Information
1. Mac Ventura
2. Android emulator
3. HTTP Toolkit 1.12.3

I have below issue to mention.
1. Open HTTP Toolkit on host mac machine
2. Run local api on localhost
4. Click Android device via ADB. This connects to my emulator and shows that APK got installed and user and system trust are enabled.
5. It also starts showing requests under View of HTTP Toolkit. Also shows correct request/response for https://amiusing.httptoolkit.tech/
6. Open chrome in the emulator
7. Go to google.com/youtube.com etc. It gets captured correctly.
8. Try to go to 10.0.2.2
9. HTTP Toolkit captures only request and then it just times out with error ETIMEDOUT in the response.
10. Stop interception from toolkit apk by clicking on "Disconnect"
11. Try to go to 10.0.2.2 and it shows the response in chrome.

![image](https://user-images.githubusercontent.com/31636584/227825656-d13616c8-89b6-43c4-a1f0-33fb2ec4b0bc.png)

![image](https://user-images.githubusercontent.com/31636584/227825606-cd4bb935-c1dc-4658-a52e-0feda40bfdfb.png)

![image](https://user-images.githubusercontent.com/31636584/227825692-3232abe6-ad2c-450d-bd4f-65249bf57048.png)

Cannot share screenshot of 10.0.2.2 response received from browser but it shows valid response if I disconnect apk.

Thanks again for reading this issue!

### How often does this bug happen?

Every time

### The desktop OS you're using

Mac OS

### Error screenshot

![image](https://user-images.githubusercontent.com/31636584/227825606-cd4bb935-c1dc-4658-a52e-0feda40bfdfb.png)

**Comment by pimterry** [comment]
Ah, yes, interesting. That makes sense, but it's difficult to fix automatically... Although for most Android emulators 10.0.2.2 does indeed resolve to the host's localhost, HTTP Toolkit can't easily know that for _all_ cases. The best guess we have available is to try and resolve the same address on the host computer (normally a good bet) but that doesn't work in this case.

Is it possible to change the application in question, to use a different hostname? If so, you could connect to `emulator-host.test` and then map that to localhost on your computer (with a Hosts file) or use any other address (like your computer's own IP) that will reach your computer on your local network.

Alternatively, if you're good with networking configuration then if you set up a route so that `10.0.2.2` on your host computer maps acts as a loopback address then that should work without modifications (I think that's possible, but I'm not sure how to do it myself).

Lastly, if you use HTTP Toolkit Pro you can create rules to redirect traffic automatically, so you could add a rule to redirect `10.0.2.2` to `127.0.0.1` and everything should work correctly. You can test this out manually even without Pro by using a request breakpoint and then editing the request URL from 10.0.2.2 to 127.0.0.1 (or anything else you like).

**Comment by Jay1305** [comment]
Thanks a lot @pimterry for your reply and explanation on why that is happening!

I think I have got on the root cause on why that is not showing up and I will dig into on how I can setup host to redirect from 10.0.2.2 to localhost per your other given options.

Yes, by manually editing the request url from 10.0.2.2 worked well from toolkit. 

I could have opted for pro if it would have to buy single time purchase instead of monthly license ;). But honestly thank you for making great tool that is benefiting developers around the world.
