### ISSUE TITLE
[Bug]: httptoolkit will miss some requests for a flutter app

### ISSUE THREAD

**Issue by hpp0hpp** [httptoolkit/httptoolkit#408]
### Repro steps

I found httptoolkit doesn't forward some of the request from flutter app. 
Like this one: [downloadlink](https://wwvl.lanzout.com/iJ7zK0s1ug1c)

maybe they have been configured to not respect the VPN and go through directly. 

### How often does this bug happen?

Every time

### The desktop OS you're using

win 11

### Details of other apps/devices

for this app, httptoolkit cannot capture the request started from flutter with host http://106.53.113.42:6666

but in httpcanary I can see those requests are captured 

it's strange, maybe some thing missed during the forward. 

### Error screenshot

![057f23b550ba7d5000b721814677efb](https://user-images.githubusercontent.com/54829297/231189211-e8158b1c-2edb-45ca-94db-5a5b0740e3a3.jpg)

**Comment by pimterry** [comment]
Android interception works using the VPN app in two ways:

* Configuring the device's proxy setting, which will redirect traffic from all well-behaved apps
* Manually rewriting individual packets sent to recognized TCP ports, to forcibly redirect them

I believe that Flutter ignores the device proxy settings, and so the first method doesn't work. That means that only traffic on recognized ports will be intercepted, and 6666 and 88 aren't in that list. To fix this, you can add more ports to the list using the ports button that's shown in the Android app while it's connected.

Be aware that adding any ports which are used for non-HTTP traffic there will effectively block traffic on those ports, since HTTP Toolkit will fail to parse it and will reject it.

Does that work for you?

**Comment by hpp0hpp** [comment]
Thank you for explaining, this worked.
