### ISSUE TITLE
[Bug]: HTTP Toolkit hit an error spawn C.:lUserstShree\AppData\LocalMic....PythonSoftwareFoundation.Python.3.11_qbz5n2kfra&pO ENOENT. Please file an issue at github.com/httptoolkit/httptoolkit.

### ISSUE THREAD

**Issue by roshan-sirohi-au19** [httptoolkit/httptoolkit#410]
### Repro steps

HTTP Toolkit hit an error
spawn
C.:lUserstShree\AppData\LocalMic....PythonSoftwareFoundation.Python.3.11_qbz5n2kfra&pO
ENOENT.
Please file an issue at github.com/httptoolkit/httptoolkit.

I am getting this error please help

### How often does this bug happen?

Every time

### The desktop OS you're using

windows

**Comment by pimterry** [comment]
Hi @roshan-sirohi-au19, this suggests that your shell is not correctly configured on Windows. HTTP Toolkit is trying to launch its server (an internal component) and when trying to do so with the default command line configuration, the command line itself (not the server) is failing to start because the configured path doesn't even exist.

This normally means you have the [COMSPEC](https://en.wikipedia.org/wiki/COMSPEC) environment variable set incorrectly. Can you check that? On most machines this should be set to something like `C:\Windows\system32\cmd.exe`. If you change that in your system environment variables settings and restart HTTP Toolkit then everything should work correctly. Having this set wrong may well have broken various other parts of your system too, so it's worth fixing.

Does that work for you?
