### ISSUE TITLE
[Bug]: Failing to load

### ISSUE THREAD

**Issue by skyronic** [httptoolkit/httptoolkit#412]
### Repro steps

I am unable to get the desktop app to load, I have also tried running my own server and using `https://app.httptoolkit.tech/`

The server starts fine but the UI version 559d4068476ed964a9c5bd52451f319956776d7b breaks because:

```
Reporting error: Error: Failed to initialize application
    at index.tsx:148:13
    at Generator.next (<anonymous>)
    at a (app.js:3393:1034) 
```

### How often does this bug happen?

Every time

### The desktop OS you're using

macOS 12, M1

**Comment by pimterry** [comment]
Hi @skyronic, can you share your app logs? You can find them in the menu under Help -> View HTTP Toolkit logs. That should have some clues about what's failing here.

**Comment by skyronic** [comment]
Certainly - here it is!

[last-run.log](https://github.com/httptoolkit/httptoolkit/files/11264645/last-run.log)

**Comment by pimterry** [comment]
Hmm, that's very unusual. From all that, I can see:

* The server starts up successfully and quickly
* The UI starts initializing successfully
* The accounts, UI, proxy, API & rules UI stores all initialize OK
* The interceptor UI store never initializes (there's no "Interceptor store initialized" in the logs)
* UI startup times out waiting for this final step

I think this means that for some reason the 'detect what interceptable apps are available locally' step is not completing, but I've never seen that before.

If you open the developer tools (View -> Toggle developer tools) and then reload the UI (View -> reload) you'll be able to see in the Network tab all the requests HTTP Toolkit makes internally to start up.

There'll be a series of `127.0.0.1` requests, and one will be a POST request containing JSON including `"operationName": "getInterceptors"`. Can you see that? Is it by any chance still pending, and never returning a response? That would do this.

Hard to say why that wouldn't complete though. On the server side, there's supposed to be a 1 second [timeout](https://github.com/httptoolkit/httptoolkit-server/blob/main/src/api-server.ts#L110) that should ensure this always returns (although I see now that actually [one small case](https://github.com/httptoolkit/httptoolkit-server/blob/0e089703ac26716c073c4826ee5fb83beb0229ab/src/api-server.ts#L204-L211) isn't covered by that).

By any chance do you have Docker installed? Or have you recently uninstalled it or similar, so that trying to test for Docker connectivity would never complete? That's the one example I can see where this would happen.

**Comment by skyronic** [comment]
Hi @pimterry

Thank you for taking the time to take a closer look.

You were right - Killing my docker engine fixed the issue! I don't know what's wrong with the docker on my laptop but I'm happy to provide more details.

Closing the issue for now.

**Comment by pimterry** [comment]
Was your Docker working normally otherwise? Had any other issues with it recently?

Can you start Docker up again, run `docker info` on the command line and share the output? (You might want to redact anything personal in there first, I'm not sure if that exposes usernames or other config).

Looking at the code linked above, I certainly can see how HTTP Toolkit will currently fail to finish detection if Docker is non-responsive for some reason, so that's a nice clear bug that I can fix easily enough. But if HTTP Toolkit is failing to detect Docker correctly while it's working correctly then there's something else weird going on, and I'm not sure what that is.

**Comment by skyronic** [comment]
I have been having issues with docker desktop. Unfortunately I haven't been able to reproduce the exact issue.

Glad to hear that HTTP Toolkit can be more defensive when docker isn't responding properly. Look forward to the upcoming release. If I can re-create the docker failure I'll definitely test it with a future release.

Offtopic - your product is absolutely fantastic. I've been a user of Charles for a long while but your Android integration was incredibly seamless and worked great out of the box.

**Comment by pimterry** [comment]
Ok, thanks. That sounds like this is indeed a "handling broken docker" problem rather than a general docker integration issue. That's great, that's much easier to fix :smile:.

Thanks for the positive feedback too, glad HTTP Toolkit is working so well for you! Do let me know if you run into any other issues at all.
