### ISSUE TITLE
[Bug]: Sending two requests with the rust library reqwest makes the second fail

### ISSUE THREAD

**Issue by tyilo** [httptoolkit/httptoolkit#425]
### Repro steps

- Create a Rust project that sends two requests using [reqwest](https://docs.rs/reqwest/latest/reqwest/):
```
$ cargo new reqwest-test
$ cd reqwest-test
$ cargo add reqwest
$ cargo add tokio -F full
```

Edit `src/main.rs`:
```rust
use reqwest::Client;

#[tokio::main]
async fn main() {
    let client = Client::new();

    for _ in 0..2 {
        let response = client.get("http://example.org/").send().await.unwrap();
        println!("Response: {:?}", response.status());
    }
}
```

- Run the binary and see that it makes two successful requests:
```
$ cargo run --release
...
Response: 200
Response: 200
```

- Open the desktop app
- Run the binary with `HTTP_PROXY` set and see that the second request fails:
```
$ HTTP_PROXY=http://127.0.0.1:8000 cargo run --release
Response: 200
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("example.org")), port: None, path: "/", query: None, fragment: None }, source: hyper::Error(IncompleteMessage) }', src/main.rs:8:71
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### How often does this bug happen?

Often

### The desktop OS you're using

Arch Linux

### Error screenshot

![image](https://github.com/httptoolkit/httptoolkit/assets/568036/edd0a19a-3175-40d2-b384-b3e6c8409da8)

### Any other info?

I also tested the binary with [mitmproxy](https://mitmproxy.org/) to rule out that the possibility that the error is in reqwest's handling of HTTP proxies.
It works fine:
```
$ mitmproxy
```

In another terminal:
```
$ HTTP_PROXY=http://127.0.0.1:8080 cargo run --release
...
Response: 200
Response: 200
```

**Comment by pimterry** [comment]
After further investigation, I think this is very difficult to patch out reliably, and it will be fixed very cleanly by updating to Node 20, so it's going to have to wait until we can do so (which I believe is currently just blocked on Node merging this PR: https://github.com/nodejs/node/pull/45190). Hopefully that won't be a big problem as this current behaviour has been the case for quite some time already without causing many notable issues (I suspect because of the very precise timing & conditions required for this to fail, and/or because many HTTP clients seem to be resilient to connection closures in cases like this, and so quietly retry requests if required anyway).

I'll keep this open until Node is updated to v20 and this can be fully resolved, hopefully we'll get there soon! In the meantime, any of the workarounds above can all be used to handle this issue. For the v20 workaround case, you can do that manually by [running the server locally](https://github.com/httptoolkit/httptoolkit-server/#contributing) - note that without the above Node fix though, some Android traffic using unusual ALPN requests may be unexpectedly rejected, e.g. some gRPC clients etc.

Sorry I don't have a more satisfying answer here, but I think this is the best route for the long-term. I'd rather not try to add in a funky patch that would be problematic in itself given that this is going to be resolved properly soon regardless.

**Comment by pimterry** [comment]
The migration to Node v20 has now been completed, including the fix referenced above and some others, and this issue appears to be entirely resolved - running the given code in the latest version of HTTP Toolkit reliably prints `Response: 200` twice, and all requests appear successful.

Thanks again for reporting this @tyilo, do let me know if you see any more issues in future.
