### ISSUE TITLE
Bluestacks Certificate Installation

### ISSUE THREAD

**Issue by LaserSlime** [httptoolkit/httptoolkit#443]
So basically the problem is that installing certificates in bluestacks isn't possible because android forces you to set up a display unlock mechanism for it. This doesn't work since bluestacks removed display unlock mechanisms. It is still possible to manually install certificates with root though, like with for example [Root Certificate Manager](https://play.google.com/store/apps/details?id=net.jolivier.cert.Importer). 

What I'm asking for is a way to just save the certificate somewhere so you can use Root Certificate Manager to install it or maybe just integrate Root Certificate Manager's functionality directly into the app.
---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by AlexNaga** [comment]
Try enabling ADB in bluestacks and choose the _"Android device via ADB"_ option. It should automatically setup the certificate for you.
![image](https://github.com/httptoolkit/httptoolkit/assets/14061533/0cbd6dbf-07e3-4734-ab52-80b74f85e416)

**Comment by LaserSlime** [comment]
That's exactly what doesnt work. Installing the certificate requires me to set a screen lock mechanism, which doesnt work in bluestacks.

**Comment by LaserSlime** [comment]
![Screenshot 2023-07-01 192232](https://github.com/httptoolkit/httptoolkit/assets/76707643/224f635e-0201-4b64-94f7-994c3d1824a5)
After clicking this I'm asked to set a pin or a password:
![Screenshot 2023-07-01 192331](https://github.com/httptoolkit/httptoolkit/assets/76707643/f2c65683-f066-4af5-918a-92ffd5b1d939)
Clicking ok results in a little bit of screen glitching and a text saying "The certificate is not installed."

**Comment by AlexNaga** [comment]
And you're sure you got root enabled?
![image](https://github.com/httptoolkit/httptoolkit/assets/14061533/1cf1e03a-e75f-40b4-ad89-2b2f81dbeb86)

After enabling ADB in Blustacks, have you connected to it from your computer? `adb connect localhost:5555`

After that, can you see the device after typing `adb devices` ?

The command should return
```
List of devices attached
localhost:5555  device
```

Also, do _not_ try and connect in HTTP toolkit from your emulator, but rather click on the "Android device via ADB" from your computer.
![image](https://github.com/httptoolkit/httptoolkit/assets/14061533/4526e293-2cba-4063-8edc-d0841a79187a)


As it will inject the certificates for you.
![image](https://github.com/httptoolkit/httptoolkit/assets/14061533/af268e64-9f6c-4a7b-8976-a9a20b4f5409)

**Comment by LaserSlime** [comment]
Yes I am rooted and have connected to adb using the command prompt. The problem only lies in the certificate. To install a user certificate on any android device you have to set a pin or password. It's not possible to do that on bluestacks since the respecting menus are disabled so certificate installation will fail.
And even if I use other apps to install the certificate as a system certificate it still want's me to install the user certificate. (Or maybe I'm just doing it wrong, like I said I used Root Certificate Manager if you know a better way please tell me)

**Comment by AlexNaga** [comment]
Yeah, not sure what you're doing wrong as I have been able to get this to work with two different computers and both using Blustacks 10.

**Comment by pimterry** [comment]
Hi @LaserSlime, this definitely means your root setup isn't working with HTTP Toolkit for some reason. The certificate install process on the device only happens if HTTP Toolkit hasn't been able to do it automatically via ADB previously, and in this case it will only install a 'user' (not system-level) certificate anyway, which probably isn't what you want.

Can you share your HTTP Toolkit logs? They're available via Help -> View HTTP Toolkit logs. They reset each run, so you'll want to start the tool, redo ADB interception setup to reproduce the issue, and then get the logs. That should have the details of the setup process and what's going wrong.

**Comment by LaserSlime** [comment]
[last-run.log](https://github.com/httptoolkit/httptoolkit/files/11936712/last-run.log)

**Comment by pimterry** [comment]
Ok, that's very interesting - it appears here that the root access did work, and the system certificate was actually installed correctly! But then for some reason the Android app isn't seeing it...

Can you try:

* Looking in the list of system certificates on the device (Settings -> Security, Encryption & Credentials -> Trusted Credentials -> System) and see if 'HTTP Toolkit CA' is listed in there?
* On your computer, running `adb shell`, then `whoami` (should return 'shell', not 'root') and then sharing the output here from:
  * `getprop ro.build.version.release`
  * `mount`
  * `ls -l /system/etc/security/cacerts/4f74014f.0`
  * Then running `su`, and then `whoami` (should now be root), and then running the `mount` and `ls` commands again.

Can you also confirm exactly which Bluestacks version you're using?

Hopefully that should provide some clues about what's going on here.

**Comment by LaserSlime** [comment]
I'm using Bluestacks 5.11.42.1001 N32.
Bluestacks doesnt have "Security, Encryption & Credentials" in the android settings.

Outputs as shell:
```
OnePlus5:/ $ getprop ro.build.version.release
getprop ro.build.version.release
7.1.1
OnePlus5:/ $ mount
mount
rootfs on / type rootfs (ro,seclabel,size=1033284k,nr_inodes=78384)
proc on /proc type proc (rw,relatime,gid=3009,hidepid=2)
sysfs on /sys type sysfs (rw,seclabel,relatime)
/dev/sda1 on /boot/android type ext4 (ro,seclabel,relatime,data=ordered)
/dev/sda1 on /system type ext4 (ro,seclabel,relatime,data=ordered)
tmpfs on /cache type tmpfs (rw,seclabel,relatime)
/dev/sdb1 on /data type ext4 (rw,seclabel,relatime,data=ordered)
/dev/sda1 on /system/lib/libc.so type ext4 (ro,seclabel,relatime,data=ordered)              ^
/dev/sda1 on /system/lib/libstdc++.so type ext4 (ro,seclabel,relatime,data=ordered)
/dev/sda1 on /system/lib/libmedia.so type ext4 (ro,seclabel,relatime,data=ordered)
/dev/sda1 on /system/lib/libmediaplayerservice.so type ext4 (ro,seclabel,relatime,data=ordered)
/dev/sda1 on /system/lib/libaudioflinger.so type ext4 (ro,seclabel,relatime,data=ordered)
/dev/sda1 on /system/lib/libcameraservice.so type ext4 (ro,seclabel,relatime,data=ordered)
debugfs on /sys/kernel/debug type debugfs (rw,seclabel,relatime,mode=755)
tmpfs on /dev type tmpfs (rw,seclabel,nosuid,relatime,mode=755)
devpts on /dev/pts type devpts (rw,seclabel,relatime,mode=600,ptmxmode=000)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
none on /acct type cgroup (rw,relatime,cpuacct)
tmpfs on /mnt type tmpfs (rw,seclabel,relatime,mode=755,gid=1000)
none on /config type configfs (rw,relatime)
none on /dev/cpuctl type cgroup (rw,relatime,cpu)
none on /dev/cpuset type cgroup (rw,relatime,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent)
pstore on /sys/fs/pstore type pstore (rw,seclabel,relatime)
none on /cache type tmpfs (rw,seclabel,nosuid,nodev,noatime)
tmpfs on /storage type tmpfs (rw,seclabel,relatime,mode=755,gid=1000)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,seclabel,relatime)
none on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
none on /mnt/windows/Documents type vboxsf (ro,nodev,relatime)
none on /mnt/windows/Pictures type vboxsf (ro,nodev,relatime)
none on /mnt/windows/InputMapper type vboxsf (rw,nodev,relatime)
none on /mnt/windows/BstSharedFolder type vboxsf (rw,nodev,relatime)
/data/media on /mnt/runtime/default/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6)
/data/media on /storage/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6)
/data/media on /mnt/runtime/read/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=23)
/data/media on /mnt/runtime/write/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7)
/dev/sdb1 on /system/xbin type ext4 (rw,seclabel,relatime,data=ordered)
OnePlus5:/ $ ls -l /system/etc/security/cacerts/4f74014f.0
ls -l /system/etc/security/cacerts/4f74014f.0
ls: /system/etc/security/cacerts/4f74014f.0: No such file or directory
```
Outputs as root:
```
OnePlus5:/ # getprop ro.build.version.release
getprop ro.build.version.release
7.1.1
OnePlus5:/ # mount
mount
rootfs on / type rootfs (ro,seclabel,size=1033284k,nr_inodes=78384)
proc on /proc type proc (rw,relatime,gid=3009,hidepid=2)
none on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
sysfs on /sys type sysfs (rw,seclabel,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,seclabel,relatime,mode=755)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,seclabel,relatime)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
pstore on /sys/fs/pstore type pstore (rw,seclabel,relatime)
/dev/sda1 on /boot/android type ext4 (ro,seclabel,relatime,data=ordered)
/dev/sda1 on /system type ext4 (ro,seclabel,relatime,data=ordered)
/dev/sda1 on /system/lib/libc.so type ext4 (ro,seclabel,relatime,data=ordered)
/dev/sda1 on /system/lib/libstdc++.so type ext4 (ro,seclabel,relatime,data=ordered)
/dev/sda1 on /system/lib/libmedia.so type ext4 (ro,seclabel,relatime,data=ordered)
/dev/sda1 on /system/lib/libmediaplayerservice.so type ext4 (ro,seclabel,relatime,data=ordered)
/dev/sda1 on /system/lib/libaudioflinger.so type ext4 (ro,seclabel,relatime,data=ordered)
/dev/sda1 on /system/lib/libcameraservice.so type ext4 (ro,seclabel,relatime,data=ordered)
/dev/sdb1 on /system/xbin type ext4 (rw,seclabel,relatime,data=ordered)
tmpfs on /cache type tmpfs (rw,seclabel,relatime)
none on /cache type tmpfs (rw,seclabel,nosuid,nodev,noatime)
/dev/sdb1 on /data type ext4 (rw,seclabel,relatime,data=ordered)
tmpfs on /dev type tmpfs (rw,seclabel,nosuid,relatime,mode=755)
devpts on /dev/pts type devpts (rw,seclabel,relatime,mode=600,ptmxmode=000)
none on /dev/cpuctl type cgroup (rw,relatime,cpu)
none on /dev/cpuset type cgroup (rw,relatime,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent)
none on /acct type cgroup (rw,relatime,cpuacct)
tmpfs on /mnt type tmpfs (rw,seclabel,relatime,mode=755,gid=1000)
none on /mnt/windows/Documents type vboxsf (ro,nodev,relatime)
none on /mnt/windows/Pictures type vboxsf (ro,nodev,relatime)
none on /mnt/windows/InputMapper type vboxsf (rw,nodev,relatime)
none on /mnt/windows/BstSharedFolder type vboxsf (rw,nodev,relatime)
/data/media on /mnt/runtime/default/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6)
/data/media on /mnt/runtime/read/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=23)
/data/media on /mnt/runtime/write/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7)
none on /config type configfs (rw,relatime)
tmpfs on /storage type tmpfs (rw,seclabel,relatime,mode=755,gid=1000)
/data/media on /storage/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6)
OnePlus5:/ # ls -l /system/etc/security/cacerts/4f74014f.0
ls -l /system/etc/security/cacerts/4f74014f.0
ls: /system/etc/security/cacerts/4f74014f.0: No such file or directory
```

**Comment by pimterry** [comment]
To be clear, that's running on the device after the issue has been reproduced? So the ADB interception setup has run and the app has failed to install the cert?

It doesn't show any of the settings from the setup process at all, which is very unusual given that.

You might find something interesting if you try to follow the automated setup process by hand. The code is here: https://github.com/httptoolkit/httptoolkit-server/blob/e0824930080bcac25f42950b18d206fbef526b68/src/interceptors/android/adb-commands.ts#L262-L314. Effectively, it:

* Copies HTTP Toolkit's interception CA certificate onto the device (e.g. with `adb push`) - you can get the certificate for yourself from the 'Anything' option on the Intercept page in HTTP Toolkit
* On the device, as root, it sends and then runs it a script which:
  * Creates a temp directory
  * Copies all the system certificates there
  * Creates a tmpfs mount over the top of the real system certificate directory
  * Copies the system certificates back into the new mounted directory
  * Copies the interception certificate there too
  * Sets various permissions and flags required on those files
  * Cleans up after itself

Once that's complete, you should definitely see the results in `mount` (which should show a tmpfs mount on `/system/etc/security/cacerts`) and `ls`, at least in that same terminal. I have seen issues in the past with old Magisk versions where it somehow isolated system effects to that one shell, so that you could see them there, but if you opened a separate shell on the same device they were invisible. I've also heard reports of one device where the changes were somehow isolated to root, so normal users (and normal apps) didn't see the results.

Only a handful of cases like that though, and never with Bluestacks, so I'm not sure what's going on here I'm afraid! Hopefully walking through the setup will show something failing or behaving weirdly along the way.

**Comment by pimterry** [comment]
For background, there's a detailed article explaining how this all works here: https://httptoolkit.com/blog/intercepting-android-https/

**Comment by pimterry** [comment]
Ah, ok, we're getting somewhere then! I can see how that would cause this. This is the same as a case I mentioned above:

> I've also heard reports of one device where the changes were somehow isolated to root, so normal users (and normal apps) didn't see the results.

That means we are injecting a system cert, but it's only being applied for the root user somehow...

Is this a completely vanilla Bluestacks setup? Do you have any kind of root management software, or root hiding software, or anything remotely like that that could be related to this?

**Comment by LaserSlime** [comment]
> Ah, ok, we're getting somewhere then! I can see how that would cause this. This is the same as a case I mentioned above:
> 
> > I've also heard reports of one device where the changes were somehow isolated to root, so normal users (and normal apps) didn't see the results.
> 
> That means we are injecting a system cert, but it's only being applied for the root user somehow...
> 
> Is this a completely vanilla Bluestacks setup? Do you have any kind of root management software, or root hiding software, or anything remotely like that that could be related to this?

No, I rooted it by modifying bluestacks.conf in ProgramData.

**Comment by LaserSlime** [comment]
Ok well this is interesting. The first time I tried it it also asked me to set a login password but this time it didnt glitch out and I was able to set one. It still wouldn't let me get past that screen though. But then I tried again and it said it worked however it still says "Certificate rejected" when I open apps with encrypted traffic.

**Comment by pimterry** [comment]
Yes, so that sounds like rooted setup is still failing. You've successfully installed a user certificate (so you'll be able to intercept Chrome and any apps that opt-in to interception to enable debugging) but without a system certificate HTTPS from most 3rd party apps won't be interceptable.

To be honest I'm a bit stumped. I'm not a Bluestacks expert at all, and I don't know why it wouldn't work for you when it sounds like it does work for everybody else.

@AlexNaga are you doing anything special to root your Bluestacks setup, or are you aware of any other Bluestacks configuration that might relate to this?

@LaserSlime I'd suggest maybe trying different Bluestacks versions, and fiddling with any relevant options you can find, and see if you can find something else that works. Fundamentally you need to be able to write to that `/system/etc/security/cacerts/` directory in a way that's visible to apps on the system. Right now, it seems like writes to that directory end up only visible to root for some bizarre reason. If you can't modify that directory then it's basically impossible to intercept HTTPS traffic from that emulator - not just for HTTP Toolkit, but for all existing tools anywhere that I'm aware of.

If you're really stuck and you need to get something working ASAP, I'd suggest using the official Google emulators instead, since they tend to work very reliably. There's a walkthrough for that here: https://httptoolkit.tech/blog/inspect-any-android-apps-http/

If you do manage to find any clues as to what is different about your setup or why this is happening do please share them here, I'd love to be able to investigate further!

**Comment by LaserSlime** [comment]
Hmmm I guess I will try to use the android studio emulator if you think that will give me a higher chance of success. 

One thing I noticed with adb is that the `adb root` command doesn't seem to work. Like when I do `adb shell` after it I'm still the shell user per default and have to use `su` to switch to root perms. Or at least that's how it used to be. Now it just disconnects the device and I have to use `adb connect` to connect again for some reason.

**Comment by LaserSlime** [comment]
Ok installing apps on the android studio emulator via adb doesnt work:

adb: failed to install com.rovio.gold_3.0.27463.4821-4821_minAPI19(armeabi-v7a,x86)(nodpi)_apkmirror.com.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

**Comment by fdciabdul** [comment]
use LDPlayer , it's better

**Comment by LaserSlime** [comment]
> use LDPlayer , it's better

Already tried, same issue.

**Comment by fdciabdul** [comment]
> > use LDPlayer , it's better
> 
> Already tried, same issue. (To clarify I'm not talking about the screen lock problem, I already found a way around that)
> 
> And it looks like it happens using Android studio as well...

which version ? use LDPlayer v.5 instead of latest 

also on android studio you must root your AVD

**Comment by LaserSlime** [comment]
> > > use LDPlayer , it's better
> > 
> > 
> > Already tried, same issue. (To clarify I'm not talking about the screen lock problem, I already found a way around that)
> > And it looks like it happens using Android studio as well...
> 
> which version ? use LDPlayer v.5 instead of latest
> 
> also on android studio you must root your AVD

What do you mean by rooting AVD?

Also considering the same issue happened on Bluestacks 5, LDPlayer 9, Nox Emulator and Android Studio I'm starting to doubt if the emulator is the problem.

**Comment by fdciabdul** [comment]
To root and install Magisk in the Android Studio emulator, check out this link: https://github.com/newbit1/rootAVD. This is really important for this process.

If you want to manually install a certificate in LDPlayer, I've written an article about it. However, it's in my language. You can find it [here](https://imtaqin.id/cara-intercept-bypass-ssl-pinning-android-menggunakan-http-toolkit/).

Regarding your problem, it's very strange, as HTTPToolkit provides a one-click setup solution.

**Comment by AlexNaga** [comment]
To root BlueStacks I simply edited `%programdata%/BlueStacks_nxt/bluestacks.conf`
and set 

```
bst.feature.rooting="1"
bst.instance.Pie64.enable_root_access="1"
```

**Comment by LaserSlime** [comment]
> 

Thats exactly what I did.

**Comment by pimterry** [comment]
> Also considering the same issue happened on Bluestacks 5, LDPlayer 9, Nox Emulator and Android Studio I'm starting to doubt if the emulator is the problem.

I'm not sure what's going on either, but to be clear this is _definitely_ some kind of issue with emulator setup (either the specific version, or how it's rooted, or some other app messing with things, or something else with your system somewhere).

The challenge isn't with HTTP Toolkit itself, or any other tool that's involved.

If you want to be able to intercept an Android app, you must first set up an emulator where you can write certificates to `/system/etc/security/cacerts/`.

It doesn't matter what other tools you use - if you can't do that, it's game over and you'll never be able to intercept anything. If you can do that, HTTP Toolkit's automatic setup should work, but also alternatively it's possible to manually write certificates there and manually set your proxy in the Android settings, and then you won't really need the automated setup or HTTP Toolkit Android app at all (there are some other advantages in there so it's still useful - like being able to intercept just a single app - but certainly nothing critical).

In terms of Bluestacks or LDPlayer I'm still stumped though I'm afraid. I have no idea why this wouldn't work on your setup since it clearly works for others elsewhere.

> And it looks like it happens using Android studio as well...

> on android studio you must root your AVD

This shouldn't be true. If you install a 'Google APIs' or 'Android Open Source Edition' official emulator (_not_ a 'Google Play' version, _not_ the still-pre-release UpsideDownCake version) then it's rooted out of the box and it's possible to modify the certificates.

You can confirm this very quickly:

* Set up a new emulator (e.g. with a Android 13 'Google APIs' image)
* Run `adb shell`, then `su`, then `whoami` (shows `root` - ADB root access is always enabled)
* Run `mount -t tmpfs tmpfs /system/etc/security/cacerts`
* In the emulator, go to Settings -> Security -> Encryption & credentials -> Trusted Credentials
* System tab is completely empty (because we've created an empty mount, hiding it, effectively removing all system certs)

If that works, everything else should work (because then you can write any certs you like into that mount, and they'll be trusted to intercept traffic).

I've just tested this in a brand new Android 13 'Google APIs' emulator myself, and the above all works correctly. If that's not working, and you're definitely using the correct image versions, something _extremely_ weird is happening, and your computer is haunted by ghosts or hacked by the CIA, I dunno :shrug:

**Comment by LaserSlime** [comment]
I'm using an Android 7.0 x86 image since x86_64 doesn't seem to work with the app I'm trying to intercept. From what I've heard it also has issues with Android 13 in general since it hasn't been updated since 2018. Not to mention that the Android 13 emulator is laggy to the point of being nearly unusable.

I have tried those mount commands and they seem to have worked on the Android 7.0 x86 image.

**Comment by LaserSlime** [comment]
Update: My app had a file with certificate inside the apk. Adding the httptoolkit certificate to that file fixed it.

Except now the problems described in #480 happen on my pc.
