### ISSUE TITLE
[Bug]: System Trust Disabled Android 14.x beta [Rooted]

### ISSUE THREAD

**Issue by crtyx** [httptoolkit/httptoolkit#447]
### Repro steps

1. Connect device via the usual android device via adb method.
2. Ensure user CA certificate is installed.
3. Double check device is rooted; true.
4. Grant SU perms.
5. System trust still disabled despite root access.

### How often does this bug happen?

Every time

### The desktop OS you're using

Android 14

### Details of other apps/devices

Pixel 7 Pro
Official Developers Beta - 14.x

**Comment by crtyx** [comment]
```
Android command [ 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `shell`
Android command [ 'su', '-c', 'sh /data/local/tmp/htk-root-test.sh' ] returned `root`
Android command [ 'su', '-c', 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `root`
Android command [ 'su', 'root', 'sh', '/data/local/tmp/htk-root-test.sh' ] threw Timeout for ADB command su,root,sh,/data/local/tmp/htk-root-test.sh
Error: Timeout for ADB command su,root,sh,/data/local/tmp/htk-root-test.sh
```

**Comment by crtyx** [comment]
Thanks for the super quick response. Shall flash a 13.x ROM for time being.

**Comment by PatrickKing** [comment]
Ok, this explains why every attempt to add a system CA cert has failed for me recently (via HTTP Toolkit and other approaches).

I might suggest adding a word about the Android version requirement to [the docs](https://httptoolkit.com/docs/guides/android/).

**Comment by pimterry** [comment]
I'm going to close this, as interception on Android 14 has since been fixed! This should work correctly nowadays using all recent HTTP Toolkit versions. More info on the blog here: https://httptoolkit.com/blog/android-14-install-system-ca-certificate/.

If you're still having issues, please look at the docs (https://httptoolkit.com/docs/guides/android/#system-certificates-are-not-trusted) for basic debugging steps first, and open a new issue if that doesn't provide any clues about what's going on.
