### ISSUE TITLE
[Bug]: UI crashed - unable to launch the app

### ISSUE THREAD

**Issue by RandyLutcavich** [httptoolkit/httptoolkit#451]
### Repro steps

Did a fresh install HTTP Toolkit on my Mac M1 and it will not start.
Always crashes immediately and says to file a bug on Github.

### How often does this bug happen?

Every time

### The desktop OS you're using

Apple M1 Pro - 32 GB - Version 13.4.1 (22F82)

### Error screenshot

<img width="260" alt="image" src="https://github.com/httptoolkit/httptoolkit/assets/104787261/6c306bdf-9453-4cba-89a8-a38eb68d3b0b">

**Comment by RandyLutcavich** [comment]
This issue resolved itself for me when I upgraded my Mac to Version 13.4.1 (22F770820d)

**Comment by RandyLutcavich** [comment]
After working once it is now broken again with this error now:
<img width="1286" alt="image" src="https://github.com/httptoolkit/httptoolkit/assets/104787261/b3c7cfea-03c1-454d-85f8-47c38f399dd4">

**Comment by pimterry** [comment]
Hmm, I haven't seen this myself, I'm not sure what could cause that. 

There may be more information available in the log files - those are stored at `/Users/<username>/Library/Logs/httptoolkit/`.

In general, as far as I can tell exit code 137 means that HTTP Toolkit's internal server was killed by a SIGKILL signal, i.e. it was shut down by your operating system directly, or some other process on your machine. I think that could plausibly be due to some security configuration that didn't allow it to start, or your machine being out of memory, or various other similar cases, but I don't think there's any way to tell from this error alone.
