### ISSUE TITLE
[Bug]: Android interception setup fails, only shows 301 responses

### ISSUE THREAD

**Issue by scerdan** [httptoolkit/httptoolkit#462]
### Repro steps

It does not install certificates automatically, nor does it link emulators on windows 11 or on android physical device.

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11, Android

### Details of other apps/devices

Using in Windows 11 and Android SO 13

### Error screenshot

![image](https://github.com/httptoolkit/httptoolkit/assets/70868577/dfdc00e2-7d3c-450e-91d8-dd7abff98c59)

**Comment by pimterry** [comment]
Hi @scerdan, what rules do you have on the mock page? HTTP Toolkit should return a response to that config request, not the 301 redirect that you're seeing here. That's controlled by a rule that's automatically created when you click the Android intercept buttons. It should appear in the 'Default rules' section.

**Comment by scerdan** [comment]
Ohh Thank you so much! Is this going to happen every time I reinstall the
software?

**Comment by pimterry** [comment]
No - this won't happen automatically at all! I think you'll only hit this issue if you create a rule above the default Android rule, which matches the same requests, and then you set up Android interception afterwards.

If you intercept the device first, or you create a rule that doesn't match this specific `http://android.httptoolkit.tech/config` URL, or similar, then you won't have this issue.

I do have plans in future to build a 'priority rules' system, so that this rule doesn't conflict with others by default, but it's not enabled quite yet. Coming soon :smile:.

I'll close this for now anyway, glad it's working for you now. Do open another issue if you have any more problems or any other feedback at all.
