### ISSUE TITLE
[Bug]: System trusted cetificate not working since last update

### ISSUE THREAD

**Issue by UwUDev** [httptoolkit/httptoolkit#465]
### Repro steps

1. Open cmd and type `adb shell su` to verify if i still have root acces
2. Launch http toolkit om my pc
3. Connect with the option "Android device with ADB"

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10 (21H2)

### Details of other apps/devices

The phone is a Pixel 6a on android 13
Also tryed on my Fedora 38 with same result

### Error screenshot

![Screenshot_20230826-202137](https://github.com/httptoolkit/httptoolkit/assets/61664271/ae594cd6-72a8-4b51-92f4-dadbadfc39ac)
You can see the SU access notification at the bottom

### Any other info?

I tried to reboot my phone, remove and re add root acces to the shell, delete the app, reinstall user trusted cetificates but i get the same issue

**Comment by UwUDev** [comment]
I forgot to mention that the certificate was installed as "system trusted" but since then it's been removed when I connected with adb.

**Comment by UwUDev** [comment]
I _think_ it's an update issue because I just reinstalled it and before i had no problems.

[last-run.log](https://github.com/httptoolkit/httptoolkit/files/12458137/last-run.log)

For the device info it's my physical Google Pixel 6a, running on androd 13 AOSP (TQ3A.230605.010.A1) but since it's a Google device you can maybe emulate it in android studio. Rooted with magisk by patching the boot.img and flashing it manually. Also zygisk is enabled but i did not changed it between the two tests.

Hope it helps!

**Comment by pimterry** [comment]
I'm think it's likely this was due to the Android 14 related changes that appeared around this time (shortly before the Android 14 release) and affected some rooted devices on older versions, disabling system trust setup. That's now working correctly, so you shouldn't see this any more.

If you're still having issues, please look at the docs (https://httptoolkit.com/docs/guides/android/#system-certificates-are-not-trusted) for basic debugging steps first, and open a new issue if that doesn't provide any clues about what's going on.

**Comment by UwUDev** [comment]
Hey,
You're right, even though I have Android 13 I actually had to do the same method as for Android 14 and everything works!
Thanks again :)
