### ISSUE TITLE
[Bug]: Android QR intercept does not work with desktop app ver v1.14.0, only works with v1.14.1

### ISSUE THREAD

**Issue by hoangtan1998** [httptoolkit/httptoolkit#466]
### Repro steps

1. Open desktop app ver 1.14.0
2. Click Android device via QR code
3. Use mobile phone QR scanner to scan QR code on desktop
4. Keep getting "Oh no!" message

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11

### Details of other apps/devices

Every android device I have with MIUI 12.5

### Error screenshot

![photo_2023-09-08_09-30-07](https://github.com/httptoolkit/httptoolkit/assets/41163654/b9ee6421-bd73-4d32-b5c5-cef8724df7f4)

### Any other info?

Try use Desktop app v 1.14.1 seems to work

**Comment by pimterry** [comment]
There's normally two possible causes for this:

* The device can't connect to your computer by any IP that the computer is aware of
* You've modified the rules in HTTP Toolkit so that the app can't read the config it's expecting

You can tell which by looking at the View page on your computer while this happens. If a request is shown there, then the connection is good and there must be an issue with your rules (check that you don't have a rule overriding the `http://android.httptoolkit.tech/config` rule), or something very unexpectedly failing elsewhere.

If no request is shown, then the proxy port on your computer isn't accessible from your phone via any IP addresses your computer is aware of. That can be caused by local network limitations (some business networks block communication between local devices) or due to a firewall on your computer that you'll need to disable.

You can get more information via ADB if you run `adb logcat -T1` and then watch the logs while this happens.
