### ISSUE TITLE
Was about to purchase the pro version, but....

### ISSUE THREAD

**Issue by enthusedcoder** [httptoolkit/httptoolkit#503]
_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

I was just about to purchase the pro version of this very useful tool to unlock all of the features and support you, the developers, for creating such useful software.  However, when I attempted to purchase the pro version of the software, I was shocked to discover that you don't actually sell the pro version of your software.  You rent it out, and I will personally only pay a monthly subscription for a service that is provided to me (eg cloud storage), and refuse to entertain the idea of supporting any software developer that would only offer to rent their software out by actually renting the software.  In short, I would highly recommend that you offer a "lifetime license" option for customers to purchase as well, as it will attract customers like myself who would otherwise refuse to rent your product, as I would personally rather litterally burn money than rent software.  Just something to consider.

**Comment by pimterry** [comment]
The code is provided fully open source (even the Pro bits) with no subscription required whatsoever. If that's all you need, no renting required, go wild.

Actual products like HTTP Toolkit though require ongoing maintenance: support interactions like this one, keeping integrations up to date as the world changes ([Android changes](https://httptoolkit.com/blog/android-14-install-system-ca-certificate/), browser changes, new OS releases, HTTP changes, etc), handling security vulnerabilities in dependencies, maintaining software update & user account infrastructure, keeping up to date with changing legislation (CRA, GDPR), billing issues (refunds, chargebacks, ongoing queries, changing tax & invoicing rules worldwide, payment provider changes, etc), documentation (which again must change as the world changes), etc etc etc. These all have ongoing costs, just like cloud storage (frankly, far more expensive than cloud storage). I can't take on indefinite ongoing costs for customers for a fixed one-time fee without the fee being enormous. It's a bad result for everybody. Subscriptions meanwhile solve this: ongoing fees for an actively maintained product.

On the positive side, it's a financially better deal for the majority of actual customers. A large proportion of HTTP Toolkit users use it only intermittently, for specific problems, rather than using it every day. With a subscription, they pay just for a single month, just when they need it. In all scenarios that ends up at a dramatically cheaper lifetime cost than any plausible price for a perpetual license would be.

For the users who do use it daily and keep an active subscription indefinitely, it gets cheaper (~30%) paying annually, and although they're paying more they're also getting significantly more value out of it (at least, I very much hope if you use HTTP Toolkit Pro every single day you're doing so because it helps you a lot!).

Subscriptions also make HTTP Toolkit significantly more accessible in global markets. The vast majority of software developers don't live in the US or western Europe, and often have much tighter cashflow. There's a particularly large number of HTTP Toolkit users in India, Indonesia and Brazil. India alone has 30% more HTTP Toolkit users than the entire US. In a lot of the countries like these, a large upfront cost is a serious problem, and smaller payments just for the time you need are extremely helpful.

Last point: subscriptions align incentives. If I sell you a product once, I have very little incentive to maintain it or improve it for you later. Even in an 'annual new version paid upgrade' model, I'd have weird incentives (e.g. it's clearly beneficial to hold back good updates or bug fixes late in the year, and only include those in the next big version upgrade). Subscription incentives are simple and good for everybody: make great software, maintain & update it to keep customers happy all the time, release improvements as quickly as possible. No funny business.

Does that make more sense? I get the conceptual concern about 'renting', but fundamentally a product is a lot more than just the code. I've been doing this for quite a while now, I've talked to a _lot_ of customers, and as a solo developer if HTTP Toolkit wasn't sold by subscription then the business model wouldn't work to let me do this, and it just wouldn't exist at all.

**Comment by enthusedcoder** [comment]
Your loss
