### ISSUE TITLE
 error when initializing

### ISSUE THREAD

**Issue by HKONCHKS** [httptoolkit/httptoolkit#504]
Startup failed: "API error during getConfig: GraphQL errors (2): Cannot read properties of undefined (reading 'apiConfig') at systemProxy, Cannot read properties of undefined (reading 'apiConfig') at config"
Please [file an issue](https://github.com/httptoolkit/httptoolkit/issues/new), and we'll get this fixed ASAP

Could you tell me how to resolve it?

**Comment by pimterry** [comment]
This is already reported, see #481. Please check for existing issues in future, it saves you and everybody else lots of time & hassle! That issue is also pinned right at the top of the issues list.

Take a look at [the solution](https://github.com/httptoolkit/httptoolkit/issues/481#issuecomment-1748401917) discussed there, and that should resolve this for you straight away.
