### ISSUE TITLE
Allow non-Pro users to use Unrecognized HTTPS Certificates

### ISSUE THREAD

**Issue by lavish440** [httptoolkit/httptoolkit#521]
Hi I am a student and I use HTTP Toolkit very often. It is very useful for me. 
Recently, I was debugging my website which doesn't have a valid HTTPS certificate but HTTP Toolkit didn't forward the request because it doesn't allow non-Pro users to use Invalid HTTPS Certificates. 
Please add this feature to non-Pro users as well. 

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi @lavish440! HTTP Toolkit by default does trust any certificate for requests to localhost sites, and of course it trusts Let's Encrypt and other free providers that you'd normally use for any site quickly published on the internet for testing. Is there a reason you're using a self-signed certificate that's not covered by either of those cases?

The expectation is that the invalid/extra CA certificates option is mostly for use by people building internal company services and similar tools - the kind of users who are happy to pay for tools, because they make money directly by using them.

It would be useful to understand that context if you could share more information, but regardless HTTP Toolkit is actually free for students anyway :smile:. To confirm this, can you please send me an email at tim @ httptoolkit.com from your student email address (e.g. you@your-school.com) or ask a professor to email me from theirs, or share something else to demonstrate this? Happy to set up a year of HTTP Toolkit Pro for you if you can just confirm that.

**Comment by lavish440** [comment]
My website is not on localhost and I have borrowed a sub-domain from a friend. The website uses a CA certificate from GlobalSign nv-sa. 
I sent a mail to Tim hoping he would respond. 
Closing this for now.

**Comment by lavish440** [comment]
@pimterry I mailed Tim 2 days ago and till now I got no response. My project is stuck because of that issue. Can please confirm the email address again?

**Comment by pimterry** [comment]
> I mailed Tim 2 days ago and till now I got no response.

@lavish440 yes, it was the weekend. See your email for your student account details.

**Comment by lavish440** [comment]
Thanks a bunch. 
I can confirm that I have got the Pro Subscription for 1 year.
