### ISSUE TITLE
[Bug]: Android device via QR code not working on Windows Installer Version

### ISSUE THREAD

**Issue by ataraxia-admail** [httptoolkit/httptoolkit#543]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

1. Open desktop app 1.14.8 (Windows Installer Ver)
2. Scan android QR with android phone
3. "Oh No" Message

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11

### Details of other apps/devices

Trying to connect with Unrooted Android 14 Phone 

### Error screenshot

![image_2024-01-15_152945774](https://github.com/httptoolkit/httptoolkit/assets/149305951/78914f8a-0d0b-4a33-8c5d-2afeae052b36)

### Any other info?

NOTE: ADB method works but doesn't for QR method with **Windows Installer Ver** but QR method does actually work for **Windows Standalone Ver**

So.... following the docs for the "Oh No" Message. (**Windows Installer Ver**)
1. They are on the same network (also allowed HTTP toolkit to communicate through Windows Firewall )
2. I don't think i have any rules overriding the "android.toolkit" rule
![image](https://github.com/httptoolkit/httptoolkit/assets/149305951/03b526b0-4610-4bef-9d2c-a4f813485aff)

**Comment by pimterry** [comment]
When this happens, can you see any incoming requests on the View page? When the app tries to connect, you should be able to see requests to that android.httptoolkit.tech/config URL. If you can't, that means that there's a connection issue somewhere (i.e. HTTP Toolkit can't detect the right IP, or your local network is blocking connections, or there's a firewall issue).

If you can see that, then the connection is working OK, and something else is going wrong - in that case, you can check the logs on your Android device by running `adb logcat -T1` and then reproducing the issue, and you can check the logs on HTTP Toolkit desktop from the menu under Help -> View HTTP Toolkit Logs.

**Comment by ataraxia-admail** [comment]
Nothing on the view page, the app is allowed to communicate through windows firewall and i doubt that its a connection issue, considering it works for the other version of the same app.

Because when the scenario is reproduced on the **standalone version** of the HTTP toolkit, it **works perfectly**.
It just **doesn't work** on the **windows installer version** of the app.

**Comment by pimterry** [comment]
> Because when the scenario is reproduced on the standalone version of the HTTP toolkit, it works perfectly.
> It just doesn't work on the windows installer version of the app.

That doesn't make very much sense - the code is exactly the same. The only difference is where the application is stored. There must be some other difference here or a different version being used or similar.

> Nothing on the view page, the app is allowed to communicate through windows firewall and i doubt that its a connection issue

If there is nothing on the View page, it's very very very likely to be a connection issue. If the connection is good, you should always see something on the View page.

The first thing that app does to connect is to send an HTTP request to HTTP Toolkit via every IP address the computer has. Every request that arrives will appear on the View page. In this case, for some reason no requests are arriving.

Can you please run `adb logcat -T1`, then reproduce the issue, and then share the logs? That will include the list of detected IP addresses, the connection result for each address, and any other errors that occurred.

You can also test the connection manually, by simply opening HTTP Toolkit's address in a browser on your phone. E.g. if you go to `http://192.168.0.1:8000` (using the correct IP & port for your computer!) in a browser on your phone, then if the connection is good then you should see that request appear in HTTP Toolkit (the response will probably be an 500 error because it's a direct request that can't be handled, but that doesn't matter). That should always work, even if nothing is configured.

**Comment by ataraxia-admail** [comment]
Ok, i tried something else and kinda found the issue.
Well..... ur right, it is an issue with the firewall, once i disabled Microsoft Defender Firewall, it works fine.

> That doesn't make very much sense - the code is exactly the same. The only difference is where the application is stored. There must be some other difference here or a different version being used or similar.

It seems that the standalone version of the app that is located in my downloads folder, does not have to deal with firewalls which allowed it to work properly by default somehow, unless specifically set to be blocked from in "Allowed Apps"


So, am i setting up the "Allowed Apps" for firewall wrongly? (probably)
1. I placed the file location of the executable below in to "Allowed Apps" and ensured it is ticked, as well as for Private and Public Networks. Location "C:\Users\user_name\AppData\Local\Programs\httptoolkit\HTTP Toolkit.exe"
2. Even tried adding a rule at Inbound + Outbound rules that allows Domain+Private+Public.

Am i missing something? Isn't the firewall setup for this same as other executables too?


> Can you please run adb logcat -T1, then reproduce the issue, and then share the logs? That will include the list of detected IP addresses, the connection result for each address, and any other errors that occurred.

Heres [adb log file](https://github.com/httptoolkit/httptoolkit/files/13939589/adblog1.txt) if u still need it?

> You can also test the connection manually, by simply opening HTTP Toolkit's address in a browser on your phone. E.g. if you go to http://192.168.0.1:8000 (using the correct IP & port for your computer!) in a browser on your phone, then if the connection is good then you should see that request appear in HTTP Toolkit (the response will probably be an 500 error because it's a direct request that can't be handled, but that doesn't matter). That should always work, even if nothing is configured.

No requests, nothing (windows installer version), probably microsoft defender

**Comment by pimterry** [comment]
> So, am i setting up the "Allowed Apps" for firewall wrongly? (probably)

No idea, I'm not really familiar with the windows firewall settings, you'd need to research that for yourself.

I think normally it prompts you on the first run, and as long as you allow connections at that point everything usually works correctly. If you don't, I'm not sure how to resolve that manually.

The quick fix would be to just disable your firewall entirely, but that requires you to fully trust the rest of your local network.

You might be able to expose just a single port (HTTP Toolkit's proxy port, 8000 by default) via the firewall: https://www.windowscentral.com/how-open-port-windows-firewall. That should be low risk.

**Comment by ataraxia-admail** [comment]
> You might be able to expose just a single port (HTTP Toolkit's proxy port, 8000 by default) via the firewall: https://www.windowscentral.com/how-open-port-windows-firewall. That should be low risk.

Well, that doesn't help either, so i guess its best to just leave the solution for this issue as "Just use the standalone version"

**Comment by pimterry** [comment]
> guess its best to just leave the solution for this issue as "Just use the standalone version"

That's not quite right.

This is a problem with windows firewall settings. There's no specific difference between the settings required for the standalone & installed versions, the only difference is the location that they're installed. It's not clear what your configuration issue is, but it will be totally possible with different settings to flip the issue so that the windows installer version works and the standalone version does not.

I understand that the standalone version is currently working on your machine, but that's something to do with your firewall config. I'm glad that's a useful workaround for you, but it's not a general solution that's going to work for anybody else who runs into this issue.

**The general solution for this issue is to configure your firewall correctly to allow connections to HTTP Toolkit, or disable it entirely** (which you confirmed above worked correctly, thanks, so that's good as another workaround here).

One possibility to get the windows installer version working: do you have a node.exe app listed in your firewall settings? It's possible that the internal HTTP Toolkit server could appear like this since that's the internal binary used for the proxy. Note that the location of this binary could change every update though (in general it'll reprompt you for firewall settings at the time). The location will be somewhere within AppData but I think it can depend on your OS configuration I'm not sure.

It might also be interesting to look at blocked connections in the firewall settings, if possible. I'm not sure if that's available, but if so it might offer some clues to fix this.

**Comment by ataraxia-admail** [comment]
> One possibility to get the windows installer version working: do you have a node.exe app listed in your firewall settings? It's possible that the internal HTTP Toolkit server could appear like this since that's the internal binary used for the proxy. 

Wait, somehow its blocked for the installer version, we've found the main cause of the entire issue here, now it finally works properly after allowing node.exe on the firewall
