### ISSUE TITLE
[Bug]: mock does not modify request body

### ISSUE THREAD

**Issue by slimedalimea** [httptoolkit/httptoolkit#550]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

everytime i do a mock rule to modify the request body, both automatic and manually, it always does the oringial body

### How often does this bug happen?

Every time

### The desktop OS you're using

widnows 10

**Comment by pimterry** [comment]
I'm fairly sure your request is being modified, and this is just confusion about the current UX.

Can you explain how you know the request isn't being modified?

If it's just because you're still seeing the original content in HTTP Toolkit, that's expected - HTTP Toolkit always shows the _original_ content that the client sent, and the final content the client receives. It doesn't show the upstream request & response data from the server perspective, even if that differs. It's always the client's perspective.

Most of the time that's what you want, although I see how it can be confusing in cases like this. Extending the UX there to explicitly show both client & server perspectives is tracked already here: https://github.com/httptoolkit/httptoolkit/issues/250.

If that's not what's happening, and you're editing the request but you can see (e.g. in server logs) that the server is not receiving your modifications, please do share more information, but I think it needs to be in video form or clear steps I can reproduce for myself. I've just tested manually, and request editing does seem to be working for me.

https://httpbin.org/anything might be useful for testing - that will directly echo the request content back to you so you can see the server's POV.
