### ISSUE TITLE
[Bug]: Working with real root devices

### ISSUE THREAD

**Issue by null8tr** [httptoolkit/httptoolkit#556]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

When I want to connect HTTP toolkit through ADB first it shows me a one second popup to grant root permission from the app then when I saw I couldn't accept it I turned on auto grant permission and it still did not work 

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10

### Details of other apps/devices

POCO X3 NFC

**Comment by pimterry** [comment]
Hmmm, I'm not sure what's happening here. How is your device rooted?

HTTP Toolkit requires that either:

* You can run `adb shell` and then use `su` to run root commands
* Or, you can run `adb root` to enable root access via ADB, then run `adb shell` to get root access

You may be able to run those commands yourself to check how that works on your device. In many root configurations there's an option for "Enable ADB root access" that you might need to enable.

**Comment by null8tr** [comment]
I enabled it before I created this issue but still not working

**Comment by null8tr** [comment]
Uploading Screenrecorder-2024-02-24-22-56-46-434.mp4…

**Comment by null8tr** [comment]
https://github.com/httptoolkit/httptoolkit/assets/54307278/8e606e95-ef4c-454a-bc80-03def3fb4c8d

**Comment by pimterry** [comment]
Hmm, that's very unusual! It should definitely show 'Connecting...' there and at least some kind of error or something.

Can you please:

* Restart HTTP Toolkit & your device
* Run `adb logcat -T1` in a terminal
* Launch ADB interception from HTTP Toolkit again
* Stop the logcat command and share the output here
* Open the HTTP Toolkit logs (Help -> View HTTP Toolkit logs) and share the output of those here too

That should give us the full logs for this from both your computer and your phone, hopefully there'll be a clue in there somewhere.

**Comment by null8tr** [comment]
[last-run.log](https://github.com/httptoolkit/httptoolkit/files/14520898/last-run.log) this is http toolkit log
[logcat.txt](https://github.com/httptoolkit/httptoolkit/files/14520901/logcat.txt) this is adb log

**Comment by pimterry** [comment]
Thanks @null8tr. That clearly shows the problem, in the logcat output:

```
03-07 11:36:37.038  1897  6208 I ActivityTaskManager: START u0 {act=tech.httptoolkit.android.ACTIVATE dat=https://android.httptoolkit.tech/... flg=0x10000000 cmp=tech.httptoolkit.android.v1/tech.httptoolkit.android.RemoteControlMainActivity} from uid 2000 from pid 3042 callingPackage com.android.shell
03-07 11:36:37.039  1897  6208 D PKMSImpl: preCheckUidPermission: permission　denied, perm=android.permission.INJECT_EVENTS
03-07 11:36:37.039  1897  6208 W ActivityTaskManager: Permission Denial: starting Intent { act=tech.httptoolkit.android.ACTIVATE dat=https://android.httptoolkit.tech/... flg=0x10000000 cmp=tech.httptoolkit.android.v1/tech.httptoolkit.android.RemoteControlMainActivity } from null (pid=3042, uid=2000) requires android.permission.INJECT_EVENTS
```

What's happening here is:

* HTTP Toolkit does all the certificate injection setup via ADB beforehand (this probably works I would guess, but hard to tell)
* HTTP Toolkit installs the Android app, if not already present
* HTTP Toolkit sends an intent, containing a URL (`android.httptoolkit.tech/...`) with the configuration for your computer that the app should connect to at the end.
* For some reason, your device refuses permission to send an intent to the app like this because the calling app (package `com.android.shell` - the ADB shell process running on the device) doesn't have the `INJECT_EVENTS` permission.

That last bit is confusing and quite unusual - notably `com.android.shell` [explicitly declares](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/packages/Shell/AndroidManifest.xml#174) this permission, and it should definitely work.

The HTTP Toolkit intent sending code is [here](https://github.com/httptoolkit/httptoolkit-server/blob/b74fdfb563bfea2d2c1ef35314e51c0f4b399abb/src/interceptors/android/android-adb-interceptor.ts#L121-L126) which uses `startActivity` from adbkit [here](https://github.com/DeviceFarmer/adbkit/blob/c16081384ca34addbdab318bda3c76434b7538af/src/adb/DeviceClient.ts#L483-L495), which says "Roughly analogous to `adb shell am start <options>`". The command is an officially supported ADB feature, the google docs are [here](https://developer.android.com/tools/adb#shellcommands).

I'm confident this works on most devices (this works successfully on thousands of devices every day) so there must be something unusual about your setup... The best similar example I can find is [this discussion](https://github.com/Genymobile/gnirehtet/issues/5). There's some commands there that might be interesting for debugging, and at the end it says:

> The issue seems to be resolved by heading over to Developer Options on MIUI, and enabling the following:
> * USB debugging -Debug mode when USB is connected
> * Install via USB -Allow installing apps via USB
> * USB debugging (Security Settings)- Allow granting permissions and simulating input via USB debugging

Are all those enabled on your device? The last one particularly would cause this I think.

**Comment by PiggyAwesome** [comment]
@pimterry Your solution helped me tremendously. Thank you for your effort in solving this issue!
