### ISSUE TITLE
[Bug]: Certificate has expired

### ISSUE THREAD

**Issue by mariusuncrop** [httptoolkit/httptoolkit#574]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

1. Use the steps from `Intercepting iOS HTTP` page: https://httptoolkit.com/docs/guides/ios/
2. Check network traffic on View page of HTTP Toolkit desktop app => no traffic is intercepted; assuming it's because the certificate has expired

### How often does this bug happen?

Every time

### The desktop OS you're using

MAC)S 14

### Error screenshot

![image](https://github.com/httptoolkit/httptoolkit/assets/28760204/1614f029-2067-49b4-95c5-6ba0c37a34ba)
![image](https://github.com/httptoolkit/httptoolkit/assets/28760204/4a19d97e-2f55-4043-b365-486ae525430c)

### Any other info?

This used to work just fine up until recently

**Comment by pimterry** [comment]
Interesting, that's quite unusual! The certificate lasts a year, and should be regenerated automatically if it has less than 48 hours left when HTTP Toolkit starts.

Have you had HTTP Toolkit running constantly for more than 2 days? If you completely close and restart the app, and then do iOS setup again, does it work? If not it would be helpful if you could share your log file, available in the menu under Help -> View HTTP Toolkit logs.

**Comment by pimterry** [comment]
Hmm, that log pretty strongly suggests you haven't actually restarted the app - you've just reopened the window. When the app opens, it should create an empty log file, but this log file has 5 "App Started" lines (when new windows are opened) and 2516x "Updating CLI" lines (from a background update check that runs once every 5 minutes).

This may be a Mac UX issue: unlike Windows & Linux, simply closing a window on Mac never closes the program or doesn't stop anything from running. You need to actual quit the app (from the menu bar, or with Cmd+Q) and start it again.

**Comment by pimterry** [comment]
Great! Glad that's working for you now :+1:

I'll look into this UX and see if we can find a good way to make this clearer. I think we could probably detect this and prompt you to a restart once/day if your cert has expired, for example, which would avoid most confusing cases here...

Unfortunately it's not really possible to update the certificate while HTTP Toolkit is running, but since it's only once a year, and only if you don't restart the app, I think that's probably OK.

Thanks for reporting this, do let me know if you run into any other issues at all.
