### ISSUE TITLE
Method unrecognisable 

### ISSUE THREAD

**Issue by conducked2** [httptoolkit/httptoolkit#577]
---

Everytime I load the app it says the attached and the actual app wont load unless i turn https off
![aff67e167656503ff3e6d6be141c07fa](https://github.com/httptoolkit/httptoolkit/assets/166819445/64200ecc-5cd7-478f-90ca-dc23de463318)

**Comment by pimterry** [comment]
Hmm, that's very odd. It's hard to help more though without any info, can you share more details? Which app is this, what OS are you using, how is it set up, and how are you intercepting it?

In general, traffic like this means you're intercepting something that is not HTTP, but that's quite unusual with most setups.

**Comment by conducked2** [comment]
The app is called evony on Android, if I use a app on ios called http catcher it works but if I use http toolkit it doesn't work anymore, it works on other apps fine just evony stopped working, 

I'm on Android emulator, as soon as i run http toolkit it freezes the game but as soon as I turn off http toolkit it loads the game again but as above if I use a different program on ios it loads fine 

Adb debugging, and I'm intercepting it as you would any other way :)

It works fine with other apps but within the last 2 months it stopped with evony and I'm just confused why it doesn't work with http toolkit but it loads with http catcher on ios

I need to be able to save the .har once I captured the ones I need

**Comment by conducked2** [comment]
> Hmm, that's very odd. It's hard to help more though without any info, can you share more details? Which app is this, what OS are you using, how is it set up, and how are you intercepting it?
> 
> In general, traffic like this means you're intercepting something that is not HTTP, but that's quite unusual with most setups.

Any idea with the above reply?

**Comment by pimterry** [comment]
I've done a little more testing. This is definitely not HTTP, or anything else I recognize. The actual data starts with `39 00 00 00 01 00 00 00 0a 00 00 00 32 37 37...`. In ASCII, 0x39 => 9, 0x32 => 2, 0x37 => 7, and all the other 0X characters are unprintable, so this prints as `9[???]277`. Hard to know what that data actually is though.

The traffic itself is sent outbound to port 443, ignoring HTTP proxy settings (but forcibly captured by HTTP Toolkit's VPN). It's seemingly sent in plain text, which is extra weird, since 443 is normally the HTTPS port, so should always be TLS traffic (which this is definitely not - TLS always starts with `0x16`).

Since it's seemingly not using TLS, you can 'intercept' this raw using Wireshark or similar and you'll be able to see all the bytes of the traffic. It's possible there's some other non-TLS custom encryption involved there or something though. There's basically no tools you can use to go beyond that, if you're interested in this traffic you'll need to look through the bytes yourself and work out what they mean.

As an alternative though, if you're not interested in this traffic, you can just remove 443 from the forcibly intercepted ports (in the HTTP Toolkit Android app, while it's connected) and then you won't see this traffic at all. If you do so, the game loads successfully, and you still see various other HTTP requests going on. Whether that works for you depends on what you're trying to do and what this traffic actually is, but you'll need to decide that for yourself.

Either way, it's not HTTP, so HTTP Toolkit can't do much beyond ignoring this. I'm going to close this issue, since it's not really an HTTP Toolkit issue, but do feel free to comment here if you work out more about what's going on to help any others finding similar traffic in future.
