### ISSUE TITLE
[Bug]: in pause the requests it's not work  

### ISSUE THREAD

**Issue by 00x1337** [httptoolkit/httptoolkit#582]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

pause the requests

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10

### Error screenshot

![image](https://github.com/httptoolkit/httptoolkit/assets/35100055/e22a2c35-6eca-4939-b9af-f24ff9e0518d)
![image](https://github.com/httptoolkit/httptoolkit/assets/35100055/1960632c-f390-4857-97c9-99f4b137166e)

### Any other info?

I paid the subscription and also it's doesn't work as you can see 
SUBSCRIPTION STATUS
Active
SUBSCRIPTION PLAN
Pro (monthly)
NEXT RENEWS
in 1 month (20th of May 2024)

**Comment by pimterry** [comment]
Hi @00x1337. Can you explain what you mean when you say "not work"? What do you expect it to do that it's not doing? Is there some kind of error shown?

**Comment by pimterry** [comment]
To clarify then: what the pause button should do is stop new requests appearing in HTTP Toolkit, so the View page data should stop changing. It doesn't block traffic on the network or anything else like that (you can do that if you like, but you have to do so with a mock rule that defines exactly _how_ you want to block the traffic).

Does that make sense? Happy to investigate this further if you can explain what you were expecting or what's wrong here given that, but otherwise I'm going to close for now.
