### ISSUE TITLE
[Bug]: Android QR code fails to connect to HTTPToolkit on Debian on ChromeOS

### ISSUE THREAD

**Issue by techandsoftware** [httptoolkit/httptoolkit#583]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

1. Installed HTTPToolkit on Debian inside ChromeOS's Linux container
2. Configure port 8000 in the linux port forwarding settings on ChromeOS
3. Start httptoolkit on Debian
4. Scan the QR in the Android app

Observed: On Android, shows the  'oh no' error and fails to connect

My Android device and Chromebook are on the same network.  But, the Linux container on ChromeOS has a different IP to the computer's actual network IP. Could this be the reason it's not connecting, if the QR is presenting the container's IP and not the host's IP?

If I manually configure the proxy on Android with the host IP, then I can see connections hitting httptoolkit in the View pane, but they fail because of the HTTPS cert is rejected by the Android apps. 

### How often does this bug happen?

Every time

### The desktop OS you're using

Debian 12, in ChromeOS 123

### Details of other apps/devices

Samsung Galaxy S10, Android 12

### Any other info?

# debian - ip a
: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
5: eth0@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:f0:00:f7 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 100.115.92.197/28 brd 100.115.92.207 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fd43:d93a:f0a0:1:216:3eff:fef0:f7/64 scope global dynamic mngtmpaddr 
       valid_lft 9944sec preferred_lft 2744sec
    inet6 fe80::216:3eff:fef0:f7/64 scope link 
       valid_lft forever preferred_lft forever

ChromeOS local IP is 192.168.1.12

**Comment by pimterry** [comment]
The easiest way to confirm this is to look at the device logs via ADB (`adb logcat -T1`, then rerun the setup). That will include the list of all tested IPs and the results.

You can also just look at the View page as a quick test: if the proxy address & port is accessible to the device, you should at least one request for `android.httptoolkit.tech/config` appearing there during setup.

This commonly can have issues due to firewalls blocking local network connections, but from what you describe, I think it is indeed very likely that the problem is that the IP addresses HTTP Toolkit on your computer is aware of aren't reachable at all from the Android device.

If that's the case, you'll need to either:

* Do manual setup via Android proxy settings, using some address for your container that is reachable from the Android device
* Use ADB-based setup, via an ADB server running inside your container (ADB-based setup tunnels your proxy traffic over ADB, which can avoid many network issues)
* Use host-mode networking (or similar) for your container so that the IP address it sees is visible from Android

> but they fail because of the HTTPS cert is rejected by the Android apps.

That sounds like a different issue: in general, if you're not using a rooted device, most apps will reject your certificate. For your certificate to be trusted, either the app needs to opt into trusting it (e.g. trusting user-installed certificates by default - notably Chrome does this) or you need to use root access to modify the system store. I've written a post with more info on that here: https://httptoolkit.com/blog/intercepting-android-https/

Does that all make sense?
