### ISSUE TITLE
Copy cURL option in context menu of a API Call

### ISSUE THREAD

**Issue by SurajValluru** [httptoolkit/httptoolkit#587]
If I have some error status code from backend, more often than not, they request for a cURL to debug further. Right now, I'm copying the headers and url and giving it to ChatGPT to parse it to cURL.

Having an option in context menu is a real time saver in desktop version.

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by SurajValluru** [comment]
### This is the context menu I'm referring to

<img width="421" alt="Screenshot 2024-05-04 at 9 57 09 PM" src="https://github.com/httptoolkit/httptoolkit/assets/80475876/c0e3525a-90ab-4cae-82a1-4baa7a8c6c63">

**Comment by pimterry** [comment]
This already exists. At the bottom of the context menu there, you can see that with [HTTP Toolkit Pro](https://httptoolkit.com/get-pro/) you can copy a request as a code snippet in various formats (including cURL, and 20+ others) directly from that menu.

With Pro, the context menu will also automatically update to show your preferred option. So in addition to the full set of submenus here to select _any_ format, your last-used format will also be automatically shown at the top-level so you can access it in one click.

![Screenshot from 2024-05-06 11-02-25](https://github.com/httptoolkit/httptoolkit/assets/1526883/95a2ed47-7ab9-4bf2-8741-b6c98a1e8947)

(Context menu styles here are different just because this is on Linux).

By the way, if you're using ChatGPT for precise reproductions of issues with just copied headers, I'd be a little careful - it's very good for getting an _approximate_ curl command, but it often misses details. It's worth running generated commands back through HTTP Toolkit to compare to the original and check it matches. I tried to use it last week to create a test command to send HTTP trailers, and it invented a `--trailers` command line argument that doesn't exist :laughing:. There are also important details that are used to generate equivalent snippets here that are less obvious, such as matching the HTTP version used, handling compression appropriately depending on whether that was present etc.

**Comment by oceloteczek15** [comment]
8$ to copy curl bruv

**Comment by vipulyaara** [comment]
I see other formats but not cUrl in this menu. I am using HttpToolkit Pro Version 1.19.3 (1.19.3)

**Comment by pimterry** [comment]
@vipulyaara Curl is shown by default in the "Copy as Code Snippet" list under the "Shell" category.

The screenshow above shows it at the top level because it was the last selected format. Whichever type you selected most recently is shown there for convenience, but if you've never used any code snippet format then that won't appear there, and you'll need to find it in the correct subcategory.

**Comment by vipulyaara** [comment]
Got it. Thank you.
