### ISSUE TITLE
[Bug]: Httptoolkit Error_proxy_certificate_invalid happening with me (tried many solutions not working)

### ISSUE THREAD

**Issue by anony0mous** [httptoolkit/httptoolkit#593]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

I downloaded HttpToolkit on my brand new computer, tried it, and kept getting the error_proxy_certificate_invalid no matter what. I googled, tried every possible solution and I can't fix the problem. Can someone help please, this is the first time i ever run into this problem!?

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11 Pro

### Details of other apps/devices

- Intercepting a fresh chrome and global chrome.

### Error screenshot

![Screenshot 2024-05-19 091434](https://github.com/httptoolkit/httptoolkit/assets/63921706/f98ff9f6-6a03-4829-a976-2b54588e4c79)

**Comment by pimterry** [comment]
Hi @anony0mous, thanks for reporting this. I'm not sure exactly what's happening, so it would be helpful if you can share a little more information:

* Has HTTP Toolkit worked before for you on this network, or is this the first time? If it's worked before, can you think of anything that might have changed since then?
* If you completely close HTTP Toolkit, then restart your computer, and then restart the app, does this still happen?

Assuming that doesn't fix it, we'll need to investigate more. Unfortunately the error shown here isn't very helpful, but I think you can get a more detailed error by:

* Launching HTTP Toolkit
* Finding the proxy port shown on the 'Anything' option on the Intercept page (it's probably `8000`).
* Opening a normal Chrome window, totally separate from HTTP Toolkit
* Browsing to `https://localhost:8000/` (assuming that 8000 is your proxy port) in that window. Make sure you include the 'https' at the start of the URL.

This should show a "Your connection is not private" error.

If you click on the error code that's shown just underneath the explanation (e.g. `NET::ERR_CERT_AUTHORITY_INVALID`) then it will expand and show all of the details. Please share the details shown there here.

**Comment by anony0mous** [comment]
Recently, I resently got a new computer, and i downloaded and installed windows 11 pro, on my old pc it was working normally, but when i downloaded it on my new pc, i got that error. I tried deleting the certificate that httptoolkit was generating but i got the same error anyways. I even tried it on Edge and same problem showed up again. I will send some details in about an hour or two.

**Comment by anony0mous** [comment]
Ops i closed it by mistake

**Comment by anony0mous** [comment]
So i ran httptoolkit and opened chrome seperately on https://localhost:8000 and this is what i got:

Error: Passthrough loop detected. This probably means you're sending a request directly to a passthrough endpoint, which is forwarding it to the target URL, which is a passthrough endpoint, which is forwarding it to the target URL, which is a passthrough endpoint...

You should either explicitly mock a response for this URL (https://localhost:8000/), or use the server as a proxy, instead of making requests to it directly.

**Comment by pimterry** [comment]
That means your request did reach HTTP Toolkit without any security issues, because that non-intercepted Chrome window does already trust your certificate.

That definitely shouldn't happen. That means either:

* You clicked past the certificate security warning (clicking 'Advanced' -> 'Proceed to localhost...'). In this case, it'll load but it will still show "Not secure" in the URL bar
* You have installed HTTP Toolkit's CA certificate globally on your computer. You'll need to remove that in this case.
* You're opening this URL in an intercepted Chrome window. That's not what's required here: you need to use a normal non-intercepted Chrome window.

Basically: normal browsers will not trust HTTP Toolkit without special setup. If you try to open HTTP Toolkit's proxy port as a web page using a normal browser, it will give you detailed information about what it's seeing when that fails, and that's the information we need.

If that still doesn't work, there's an alternative:
* Open an intercepted Chrome window (showing the proxy_certificate_invalid error)
* Go to "chrome://net-export/" and click "Start logging to disk"
* Open a new tab, and trigger the same proxy error in that tab going to a new website
* Go back to the net export tab, stop recording and save the file
* Upload the resulting `chrome-net-export-log.json` file here

**Comment by anony0mous** [comment]
Turns out you were right, I had HttpToolkit certificate installed on my pc! After I removed it, I got this when visiting https://localhost:8000 
![image](https://github.com/httptoolkit/httptoolkit/assets/63921706/5bf93142-f0dd-42c1-b2db-6b17a38886c9)

**Comment by pimterry** [comment]
Ok, thanks, that's better. If you click the "NET::ERR_CERT_AUTHORITY_INVALID" text, it should show more details.

**Comment by pimterry** [comment]
Hmm, ok. That confirms that the certificate is approximately valid, and the dates are correct, so there's nothing super wrong here. But of course that's not very helpful! One thing that's interesting is that in my case, I see two certificates here, whereas it seems your computer is only receiving one...

I think it's worth testing the other approach too. Can you please:

- Open an intercepted Chrome window (one that shows the proxy_certificate_invalid error)
- Go to "chrome://net-export/" in that window and click "Start logging to disk"
- Open a new tab, and trigger the proxy error again in that tab by going to a few different new websites
- Go back to the net export tab, stop recording and save the file
- Upload the resulting chrome-net-export-log.json file here

**Comment by anony0mous** [comment]
[chrome-net-export-log.json](https://github.com/httptoolkit/httptoolkit/files/15377587/chrome-net-export-log.json)
There's the file!

**Comment by pimterry** [comment]
Hmm, I think you need to do more browsing there, it doesn't show much traffic at all. You can see the data yourself by opening it at https://netlog-viewer.appspot.com/#import and clicking 'Events'. It shows the proxy only activating at event number 380 out of 394, and most of the events are just initial Chrome setup traffic that's not very helpful.

While the recording is happing, you need to open a few different websites (like facebook, twitter, ebay, wikipedia, youtube, whatever) that all show this same proxy_certificate_invalid error when they load, to make sure some good example traffic is recorded. If that works correctly, there should be lots more requests in here (1000s) including lots of PROXY_CLIENT_SOCKET events (this is the part where the browser connects to HTTP Toolkit - and which probably fails on your machine).

**Comment by anony0mous** [comment]
So, i visited a couple of websites like facebook, twiiter, instagram, netlify etc. This is the update logs
[chrome-net-export-log.json](https://github.com/httptoolkit/httptoolkit/files/15377888/chrome-net-export-log.json)

**Comment by pimterry** [comment]
Thanks @anony0mous, there's definitely some interesting (and very weird) data in there. I can now clearly see the failure here, although the data itself is very surprising. It does seem like the certificate is not being delivered correctly for some reason.

It would be helpful to get one more recording if possible, using [Wireshark](https://wireshark.org), a very low-level network debugging tool. To capture this:

* Install http://wireshark.org/ and follow its instructions to get set up
* Start recording traffic
* Launch Chrome with TLS 1.3 disabled (TLS 1.3 encrypts some data, which is good for privacy but very unhelpful for this debugging). On Windows, I think you can do this by:
  * Pressing Win+R to open the Run window
  * Running `"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --ssl-version-max=tls1.2` (assuming that's where you have Chrome installed)
* Open "https://localhost:8000" in that Chrome window
* This should show a certificate error page, like we saw before
* Once that appears, you can stop recording traffic in Wireshark, and save the PCAP file (File -> Save As)

If you upload that PCAP file, it should contain the exact bytes that HTTP Toolkit is sending to the browser here, which will hopefully give a final answer.

Thanks for all your help here so far by the way! To say thanks I'm happy to give you 6 months of HTTP Toolkit Pro for free - just let me know an email address you'd like to use and I'll set you up with an account.

**Comment by anony0mous** [comment]
I hope this file helps! My email is charbelawad06@gmail.com 
[file.zip](https://github.com/httptoolkit/httptoolkit/files/15394944/file.zip)

**Comment by pimterry** [comment]
> I hope this file helps

Hi @anony0mous, that's nearly it - that's a working Wireshark recording, but it doesn't contain the localhost traffic. I think that means you've selected to only record traffic to the internet (maybe on your wifi or LAN interface) but not local traffic (which is where the interesting Chrome<->HTTP Toolkit bits are happening). Can you try again?

You can check whether the recording has the right data for yourself: just search for `tls` in Wireshark, and check there's at least one row there going to 127.0.0.1 port 8000, with "Client hello" in the info section. As long as it has a TLS connection including that start part, it should be possible to look at the key magic bytes I need to see.

> My email is...

Thanks! I've now set up an account for you - just click 'Get Pro' then 'Log into existing account' and enter that email to get started.

**Comment by anony0mous** [comment]
There's the updated file that contains https://localhost:8000
[file1.zip](https://github.com/httptoolkit/httptoolkit/files/15402203/file1.zip)
I hope this helps! :)
