### ISSUE TITLE
i want to intercept or capture data:image/png;base64

### ISSUE THREAD

**Issue by farisyusry** [httptoolkit/httptoolkit#605]
---

_is it possible to intercept or capture data:image/png;base64?._

**Comment by pimterry** [comment]
Hi @farisyusry. When a data URLs like this is loaded, there is no network traffic (so there's nothing to capture). If you have the URL, you already have all the data.

I imagine you have a URL that looks something like this: `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII`

When a browser tries to load this data (e.g. because it's the `src` for an `<img>` tag) it doesn't make a request anywhere. Instead, it takes the base64 string (all the text after the `data:image/png;base64,` part) and decodes it ([base64](https://en.wikipedia.org/wiki/Base64) is a way of encoding binary data - so decoding this will turn that string back into raw bytes) and then treats that data like it's a png image. It's the same as if a network request happened, and returned the decoded base64 data (the raw bytes, not the string).

Does that make sense?

What that means is that if you have a URL like this, and you're trying to work out what the data is, all you have to do is decode the base64 data (e.g. pasting the base64 part after the `,` into the input field on [this website](https://gchq.github.io/CyberChef/#recipe=From_Base64('A-Za-z0-9%2B/%3D',true,false)&oeol=VT)). For an image specifically, the resulting data won't make much sense (it'll show you the raw data of the image) but you can use a tool like https://base64.guru/converter/decode/image to easily see this for yourself.

I'll close this, as it's not something HTTP Toolkit can help with (there is no network traffic happening when a URL like this is loaded) but let me know if you have any other questions at all.
