### ISSUE TITLE
[Bug]: Unable to intercept traffic on edge/firefox: ERR_PROXY_CERTIFICATE_INVALID / This browser does not trust the HTTP Toolkit certificate authority

### ISSUE THREAD

**Issue by ocp1006** [httptoolkit/httptoolkit#622]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

1. Open HTTP Tookit latest version: 1.19).
2. Approve any firewall request for NodeJS.
3. Try to intercept by either using Firefox or Edge.
4. Edge shows: 
![image](https://github.com/user-attachments/assets/dd227bd5-5976-4fd1-91d9-4540e95eeabe)
5. Firefox shows:
![image](https://github.com/user-attachments/assets/7c45ebbc-90c9-40d7-9f72-6378361644cc)

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11 Pro, 23H2 (22631.4037)

### Details of other apps/devices

Firefox version: 129.0.2 (64-bit)
Edge version: Version 128.0.2739.54 (Official build) (64-bit)

### Any other info?

1. I used to work with Fiddler Classic, but I remove it before installing HTTP Tool kit. I used BCUninstall to make sure there are no leftovers and I even restarted my PC before installing HTTP Tool kit.
2. I deleted the old certificates, located on `C:\Users\<username>\AppData\Local\httptoolkit\Config\ca.{key,pem}` and restarted HTTP Tool kit. New certificates were generated, but that didn't solve the issue.

**Comment by xKiian** [comment]
Do you see anything in toolkit or maybe the logs? That could help

**Comment by ocp1006** [comment]
Here's what I see on Firefox
![image](https://github.com/user-attachments/assets/a53745b1-0761-43fb-87ea-952e35daa261)
Edge didn't yield anything.
Here are the logs for both Firefox run and Edge run.
I see exceptions about finding certificates.
[last-run-edge.log](https://github.com/user-attachments/files/16825572/last-run-edge.log)
[last-run-firefox.log](https://github.com/user-attachments/files/16825573/last-run-firefox.log)

**Comment by pimterry** [comment]
Thanks for reporting this @ocp1006. There's definitely something wrong here...

What's supposed to happen is that the first time Firefox is intercepted, it's quickly run once with some special arguments, just for a second, so that it creates an empty profile on disk for HTTP Toolkit, then it's closed and the certificate is manually injected into that profile, and then it's started up with that profile like normal. That means the first time you'll see an open-close flash, and then after that it's just loading the same profile every time.

Each time it's used, it checks the profile is still working (by trying to connect to a local test server and checking the certificate is trusted) and then you see the 'failed test' message above only if that fails. In that case, it's supposed to clear the profile, to reset and start from scratch, which should recover from any kind of profile corruption. If you try to use HTTP Toolkit to launch and then exit Firefox a couple of times, does that eventually happen? Complete failure is detected if Firefox closes without the certificate check ever succeeding - you should see `Firefox certificate check failed` specifically shown in the logs if that's detected properly (but I can't see it in the log output here - maybe it's not detecting that Firefox has exited?).

If that's definitely not appearing, after a couple of tries, can you try closing HTTP Toolkit, deleting the FF profile manually, and then trying again? The profile path on Windows is `C:\Users\<username>\AppData\Local\httptoolkit\Config\firefox-profile`. You can just delete that directory, and then next time you try to launch the app from HTTP Toolkit it will recreate it. Does that work?

**Comment by ocp1006** [comment]
@pimterry Thanks for the reply.
I tried doing both, I even deleted the `cache` folder, browser data and removed the config folder, all failed.
I'm attached the log + video of my test.

https://github.com/user-attachments/assets/841fb0c2-e1ae-4f0f-805a-f6d11f322632
[last-run.log](https://github.com/user-attachments/files/16847296/last-run.log)

Looking at the log, I see the error:
```
[19044:22492:0903/132324.596:ERROR:cert_verify_proc_builtin.cc(1069)] CertVerifyProcBuiltin for 127.0.0.1 failed:
----- Certificate i=0 (O=Mockttp Cert - DO NOT TRUST,L=Unknown,C=XX,CN=localhost) -----
ERROR: No matching issuer found
```
Could it be that I don't even have the certificate installed?
I opened `certmgr`. Where should the certificate be located?

**Comment by pimterry** [comment]
Oh I see, Edge isn't working either! I had misunderstood. That's much less complicated, and should _definitely_ work.

Do you have any kind of anti-virus or something on your computer that could be intercepting your traffic as well? That would interfere with HTTP Toolkit and cause this. I've heard reports in the past that ESET does this automatically, do you have that installed?

**Comment by ocp1006** [comment]
@pimterry I have ESET antivirus installed. I disabled it, deleted the profiles and configurations and it still fails :(
[last-run.log](https://github.com/user-attachments/files/16872097/last-run.log)

**Comment by pimterry** [comment]
> I have ESET antivirus installed

That is almost certainly the key problem here then. It's not actually that you need to disable the virus scanning though, it's the TLS scanning feature that causes problems.

You can disable this in the ESET settings, I believe it's under "Advanced setup" then "SSL/TLS". This ESET behaviour intercepts all encrypted traffic on your machine, and then blocks all traffic to HTTP Toolkit because it doesn't recognize it, which causes certificate failures just like this. Does that work?

Once that's done correctly, Edge (or Chrome etc) should work immediately. If that's not working, that's almost certainly because of something to do with ESET somehow. I'd suggest aiming to fix that first, and then investigating Firefox separately (which can be a bit more complicated, but will probably just work once Edge etc are working).

In the case of Chromium browsers like Edge, they're configured just by passing the certificate's signature on the command line when it's launched - there's no complicated profile state or anything - and the only times I've ever seen that fail is when there is some other software (like ESET) which is intercepting traffic before HTTP Toolkit does.

**Comment by xKiian** [comment]
You should be able to just add the toolkit folder as an exception in eset settings. You can google how it works for eset.
