### ISSUE TITLE
[Bug]: Frida

### ISSUE THREAD

**Issue by mrafieefard** [httptoolkit/httptoolkit#632]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

Using frida adb option 
Faild to fetch apps

### How often does this bug happen?

Every time

### The desktop OS you're using

Arch 6.10.9

### Details of other apps/devices

Using Poco X3 NFC

### Any other info?

(node:36043) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:577:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":577,"columnNumber":1}

**Comment by pimterry** [comment]
Hmm, that's odd, I haven't seen that before. Seems that Frida has got itself into a weird state. Are you installing & launching Frida yourself, or did HTTP Toolkit install it for you?

If you restart HTTP Toolkit, does the same error keep happening? What about if you restart the android device completely?

**Comment by mrafieefard** [comment]
I installed it with HTTP Toolkit and yes I try it now and still get error

**Comment by pimterry** [comment]
It sounds like this is some kind of issue with Frida generally and your device. It suggests either a Frida bug, or a fundamental issue with your device configuration I think. 

To debug it further, unfortunately I suspect you'd need to manually stop HTTP Toolkit's Frida server (closing HTTP Toolkit and restarting your android device will do this) and then install and start your own Frida, attempt to run scripts manually, and debug the details of why that isn't working.

In HTTP Toolkit's case, we're using Frida server 16.3.3, so that's a good place to start (and that will probably fail) but you may find that older or newer versions might fix your issue. If you do find a new version that works, let me know and HTTP Toolkit could potentially upgrade to fix that. Regardless, if any Frida server of any version is already running in the device, HTTP Toolkit will use that automatically without launching its own.

**Comment by nutterthanos** [comment]
problem is that not all frida versions support every device profile/config/android versions etc

**Comment by helloryuko** [comment]
Doing some research it seems that the latest Google Play system update (not the Android update) broke Frida.
`pm uninstall com.google.android.art` and a reboot fixed this issue for me.

**Comment by mrafieefard** [comment]
> Doing some research it seems that the latest Google Play system update (not the Android update) broke Frida. `pm uninstall com.google.android.art` and a reboot fixed this issue for me.

Thanks it seems working

**Comment by mrafieefard** [comment]
But I fo

**Comment by pimterry** [comment]
Yes, there's some more details in https://github.com/httptoolkit/httptoolkit-server/issues/134 too.

This is fundamentally a Frida issue that we can't resolve ourselves - HTTP Toolkit will update Frida to an official fixed release once one is available, but they're still working on that. The Frida issue tracking this is here: https://github.com/frida/frida/issues/2958

**Comment by fripokoff** [comment]
> Doing some research it seems that the latest Google Play system update (not the Android update) broke Frida. `pm uninstall com.google.android.art` and a reboot fixed this issue for me.

Worked for me too, thank you so much :D
