### ISSUE TITLE
Directly get requests via root access instead of proxy.

### ISSUE THREAD

**Issue by pgcoordinates** [httptoolkit/httptoolkit#634]
Instead of going with the process of trusting the certificate by system on rooted android, which causes some official google APIs not to work when proxy is connected, is it not possible to directly get http requests information via root access without connecting to any proxy ?

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Not really. There are some interesting approaches that go in that direction, but it's a completely different technique that comes with its own tradeoffs and limitations. At a minimum, it requires intercepting all raw packet network traffic (this requires a VPN or some complex scripts to rewrite all usage of known network APIs) and intercepting all encryption calls (e.g. writing a separate Frida hook for every known TLS API). Most cases where proxying won't work, this also won't work (because many apps doing the kind of advanced certificate pinning that's actually difficult to break aren't using standard easy-to-hook APIs to do so).

Meanwhile HTTP proxying is a well supported standard technology, and certificate trust is relatively easy to control & debug etc.

I'm going to close this issue. It's an interesting area of research if that's something you're in to, and I wouldn't be surprised if serious solutions mature there in the coming years, but in the short term it's harder, less compatible, and not significantly more capable.
