### ISSUE TITLE
[Bug]: Not finding Adb

### ISSUE THREAD

**Issue by seven305** [httptoolkit/httptoolkit#635]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

I open Genymotion first, then Http toolkit and it cant find the adb, this never happened before.

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11

### Error screenshot

![image](https://github.com/user-attachments/assets/8d548cc3-6362-4b0b-803c-73cb343635f3)

**Comment by pimterry** [comment]
This is covered in the docs here: https://httptoolkit.com/docs/guides/android/#common-issues

See the info there for more details, but in general this means HTTP Toolkit can't connect to ADB on your computer, or it's connected but there are no available devices. In both cases, this is something you'll need to debug with ADB rather than HTTP Toolkit. You may also be able to find more info in the logs (Help -> View HTTP Toolkit logs).
