### ISSUE TITLE
[Bug]: Android app via Frida can no longer be connected

### ISSUE THREAD

**Issue by ItsMarcoDE** [httptoolkit/httptoolkit#665]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

Latest Google Play System Update ruins Frida. That's why the HTTP Toolkit function “Android App via Frida” is completely without function on my Pixel 8 with Android 15.

You can find more information here:
https://github.com/frida/frida/issues/2958#issuecomment-2490266689

You can also find a corrected Frida version there:
https://github.com/frida/frida/issues/2958#issuecomment-2488844579

It would be great if the HTTP Toolkit could be set to the corrected version. It is currently not clear when this bug in Frida will be fixed.

### How often does this bug happen?

Every time

### The desktop OS you're using

MacOS 15

### Details of other apps/devices

Pixel 8 with Android 15

**Comment by pimterry** [comment]
Yep, see https://github.com/httptoolkit/httptoolkit-server/issues/134 for some more discussion of this.

Unfortunately fixing it on our side is easier said than done - we need to support quite a few different architectures, and the current model works entirely by download official Frida releases on demand for the current device. In general I'm not especially keen to rebuild Frida with random unofficial patches and host our own release server to work around this - this is really something that needs fixing by the official Frida project.

In the meantime, PRs to HTTP Toolkit to at least make the failure cleaner would be welcome - I'd be perfectly happy to detect this issue and link to workaround instructions instead.

You can also use HTTP Toolkit with your own custom Frida version if you like, if you do want to use the patched release. If Frida is already running on the device on the default port (or HTTP Toolkit's custom port: 24072) then HTTP Toolkit will use that existing server automatically, instead of installing & starting its own.
