### ISSUE TITLE
[Bug]: After connecting the HTTP Toolkit all requests in the app just fails

### ISSUE THREAD

**Issue by MElkmeshi** [httptoolkit/httptoolkit#667]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

the app is kinda tricky I had to decompile it and remove Emulator detection and then compiled it works normally when i try to setup HTTP Toolkit all my requests fails so does anyone has any idea what maybe be the cause of this?

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows

**Comment by pimterry** [comment]
Hi @MElkmeshi. If you're seeing this happen for a specific single app, but most other apps work fine, then it's probably due to certificate pinning of some sort. You might have more luck with the 'Frida' option in HTTP Toolkit, which can handle some of this for you (it uses the scripts here: https://github.com/httptoolkit/frida-interception-and-unpinning/) or you might need to do some manual reverse engineering for this if that doesn't work. Unfortunately while HTTP Toolkit includes all sorts of general purpose scripts to handle this in most normal cases, it's not possible to 100% cover every possible kind of pinning automatically so manual work is required in those cases.

If you do need to reverse engineer & fix this yourself, there's a guide here: https://httptoolkit.com/blog/android-reverse-engineering/.
