### ISSUE TITLE
[Bug]: Installing Error in Main Process

### ISSUE THREAD

**Issue by DerErzengel** [httptoolkit/httptoolkit#679]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

When i try installing Http Toolkit i get the following error (Screenshot)

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11

### Error screenshot

![image](https://github.com/user-attachments/assets/b4777066-acb8-4364-83b6-34b40b7e7816)

**Comment by pimterry** [comment]
Hi, thanks for reporting this. This is an issue in version v1.19.2, which was just briefly live now, but has since been taken down again. If you try to redownload from the website now you should receive v1.19.1 which will work correctly.

I'll close this issue - we're looking into this in https://github.com/httptoolkit/httptoolkit-desktop/issues/79 and there should be a fix (and a corresponding v1.19.3 release) coming soon.
