### ISSUE TITLE
[Bug]: Malformed request data when using frida interception

### ISSUE THREAD

**Issue by vimbing** [httptoolkit/httptoolkit#680]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

I'm trying to intercept android app on rooted device. When using proxy intercept / adb intercept I was pretty sure, that not every request is logged in view tab. When I used frida intercept, more hosts were logged into view tab, which I suspect to be these which I am looking for. The problem is that requests data is malformed. Headers are filled with "random" chars, some hosts are shown as "unknown.invalid", and methods look like random letters. In the headers I can see some readable words, so I assume it's problem with parsing http requests. 

### How often does this bug happen?

Every time

### The desktop OS you're using

Zorin OS 17.2

### Details of other apps/devices

Phone: Xiaomi mi 8 lite
Android version: 10 QKQ11.190910.002 
App which I intercept: pl.neptis.yanosik.mobi.android version 4.0.0.2

### Error screenshot

![image](https://github.com/user-attachments/assets/49e2e198-3c2b-4bf1-9f5b-e0c5e67d5411)
![image](https://github.com/user-attachments/assets/ca190ea3-e90b-4142-afe0-1ef019f11c7c)

### Any other info?

I'm using httptoolkit-server/1.19.2 linux-x64 node-v20.18.1

**Comment by pimterry** [comment]
This means that the traffic being sent isn't actually HTTP. The Frida scripts intercept _all_ TCP traffic, so any non-HTTP TCP content will still be intercepted, and those connections will be unparseable (as shown here) and will break for the client (they'll get a 400 HTTP response, which they won't understand, and then they'll get disconnected).

ADB interception is different because it doesn't necessarily intercept _all_ traffic (although it is extremely likely that it's capturing all _HTTP_ traffic). Instead, it intercepts:

* All traffic that uses the standard Android OS HTTP proxy configuration (all normal HTTP clients & APIs will do this)
* All traffic sent to a standard HTTP(S) port. The default list for these is [here](https://github.com/httptoolkit/httptoolkit-android/blob/ea0d0268879b604f43f205b4850730cf0f7a6287/app/src/main/java/tech/httptoolkit/android/PortListActivity.kt#L14) and that's configurable in the Android app - there's an option that appears there when it's connected.

This isn't configurable yet in the Frida case - it just intercepts everything. The reason this is different is that intercepting non-HTTP traffic is a larger problem when you're intercepting a whole device since it can affect all sorts of other apps & OS behaviours. When you're intercepting just a single app, it's normally OK (and potentially quite interesting) to know when non-HTTP traffic is being sent like this, and there's not too much of it. If you want to tweak this with Frida, right now you'll need to set the scripts up yourself (see instructions [here](https://github.com/httptoolkit/frida-interception-and-unpinning/)) and then modify the port configuration in config.js [here](https://github.com/httptoolkit/frida-interception-and-unpinning/blob/main/config.js#L27-L33).

In future, this will be resolved by #645 + SOCKS integration for Frida & ADB, which will allow us to proxy this traffic successfully. You wouldn't be able to modify it and you won't get any meaningful parsing of the traffic, but the connection would work and all the raw bytes sent & received would be visible.

**Comment by realmCode** [comment]
is there a way to hide such traffic?

**Comment by pimterry** [comment]
@realmCode, yes, quite a few. It depends exactly what you want to filter, but you can try things like:

* `not(errored)` - filter out anything that wasn't successfully proxied
* `not(hostname$=.invalid)` - filter our anything where the hostname ends in `.invalid` (this covers various unparseable URL cases, but no other types of errors).
