### ISSUE TITLE
Unexpected side-affects on WebDriver sessions

### ISSUE THREAD

**Issue by mrshishirr** [httptoolkit/httptoolkit#98]
In my Windows machine, WebDirver sessions for Chrome and Firefox (didn't test other browsers yet) are getting created with default **localhost:8001** proxy, and HTTP Toolkit does not seem to provide any control on turning off the global proxy. Right now I have to mess with browser user profile and switches to override it.

Example Log from Firefox:
```
98536149127	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\
\Users\\mrahman\\AppData\\Local\\Temp\\rust_mozprofile.XjJNJYRRNmx0"
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
1598536152685	Marionette	INFO	Listening on port 14563
1598536152815	Marionette	WARN	TLS certificate errors will be ignored for this session
1598536152818	Marionette	INFO	Proxy settings initialised: {"proxyType":"manual","ftpProxy":"localhost:8001","httpProxy":"localhost:8001","sslProxy":"localhost:8
001"}
Aug 27, 2020 9:49:12 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
```

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
* Are you running these webdriver sessions at the same time as using HTTP Toolkit? Or is this happening later on, after HTTP Toolkit is closed?
* Does this go away if you completely close your HTTP Toolkit Firefox or Chrome session, and then run your webdriver session?
* Have you configured the HTTP Toolkit proxy settings manually anywhere, or are you just using automatic browser launching?
* Can you share the 'Command line' information shown on `chrome://version/` in Chrome in the webdriver browser window?

I'm not sure exactly what's going on here. HTTP Toolkit always uses a separate profile for intercepted browsers, which should mean that starting a fresh browser normally _doesn't_ use the HTTP Toolkit proxy settings. On Windows those browser profiles are stored in `C:\Users\<username>\AppData\Local\httptoolkit\Config\<browser name>`. That's the only place those settings are stored, other than in memory in the running browser. I'm not sure why webdriver would find or use those.

If the intercepted browser is still running, maybe it's connecting to that process and using it somehow, rather than properly starting a fresh process?

**Comment by mrshishirr** [comment]
* It does not matter whether HTTP Toolkit is running or not, WebDriver session seems to be picking up the global proxy settings **localhost:8001** every time. I even tried uninstalling HTTP Toolkit (out of frustration 😅), but there was no difference.
* Current user profiles are not affected with this problem, only the sessions that are created by the WebDrivers seems to be affected.
* I have not configured the global proxy anywhere; not in the system, not in the browser settings.
![image](https://user-images.githubusercontent.com/17791499/91476119-8a23c980-e86a-11ea-9cd8-b34596e501ca.png)

*  Chrome command-line information: (note that I used `--no-proxy-server` arg from the web driver capabilities myself to override this issue)
```
"C:\Program Files\Google\Chrome\Application\chrome.exe" --chrome.switches --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-extensions --disable-hang-monitor --disable-infobars --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-automation --enable-blink-features=ShadowDOMV0 --enable-logging --log-level=0 --no-first-run --no-proxy-server --password-store=basic --proxy-server=ftp=localhost:8001;http=localhost:8001;https=localhost:8001 --remote-debugging-port=0 --test-type=webdriver --use-mock-keychain --user-data-dir="C:\Users\mrahman\AppData\Local\Temp\scoped_dir36736_922023968" --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox data:,
```

I don't know how those proxy settings are getting injected in the web driver sessions. I tried terminating all the web driver binaries and completely shutting down the browsers. I had the same suspicion as yours but I thought killing the browsers and web drivers should have sufficed. Unfortunately, it didn't.

**Comment by mrshishirr** [comment]
BTW, I see the browser profile folders in `C:\Users\<username>\AppData\Local\httptoolkit\Config` but they are empty in my machine.

![image](https://user-images.githubusercontent.com/17791499/91477744-ce17ce00-e86c-11ea-8105-125f3d2e28fd.png)

**Comment by pimterry** [comment]
> I see the browser profile folders in C:\Users\<username>\AppData\Local\httptoolkit\Config but they are empty in my machine.

That's expected - the contents is deleted to reset the browser each time its run. There will be content there whilst the browser is open.

> Chrome command-line information

Based on that, it looks like this a totally independent Chrome window (it doesn't have the HTTP Toolkit options), it's not reading from the Chrome profile anywhere (it uses a separate `--user-data-dir` path), and webdriver itself is finding & injecting the proxy settings before Chrome starts (because it passes a custom `--proxy-server` option - note that it includes `ftp` for example, which HTTP Toolkit's options don't).

That means these settings aren't leaking from one browser window to another, instead they're leaking from somewhere else to webdriver, which is then using them when it launches Chrome.

That doesn't solve the question, but it helps find some new questions:

* What language & webdriver library are you using?
* How are you running webdriver? From an IDE, or a terminal, or...?
* Can you share the `*_PROXY` environment variables that your test process sees when it starts up?

**Comment by daluu** [comment]
Would be interesting & curious to evaluate whether this is a Windows only problem or also affects Mac & Linux

**Comment by pimterry** [comment]
I haven't heard any fresh reports of this even as the user base has grown, and I can't reproduce it, so I suspect this was a configuration-specific issue and I'm going to close it for now.

If anybody does have this issue though, I'd love to reopen this and talk to you about it, especially if you can provide the details in my previous comment above so I can investigate further. Feel free to reply here if so.
